/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AiApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_AiApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_AiApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/AiConfigDto.h"
#include "CppRestOpenAPIClient/model/AiSuggestion.h"
#include "CppRestOpenAPIClient/model/AiSuggestionRequest.h"
#include "CppRestOpenAPIClient/model/AiWorkerConfig.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  AiApi 
{
public:

    explicit AiApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~AiApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="aiSuggestionRequest"></param>
    pplx::task<std::shared_ptr<AiSuggestion>> aiSuggestApi(
        std::shared_ptr<AiSuggestionRequest> aiSuggestionRequest
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="aiConfigDto"></param>
    pplx::task<std::shared_ptr<AiWorkerConfig>> createWorkerApi(
        std::shared_ptr<AiConfigDto> aiConfigDto
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<AiWorkerConfig>>> listWorkersApi(
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="workerId"></param>
    /// <param name="aiSuggestionRequest"></param>
    pplx::task<std::shared_ptr<AiSuggestion>> runWorkerApi(
        utility::string_t workerId,
        std::shared_ptr<AiSuggestionRequest> aiSuggestionRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_AiApi_H_ */

