/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BankingApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_BankingApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_BankingApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/BankLookup.h"
#include "CppRestOpenAPIClient/model/HebesatzLookup.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  BankingApi 
{
public:

    explicit BankingApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~BankingApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="iban"></param>
    pplx::task<std::shared_ptr<BankLookup>> bankLookupApi(
        utility::string_t iban
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<void> bankTransactionsApi(
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="gemeindeschluessel"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="plz"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="name"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="stichtag">Stichtag for validity (YYYY-MM-DD); defaults to today. Picks row where valid_from &lt;&#x3D; date &lt;&#x3D; valid_to. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="countryCode"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::vector<std::shared_ptr<HebesatzLookup>>> hebesatzLookupApi(
        boost::optional<utility::string_t> gemeindeschluessel,
        boost::optional<utility::string_t> plz,
        boost::optional<utility::string_t> name,
        boost::optional<utility::string_t> stichtag,
        boost::optional<utility::string_t> countryCode
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_BankingApi_H_ */

