/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EmissionsApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_EmissionsApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_EmissionsApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/CreateEmissionEntry.h"
#include "CppRestOpenAPIClient/model/CreateEmissionTarget.h"
#include "CppRestOpenAPIClient/model/EmissionEntry.h"
#include "CppRestOpenAPIClient/model/EmissionFactorResponse.h"
#include "CppRestOpenAPIClient/model/EmissionTarget.h"
#include "CppRestOpenAPIClient/model/EmissionsExportResponse.h"
#include "CppRestOpenAPIClient/model/EmissionsReport.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  EmissionsApi 
{
public:

    explicit EmissionsApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~EmissionsApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createEmissionEntry"></param>
    pplx::task<std::shared_ptr<EmissionEntry>> createEmissionEntryApi(
        std::shared_ptr<CreateEmissionEntry> createEmissionEntry
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createEmissionTarget"></param>
    pplx::task<std::shared_ptr<EmissionTarget>> createEmissionTargetApi(
        std::shared_ptr<CreateEmissionTarget> createEmissionTarget
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id"></param>
    pplx::task<void> deleteEmissionEntryApi(
        utility::string_t id
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id"></param>
    pplx::task<void> deleteEmissionTargetApi(
        utility::string_t id
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="year"></param>
    pplx::task<std::vector<std::shared_ptr<EmissionEntry>>> emissionsEntriesApi(
        int32_t year
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="year"></param>
    pplx::task<std::shared_ptr<EmissionsExportResponse>> emissionsExportApi(
        int32_t year
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<EmissionFactorResponse>>> emissionsFactorsApi(
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="year"></param>
    pplx::task<std::shared_ptr<EmissionsReport>> emissionsReportApi(
        int32_t year
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<EmissionTarget>>> emissionsTargetsApi(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_EmissionsApi_H_ */

