/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OrderConfirmationApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_OrderConfirmationApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_OrderConfirmationApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/DeliveryNote.h"
#include "CppRestOpenAPIClient/model/OrderConfirmation.h"
#include "CppRestOpenAPIClient/model/OrderConfirmationCreate.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  OrderConfirmationApi 
{
public:

    explicit OrderConfirmationApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~OrderConfirmationApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="orderConfirmationCreate"></param>
    pplx::task<std::shared_ptr<OrderConfirmation>> createConfirmation(
        std::shared_ptr<OrderConfirmationCreate> orderConfirmationCreate
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="confirmationId"></param>
    pplx::task<void> deleteConfirmation(
        utility::string_t confirmationId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="confirmationId"></param>
    pplx::task<void> downloadConfirmationPdf(
        utility::string_t confirmationId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="confirmationId"></param>
    pplx::task<std::shared_ptr<OrderConfirmation>> getConfirmation(
        utility::string_t confirmationId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="search"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="includeDeleted">Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional, default to false)</param>
    pplx::task<std::vector<std::shared_ptr<OrderConfirmation>>> listConfirmations(
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> search,
        boost::optional<bool> includeDeleted
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="confirmationId"></param>
    pplx::task<std::shared_ptr<OrderConfirmation>> orderconfirmationRestore(
        utility::string_t confirmationId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="confirmationId"></param>
    pplx::task<std::shared_ptr<DeliveryNote>> pursueConfirmation(
        utility::string_t confirmationId
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_OrderConfirmationApi_H_ */

