/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PaymentGatewayApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_PaymentGatewayApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_PaymentGatewayApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/AnyType.h"
#include "CppRestOpenAPIClient/model/GatewayOAuthAuthorizeRequest.h"
#include "CppRestOpenAPIClient/model/GatewayOAuthAuthorizeResponse.h"
#include "CppRestOpenAPIClient/model/GatewayOAuthCallbackRequest.h"
#include "CppRestOpenAPIClient/model/PaymentGateway.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  PaymentGatewayApi 
{
public:

    explicit PaymentGatewayApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~PaymentGatewayApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="body"></param>
    pplx::task<std::shared_ptr<PaymentGateway>> createPaymentGatewayApi(
        std::shared_ptr<AnyType> body
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="gatewayId"></param>
    pplx::task<void> deletePaymentGatewayApi(
        utility::string_t gatewayId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<PaymentGateway>>> listPaymentGatewaysApi(
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="gatewayOAuthAuthorizeRequest"></param>
    pplx::task<std::shared_ptr<GatewayOAuthAuthorizeResponse>> oauthAuthorizeApi(
        std::shared_ptr<GatewayOAuthAuthorizeRequest> gatewayOAuthAuthorizeRequest
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="gatewayOAuthCallbackRequest"></param>
    pplx::task<std::shared_ptr<PaymentGateway>> oauthCallbackApi(
        std::shared_ptr<GatewayOAuthCallbackRequest> gatewayOAuthCallbackRequest
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="gatewayId"></param>
    /// <param name="body"></param>
    pplx::task<std::shared_ptr<PaymentGateway>> updatePaymentGatewayApi(
        utility::string_t gatewayId,
        std::shared_ptr<AnyType> body
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_PaymentGatewayApi_H_ */

