/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ShipmentApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ShipmentApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ShipmentApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/CreateShipmentRequest.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include "CppRestOpenAPIClient/model/Shipment.h"
#include "CppRestOpenAPIClient/model/ShipmentStatusUpdate.h"
#include "CppRestOpenAPIClient/model/TrackOrderRequest.h"
#include "CppRestOpenAPIClient/model/TrackOrderResponse.h"
#include "CppRestOpenAPIClient/model/TrackingInfo.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ShipmentApi 
{
public:

    explicit ShipmentApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ShipmentApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shipment"></param>
    pplx::task<std::shared_ptr<Shipment>> createShipment(
        std::shared_ptr<Shipment> shipment
    ) const;
    /// <summary>
    /// Create a real shipment for an order: calls the configured carrier&#39;s label API, stores the returned tracking/label on a new shipment row, and marks the order as shipped.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="orderNumber"></param>
    /// <param name="createShipmentRequest"></param>
    pplx::task<std::shared_ptr<Shipment>> createShipmentFromOrder(
        utility::string_t orderNumber,
        std::shared_ptr<CreateShipmentRequest> createShipmentRequest
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shipmentId"></param>
    pplx::task<void> deleteShipment(
        utility::string_t shipmentId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shipmentId"></param>
    pplx::task<std::shared_ptr<Shipment>> getShipment(
        utility::string_t shipmentId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="search"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="includeDeleted">Soft-delete entities: set true to include rows with &#x60;deleted_at&#x60; set. (optional, default to false)</param>
    pplx::task<std::vector<std::shared_ptr<Shipment>>> listShipments(
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> search,
        boost::optional<bool> includeDeleted
    ) const;
    /// <summary>
    /// Customer-facing tracking lookup: order number + email → shipment status and live carrier events. No auth (public storefront API).
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="trackOrderRequest"></param>
    pplx::task<std::shared_ptr<TrackOrderResponse>> trackOrderPublic(
        std::shared_ptr<TrackOrderRequest> trackOrderRequest
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shipmentId"></param>
    pplx::task<std::shared_ptr<TrackingInfo>> trackShipmentApi(
        utility::string_t shipmentId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shipmentId"></param>
    /// <param name="shipmentStatusUpdate"></param>
    pplx::task<std::shared_ptr<Shipment>> updateShipmentStatus(
        utility::string_t shipmentId,
        std::shared_ptr<ShipmentStatusUpdate> shipmentStatusUpdate
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ShipmentApi_H_ */

