/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ShippingThresholdApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ShippingThresholdApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ShippingThresholdApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/DeliverableResponse.h"
#include "CppRestOpenAPIClient/model/PluginError.h"
#include "CppRestOpenAPIClient/model/ShippingThreshold.h"
#include "CppRestOpenAPIClient/model/ShippingThresholdCreate.h"
#include "CppRestOpenAPIClient/model/ShippingThresholdUpdate.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ShippingThresholdApi 
{
public:

    explicit ShippingThresholdApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ShippingThresholdApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="shippingThresholdCreate"></param>
    pplx::task<std::shared_ptr<ShippingThreshold>> createShippingThreshold(
        std::shared_ptr<ShippingThresholdCreate> shippingThresholdCreate
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="thresholdId"></param>
    pplx::task<void> deleteShippingThreshold(
        utility::string_t thresholdId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="productId"></param>
    /// <param name="warehouseId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<DeliverableResponse>> getDeliverable(
        utility::string_t productId,
        boost::optional<utility::string_t> warehouseId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="thresholdId"></param>
    pplx::task<std::shared_ptr<ShippingThreshold>> getShippingThreshold(
        utility::string_t thresholdId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="productId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="warehouseId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="isActive"> (optional, default to false)</param>
    pplx::task<std::vector<std::shared_ptr<ShippingThreshold>>> listShippingThresholds(
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> productId,
        boost::optional<utility::string_t> warehouseId,
        boost::optional<bool> isActive
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="thresholdId"></param>
    /// <param name="shippingThresholdUpdate"></param>
    pplx::task<std::shared_ptr<ShippingThreshold>> updateShippingThreshold(
        utility::string_t thresholdId,
        std::shared_ptr<ShippingThresholdUpdate> shippingThresholdUpdate
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ShippingThresholdApi_H_ */

