/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SupplierConditionApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_SupplierConditionApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_SupplierConditionApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/PluginError.h"
#include "CppRestOpenAPIClient/model/SupplierCondition.h"
#include "CppRestOpenAPIClient/model/SupplierConditionCreate.h"
#include "CppRestOpenAPIClient/model/SupplierConditionUpdate.h"
#include <vector>
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  SupplierConditionApi 
{
public:

    explicit SupplierConditionApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~SupplierConditionApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supplierConditionCreate"></param>
    pplx::task<std::shared_ptr<SupplierCondition>> createSupplierCondition(
        std::shared_ptr<SupplierConditionCreate> supplierConditionCreate
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supplierConditionId"></param>
    pplx::task<void> deleteSupplierCondition(
        utility::string_t supplierConditionId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supplierConditionId"></param>
    pplx::task<std::shared_ptr<SupplierCondition>> getSupplierCondition(
        utility::string_t supplierConditionId
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="supplierContactId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="search"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::vector<std::shared_ptr<SupplierCondition>>> listSupplierConditions(
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> supplierContactId,
        boost::optional<utility::string_t> search
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="supplierConditionId"></param>
    /// <param name="supplierConditionUpdate"></param>
    pplx::task<std::shared_ptr<SupplierCondition>> updateSupplierCondition(
        utility::string_t supplierConditionId,
        std::shared_ptr<SupplierConditionUpdate> supplierConditionUpdate
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_SupplierConditionApi_H_ */

