/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiResponse_GdprExport_data.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ApiResponse_GdprExport_data_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ApiResponse_GdprExport_data_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/GdprApiKey.h"
#include "CppRestOpenAPIClient/model/GdprNotification.h"
#include "CppRestOpenAPIClient/model/GdprActivity.h"
#include "CppRestOpenAPIClient/model/GdprUser.h"
#include "CppRestOpenAPIClient/model/GdprRefreshToken.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/GdprBillingInfo.h"
#include "CppRestOpenAPIClient/model/GdprUsageEvent.h"
#include <vector>
#include "CppRestOpenAPIClient/model/GdprTenant.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class GdprActivity;
class GdprApiKey;
class GdprBillingInfo;
class GdprNotification;
class GdprRefreshToken;
class GdprTenant;
class GdprUsageEvent;
class GdprUser;


class  ApiResponse_GdprExport_data
    : public ModelBase
{
public:
    ApiResponse_GdprExport_data();
    virtual ~ApiResponse_GdprExport_data();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ApiResponse_GdprExport_data members


    std::vector<std::shared_ptr<GdprActivity>> getActivityLog() const;
    bool activityLogIsSet() const;
    void unsetActivityLog();
    void setActivityLog(const std::vector<std::shared_ptr<GdprActivity>>& value);

    /// <summary>
    /// Key identifiers and names only — never a usable credential.
    /// </summary>
    std::vector<std::shared_ptr<GdprApiKey>> getApiKeys() const;
    bool apiKeysIsSet() const;
    void unsetApiKeys();
    void setApiKeys(const std::vector<std::shared_ptr<GdprApiKey>>& value);

    std::vector<std::shared_ptr<GdprBillingInfo>> getBilling() const;
    bool billingIsSet() const;
    void unsetBilling();
    void setBilling(const std::vector<std::shared_ptr<GdprBillingInfo>>& value);

    utility::datetime getExportedAt() const;
    bool exportedAtIsSet() const;
    void unsetExportedAt();
    void setExportedAt(const utility::datetime& value);

    /// <summary>
    /// Honesty field: this document is a plain data dump, never AI-generated.
    /// </summary>
    bool isGeneratedByAi() const;
    bool generatedByAiIsSet() const;
    void unsetGeneratedByAi();
    void setGeneratedByAi(bool value);

    std::vector<std::shared_ptr<GdprNotification>> getNotifications() const;
    bool notificationsIsSet() const;
    void unsetNotifications();
    void setNotifications(const std::vector<std::shared_ptr<GdprNotification>>& value);

    /// <summary>
    /// Session records: metadata only, never the token hash.
    /// </summary>
    std::vector<std::shared_ptr<GdprRefreshToken>> getRefreshTokens() const;
    bool refreshTokensIsSet() const;
    void unsetRefreshTokens();
    void setRefreshTokens(const std::vector<std::shared_ptr<GdprRefreshToken>>& value);

    std::vector<std::shared_ptr<GdprTenant>> getTenants() const;
    bool tenantsIsSet() const;
    void unsetTenants();
    void setTenants(const std::vector<std::shared_ptr<GdprTenant>>& value);

    std::vector<std::shared_ptr<GdprUsageEvent>> getUsageEvents() const;
    bool usageEventsIsSet() const;
    void unsetUsageEvents();
    void setUsageEvents(const std::vector<std::shared_ptr<GdprUsageEvent>>& value);

    std::shared_ptr<GdprUser> getUser() const;
    bool userIsSet() const;
    void unsetUser();
    void setUser(const std::shared_ptr<GdprUser>& value);


protected:
    std::vector<std::shared_ptr<GdprActivity>> m_ActivityLog;
    bool m_ActivityLogIsSet;

    std::vector<std::shared_ptr<GdprApiKey>> m_ApiKeys;
    bool m_ApiKeysIsSet;

    std::vector<std::shared_ptr<GdprBillingInfo>> m_Billing;
    bool m_BillingIsSet;

    utility::datetime m_ExportedAt;
    bool m_ExportedAtIsSet;

    bool m_GeneratedByAi;
    bool m_GeneratedByAiIsSet;

    std::vector<std::shared_ptr<GdprNotification>> m_Notifications;
    bool m_NotificationsIsSet;

    std::vector<std::shared_ptr<GdprRefreshToken>> m_RefreshTokens;
    bool m_RefreshTokensIsSet;

    std::vector<std::shared_ptr<GdprTenant>> m_Tenants;
    bool m_TenantsIsSet;

    std::vector<std::shared_ptr<GdprUsageEvent>> m_UsageEvents;
    bool m_UsageEventsIsSet;

    std::shared_ptr<GdprUser> m_User;
    bool m_UserIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ApiResponse_GdprExport_data_H_ */
