/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BudgetKategorie.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BudgetKategorie_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BudgetKategorie_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  BudgetKategorie
    : public ModelBase
{
public:
    BudgetKategorie();
    virtual ~BudgetKategorie();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// BudgetKategorie members


    utility::string_t getBudget() const;
    bool budgetIsSet() const;
    void unsetBudget();
    void setBudget(const utility::string_t& value);

    utility::string_t getDifferenz() const;
    bool differenzIsSet() const;
    void unsetDifferenz();
    void setDifferenz(const utility::string_t& value);

    /// <summary>
    /// User-set monthly goal for the category, if any.
    /// </summary>
    utility::string_t getGoal() const;
    bool goalIsSet() const;
    void unsetGoal();
    void setGoal(const utility::string_t& value);

    utility::string_t getIst() const;
    bool istIsSet() const;
    void unsetIst();
    void setIst(const utility::string_t& value);

    utility::string_t getKategorie() const;
    bool kategorieIsSet() const;
    void unsetKategorie();
    void setKategorie(const utility::string_t& value);


protected:
    utility::string_t m_Budget;
    bool m_BudgetIsSet;

    utility::string_t m_Differenz;
    bool m_DifferenzIsSet;

    boost::optional<utility::string_t> m_Goal;

    utility::string_t m_Ist;
    bool m_IstIsSet;

    utility::string_t m_Kategorie;
    bool m_KategorieIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BudgetKategorie_H_ */
