/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateTicketRequest.h
 *
 * Request body for creating a support ticket. Wraps the generated &#x60;SupportTicketCreateDto&#x60; fields plus &#x60;message_body&#x60; which is not a Model field (used to create the initial &#x60;ticket_message&#x60;).
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_CreateTicketRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_CreateTicketRequest_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Request body for creating a support ticket. Wraps the generated &#x60;SupportTicketCreateDto&#x60; fields plus &#x60;message_body&#x60; which is not a Model field (used to create the initial &#x60;ticket_message&#x60;).
/// </summary>
class  CreateTicketRequest
    : public ModelBase
{
public:
    CreateTicketRequest();
    virtual ~CreateTicketRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// CreateTicketRequest members


    utility::string_t getChannelId() const;
    bool channelIdIsSet() const;
    void unsetChannel_id();
    void setChannelId(const utility::string_t& value);

    utility::string_t getChannelType() const;
    bool channelTypeIsSet() const;
    void unsetChannel_type();
    void setChannelType(const utility::string_t& value);

    utility::string_t getCustomerEmail() const;
    bool customerEmailIsSet() const;
    void unsetCustomer_email();
    void setCustomerEmail(const utility::string_t& value);

    utility::string_t getCustomerId() const;
    bool customerIdIsSet() const;
    void unsetCustomer_id();
    void setCustomerId(const utility::string_t& value);

    utility::string_t getCustomerName() const;
    bool customerNameIsSet() const;
    void unsetCustomer_name();
    void setCustomerName(const utility::string_t& value);

    utility::string_t getExternalId() const;
    bool externalIdIsSet() const;
    void unsetExternal_id();
    void setExternalId(const utility::string_t& value);

    utility::string_t getMessageBody() const;
    bool messageBodyIsSet() const;
    void unsetMessage_body();
    void setMessageBody(const utility::string_t& value);

    utility::string_t getOrderRef() const;
    bool orderRefIsSet() const;
    void unsetOrder_ref();
    void setOrderRef(const utility::string_t& value);

    utility::string_t getSubject() const;
    bool subjectIsSet() const;
    void unsetSubject();
    void setSubject(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_Channel_id;

    boost::optional<utility::string_t> m_Channel_type;

    boost::optional<utility::string_t> m_Customer_email;

    boost::optional<utility::string_t> m_Customer_id;

    boost::optional<utility::string_t> m_Customer_name;

    boost::optional<utility::string_t> m_External_id;

    utility::string_t m_Message_body;
    bool m_Message_bodyIsSet;

    boost::optional<utility::string_t> m_Order_ref;

    utility::string_t m_Subject;
    bool m_SubjectIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_CreateTicketRequest_H_ */
