/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * DeliveryDateCreate.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_DeliveryDateCreate_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_DeliveryDateCreate_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/model/DeliveryDateStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  DeliveryDateCreate
    : public ModelBase
{
public:
    DeliveryDateCreate();
    virtual ~DeliveryDateCreate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// DeliveryDateCreate members


    /// <summary>
    /// References the customer entity.
    /// </summary>
    utility::string_t getCustomerId() const;
    bool customerIdIsSet() const;
    void unsetCustomerId();
    void setCustomerId(const utility::string_t& value);

    /// <summary>
    /// Date actually delivered (set on fulfillment).
    /// </summary>
    utility::datetime getFulfilledDate() const;
    bool fulfilledDateIsSet() const;
    void unsetFulfilledDate();
    void setFulfilledDate(const utility::datetime& value);

    utility::string_t getNote() const;
    bool noteIsSet() const;
    void unsetNote();
    void setNote(const utility::string_t& value);

    /// <summary>
    /// Sales order number (&#x60;order.order_number&#x60;).
    /// </summary>
    utility::string_t getOrderNumber() const;
    bool orderNumberIsSet() const;
    void unsetOrderNumber();
    void setOrderNumber(const utility::string_t& value);

    /// <summary>
    /// Original date promised before rescheduling.
    /// </summary>
    utility::datetime getOriginalDate() const;
    bool originalDateIsSet() const;
    void unsetOriginalDate();
    void setOriginalDate(const utility::datetime& value);

    /// <summary>
    /// Product line item this date applies to, if per-item. References the product entity.
    /// </summary>
    utility::string_t getProductId() const;
    bool productIdIsSet() const;
    void unsetProductId();
    void setProductId(const utility::string_t& value);

    /// <summary>
    /// Date promised to the customer.
    /// </summary>
    utility::datetime getPromisedDate() const;
    bool promisedDateIsSet() const;
    void unsetPromisedDate();
    void setPromisedDate(const utility::datetime& value);

    /// <summary>
    /// One of: promised | confirmed | rescheduled | fulfilled | late | cancelled
    /// </summary>
    std::shared_ptr<DeliveryDateStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<DeliveryDateStatus>& value);


protected:
    boost::optional<utility::string_t> m_CustomerId;

    boost::optional<utility::datetime> m_FulfilledDate;

    boost::optional<utility::string_t> m_Note;

    utility::string_t m_OrderNumber;
    bool m_OrderNumberIsSet;

    boost::optional<utility::datetime> m_OriginalDate;

    boost::optional<utility::string_t> m_ProductId;

    utility::datetime m_PromisedDate;
    bool m_PromisedDateIsSet;

    boost::optional<std::shared_ptr<DeliveryDateStatus>> m_Status;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_DeliveryDateCreate_H_ */
