/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * EmploymentType.h
 *
 * Employment type.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_EmploymentType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_EmploymentType_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  EmploymentType
    : public ModelBase
{
public:
    EmploymentType();
    EmploymentType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~EmploymentType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eEmploymentType
    {
        FULLTIME,
        PARTTIME,
        CONTRACT,
        INTERNSHIP,
        TEMPORARY,
    };

    eEmploymentType getValue() const;
    void setValue(eEmploymentType const value);

    protected:
        eEmploymentType m_value;
        std::map<eEmploymentType,utility::string_t> enumToStrMap = {
        { eEmploymentType::FULLTIME, _XPLATSTR("FULLTIME") },
        { eEmploymentType::PARTTIME, _XPLATSTR("PARTTIME") },
        { eEmploymentType::CONTRACT, _XPLATSTR("CONTRACT") },
        { eEmploymentType::INTERNSHIP, _XPLATSTR("INTERNSHIP") },
        { eEmploymentType::TEMPORARY, _XPLATSTR("TEMPORARY") }
};
        std::map<utility::string_t,eEmploymentType> strToEnumMap = {
        { _XPLATSTR("FULLTIME"), eEmploymentType::FULLTIME },
        { _XPLATSTR("PARTTIME"), eEmploymentType::PARTTIME },
        { _XPLATSTR("CONTRACT"), eEmploymentType::CONTRACT },
        { _XPLATSTR("INTERNSHIP"), eEmploymentType::INTERNSHIP },
        { _XPLATSTR("TEMPORARY"), eEmploymentType::TEMPORARY }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_EmploymentType_H_ */
