/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * JobApplication.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_JobApplication_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_JobApplication_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ApplicationStatus.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  JobApplication
    : public ModelBase
{
public:
    JobApplication();
    virtual ~JobApplication();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// JobApplication members


    /// <summary>
    /// Relative path of the stored CV file under the upload dir.
    /// </summary>
    utility::string_t getCvFile() const;
    bool cvFileIsSet() const;
    void unsetCvFile();
    void setCvFile(const utility::string_t& value);

    /// <summary>
    /// Extracted CV text, used for match-scoring.
    /// </summary>
    utility::string_t getCvText() const;
    bool cvTextIsSet() const;
    void unsetCvText();
    void setCvText(const utility::string_t& value);

    utility::string_t getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();
    void setEmail(const utility::string_t& value);

    utility::string_t getMatchReason() const;
    bool matchReasonIsSet() const;
    void unsetMatchReason();
    void setMatchReason(const utility::string_t& value);

    /// <summary>
    /// 0-100 LLM match score against the posting&#39;s required profile.
    /// </summary>
    int32_t getMatchScore() const;
    bool matchScoreIsSet() const;
    void unsetMatchScore();
    void setMatchScore(int32_t value);

    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    utility::string_t getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();
    void setPhone(const utility::string_t& value);

    /// <summary>
    /// References the job_posting entity.
    /// </summary>
    utility::string_t getPostingId() const;
    bool postingIdIsSet() const;
    void unsetPostingId();
    void setPostingId(const utility::string_t& value);

    /// <summary>
    /// website | email | board
    /// </summary>
    utility::string_t getSource() const;
    bool sourceIsSet() const;
    void unsetSource();
    void setSource(const utility::string_t& value);

    /// <summary>
    /// new | reviewing | interview | hired | rejected
    /// </summary>
    std::shared_ptr<ApplicationStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<ApplicationStatus>& value);


protected:
    boost::optional<utility::string_t> m_CvFile;

    boost::optional<utility::string_t> m_CvText;

    boost::optional<utility::string_t> m_Email;

    boost::optional<utility::string_t> m_MatchReason;

    boost::optional<int32_t> m_MatchScore;

    boost::optional<utility::string_t> m_Name;

    boost::optional<utility::string_t> m_Phone;

    boost::optional<utility::string_t> m_PostingId;

    utility::string_t m_Source;
    bool m_SourceIsSet;

    std::shared_ptr<ApplicationStatus> m_Status;
    bool m_StatusIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_JobApplication_H_ */
