/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * KycRecord.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_KycRecord_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_KycRecord_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  KycRecord
    : public ModelBase
{
public:
    KycRecord();
    virtual ~KycRecord();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// KycRecord members


    /// <summary>
    /// Referenz auf den Kunden/Kontakt.
    /// </summary>
    utility::string_t getCustomerId() const;
    bool customerIdIsSet() const;
    void unsetCustomerId();
    void setCustomerId(const utility::string_t& value);

    /// <summary>
    /// Name des Kunden (für die Suche).
    /// </summary>
    utility::string_t getCustomerName() const;
    bool customerNameIsSet() const;
    void unsetCustomerName();
    void setCustomerName(const utility::string_t& value);

    /// <summary>
    /// Datum der KYC-Prüfung (GwG § 8).
    /// </summary>
    utility::datetime getKycDate() const;
    bool kycDateIsSet() const;
    void unsetKycDate();
    void setKycDate(const utility::datetime& value);

    /// <summary>
    /// Freitext-Notizen.
    /// </summary>
    utility::string_t getNotes() const;
    bool notesIsSet() const;
    void unsetNotes();
    void setNotes(const utility::string_t& value);

    /// <summary>
    /// Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre).
    /// </summary>
    utility::datetime getRetentionUntil() const;
    bool retentionUntilIsSet() const;
    void unsetRetentionUntil();
    void setRetentionUntil(const utility::datetime& value);

    /// <summary>
    /// Risikoeinschätzung (z. B. Risikoklasse).
    /// </summary>
    utility::string_t getRiskAssessment() const;
    bool riskAssessmentIsSet() const;
    void unsetRiskAssessment();
    void setRiskAssessment(const utility::string_t& value);


protected:
    utility::string_t m_CustomerId;
    bool m_CustomerIdIsSet;

    utility::string_t m_CustomerName;
    bool m_CustomerNameIsSet;

    utility::datetime m_KycDate;
    bool m_KycDateIsSet;

    boost::optional<utility::string_t> m_Notes;

    utility::datetime m_RetentionUntil;
    bool m_RetentionUntilIsSet;

    boost::optional<utility::string_t> m_RiskAssessment;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_KycRecord_H_ */
