/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LegalDocType.h
 *
 * Legal document type (matches &#x60;DOC_TYPES&#x60; in legal_defaults.rs).
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_LegalDocType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_LegalDocType_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  LegalDocType
    : public ModelBase
{
public:
    LegalDocType();
    LegalDocType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~LegalDocType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eLegalDocType
    {
        IMPRINT,
        PRIVACY,
        TERMS,
        WITHDRAWAL,
        REFUND,
        SHIPPING,
        GPSR,
        COOKIE_NOTICE,
    };

    eLegalDocType getValue() const;
    void setValue(eLegalDocType const value);

    protected:
        eLegalDocType m_value;
        std::map<eLegalDocType,utility::string_t> enumToStrMap = {
        { eLegalDocType::IMPRINT, _XPLATSTR("IMPRINT") },
        { eLegalDocType::PRIVACY, _XPLATSTR("PRIVACY") },
        { eLegalDocType::TERMS, _XPLATSTR("TERMS") },
        { eLegalDocType::WITHDRAWAL, _XPLATSTR("WITHDRAWAL") },
        { eLegalDocType::REFUND, _XPLATSTR("REFUND") },
        { eLegalDocType::SHIPPING, _XPLATSTR("SHIPPING") },
        { eLegalDocType::GPSR, _XPLATSTR("GPSR") },
        { eLegalDocType::COOKIE_NOTICE, _XPLATSTR("COOKIE_NOTICE") }
};
        std::map<utility::string_t,eLegalDocType> strToEnumMap = {
        { _XPLATSTR("IMPRINT"), eLegalDocType::IMPRINT },
        { _XPLATSTR("PRIVACY"), eLegalDocType::PRIVACY },
        { _XPLATSTR("TERMS"), eLegalDocType::TERMS },
        { _XPLATSTR("WITHDRAWAL"), eLegalDocType::WITHDRAWAL },
        { _XPLATSTR("REFUND"), eLegalDocType::REFUND },
        { _XPLATSTR("SHIPPING"), eLegalDocType::SHIPPING },
        { _XPLATSTR("GPSR"), eLegalDocType::GPSR },
        { _XPLATSTR("COOKIE_NOTICE"), eLegalDocType::COOKIE_NOTICE }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_LegalDocType_H_ */
