/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MovementType.h
 *
 * Stock movement type.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MovementType_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MovementType_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  MovementType
    : public ModelBase
{
public:
    MovementType();
    MovementType(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~MovementType();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eMovementType
    {
        GOODS_RECEIPT,
        GOODS_RECEIPT_REVERSAL,
        TRANSFER_IN,
        TRANSFER_OUT,
        RETURN_RESTOCK,
        PRODUCTION_CONSUMPTION,
        PRODUCTION_COMPLETION,
        INVENTORY_ADJUSTMENT,
        SALE,
        OTHER,
    };

    eMovementType getValue() const;
    void setValue(eMovementType const value);

    protected:
        eMovementType m_value;
        std::map<eMovementType,utility::string_t> enumToStrMap = {
        { eMovementType::GOODS_RECEIPT, _XPLATSTR("GOODS_RECEIPT") },
        { eMovementType::GOODS_RECEIPT_REVERSAL, _XPLATSTR("GOODS_RECEIPT_REVERSAL") },
        { eMovementType::TRANSFER_IN, _XPLATSTR("TRANSFER_IN") },
        { eMovementType::TRANSFER_OUT, _XPLATSTR("TRANSFER_OUT") },
        { eMovementType::RETURN_RESTOCK, _XPLATSTR("RETURN_RESTOCK") },
        { eMovementType::PRODUCTION_CONSUMPTION, _XPLATSTR("PRODUCTION_CONSUMPTION") },
        { eMovementType::PRODUCTION_COMPLETION, _XPLATSTR("PRODUCTION_COMPLETION") },
        { eMovementType::INVENTORY_ADJUSTMENT, _XPLATSTR("INVENTORY_ADJUSTMENT") },
        { eMovementType::SALE, _XPLATSTR("SALE") },
        { eMovementType::OTHER, _XPLATSTR("OTHER") }
};
        std::map<utility::string_t,eMovementType> strToEnumMap = {
        { _XPLATSTR("GOODS_RECEIPT"), eMovementType::GOODS_RECEIPT },
        { _XPLATSTR("GOODS_RECEIPT_REVERSAL"), eMovementType::GOODS_RECEIPT_REVERSAL },
        { _XPLATSTR("TRANSFER_IN"), eMovementType::TRANSFER_IN },
        { _XPLATSTR("TRANSFER_OUT"), eMovementType::TRANSFER_OUT },
        { _XPLATSTR("RETURN_RESTOCK"), eMovementType::RETURN_RESTOCK },
        { _XPLATSTR("PRODUCTION_CONSUMPTION"), eMovementType::PRODUCTION_CONSUMPTION },
        { _XPLATSTR("PRODUCTION_COMPLETION"), eMovementType::PRODUCTION_COMPLETION },
        { _XPLATSTR("INVENTORY_ADJUSTMENT"), eMovementType::INVENTORY_ADJUSTMENT },
        { _XPLATSTR("SALE"), eMovementType::SALE },
        { _XPLATSTR("OTHER"), eMovementType::OTHER }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MovementType_H_ */
