/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ReturnOrder.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ReturnOrder_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ReturnOrder_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/ReturnOrderStatus.h"
#include <cpprest/details/basic_types.h>
#include "CppRestOpenAPIClient/AnyType.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  ReturnOrder
    : public ModelBase
{
public:
    ReturnOrder();
    virtual ~ReturnOrder();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ReturnOrder members


    /// <summary>
    /// References the contact entity.
    /// </summary>
    utility::string_t getCustomerContactId() const;
    bool customerContactIdIsSet() const;
    void unsetCustomerContactId();
    void setCustomerContactId(const utility::string_t& value);

    utility::string_t getCustomerName() const;
    bool customerNameIsSet() const;
    void unsetCustomerName();
    void setCustomerName(const utility::string_t& value);

    /// <summary>
    /// JSON array of &#x60;{product_id, name, quantity, condition, restock, batch_number?}&#x60;.
    /// </summary>
    std::shared_ptr<AnyType> getLineItems() const;
    bool lineItemsIsSet() const;
    void unsetLineItems();
    void setLineItems(const std::shared_ptr<AnyType>& value);

    utility::string_t getNotes() const;
    bool notesIsSet() const;
    void unsetNotes();
    void setNotes(const utility::string_t& value);

    /// <summary>
    /// References the order entity.
    /// </summary>
    utility::string_t getOrderId() const;
    bool orderIdIsSet() const;
    void unsetOrderId();
    void setOrderId(const utility::string_t& value);

    utility::string_t getOrderNumber() const;
    bool orderNumberIsSet() const;
    void unsetOrderNumber();
    void setOrderNumber(const utility::string_t& value);

    utility::string_t getReturnNumber() const;
    bool returnNumberIsSet() const;
    void unsetReturnNumber();
    void setReturnNumber(const utility::string_t& value);

    utility::string_t getReturnReason() const;
    bool returnReasonIsSet() const;
    void unsetReturnReason();
    void setReturnReason(const utility::string_t& value);

    /// <summary>
    /// One of: requested | received | inspected | restocked | closed
    /// </summary>
    std::shared_ptr<ReturnOrderStatus> getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const std::shared_ptr<ReturnOrderStatus>& value);

    /// <summary>
    /// Warehouse into which restockable items are returned. References the warehouse entity.
    /// </summary>
    utility::string_t getWarehouseId() const;
    bool warehouseIdIsSet() const;
    void unsetWarehouseId();
    void setWarehouseId(const utility::string_t& value);


protected:
    boost::optional<utility::string_t> m_CustomerContactId;

    boost::optional<utility::string_t> m_CustomerName;

    boost::optional<std::shared_ptr<AnyType>> m_LineItems;

    boost::optional<utility::string_t> m_Notes;

    boost::optional<utility::string_t> m_OrderId;

    boost::optional<utility::string_t> m_OrderNumber;

    utility::string_t m_ReturnNumber;
    bool m_ReturnNumberIsSet;

    boost::optional<utility::string_t> m_ReturnReason;

    std::shared_ptr<ReturnOrderStatus> m_Status;
    bool m_StatusIsSet;

    boost::optional<utility::string_t> m_WarehouseId;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ReturnOrder_H_ */
