/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ServiceAssignmentStatus.h
 *
 * Service assignment status.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceAssignmentStatus_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceAssignmentStatus_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ServiceAssignmentStatus
    : public ModelBase
{
public:
    ServiceAssignmentStatus();
    ServiceAssignmentStatus(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~ServiceAssignmentStatus();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eServiceAssignmentStatus
    {
        PLANNED,
        CONFIRMED,
        EN_ROUTE,
        IN_PROGRESS,
        COMPLETED,
        CANCELLED,
    };

    eServiceAssignmentStatus getValue() const;
    void setValue(eServiceAssignmentStatus const value);

    protected:
        eServiceAssignmentStatus m_value;
        std::map<eServiceAssignmentStatus,utility::string_t> enumToStrMap = {
        { eServiceAssignmentStatus::PLANNED, _XPLATSTR("PLANNED") },
        { eServiceAssignmentStatus::CONFIRMED, _XPLATSTR("CONFIRMED") },
        { eServiceAssignmentStatus::EN_ROUTE, _XPLATSTR("EN_ROUTE") },
        { eServiceAssignmentStatus::IN_PROGRESS, _XPLATSTR("IN_PROGRESS") },
        { eServiceAssignmentStatus::COMPLETED, _XPLATSTR("COMPLETED") },
        { eServiceAssignmentStatus::CANCELLED, _XPLATSTR("CANCELLED") }
};
        std::map<utility::string_t,eServiceAssignmentStatus> strToEnumMap = {
        { _XPLATSTR("PLANNED"), eServiceAssignmentStatus::PLANNED },
        { _XPLATSTR("CONFIRMED"), eServiceAssignmentStatus::CONFIRMED },
        { _XPLATSTR("EN_ROUTE"), eServiceAssignmentStatus::EN_ROUTE },
        { _XPLATSTR("IN_PROGRESS"), eServiceAssignmentStatus::IN_PROGRESS },
        { _XPLATSTR("COMPLETED"), eServiceAssignmentStatus::COMPLETED },
        { _XPLATSTR("CANCELLED"), eServiceAssignmentStatus::CANCELLED }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ServiceAssignmentStatus_H_ */
