/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SyncStatus.h
 *
 * Marketplace sync status.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_SyncStatus_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_SyncStatus_H_

#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  SyncStatus
    : public ModelBase
{
public:
    SyncStatus();
    SyncStatus(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~SyncStatus();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eSyncStatus
    {
        PENDING,
        CONNECTED,
        SUCCESS,
        ERROR,
    };

    eSyncStatus getValue() const;
    void setValue(eSyncStatus const value);

    protected:
        eSyncStatus m_value;
        std::map<eSyncStatus,utility::string_t> enumToStrMap = {
        { eSyncStatus::PENDING, _XPLATSTR("PENDING") },
        { eSyncStatus::CONNECTED, _XPLATSTR("CONNECTED") },
        { eSyncStatus::SUCCESS, _XPLATSTR("SUCCESS") },
        { eSyncStatus::ERROR, _XPLATSTR("ERROR") }
};
        std::map<utility::string_t,eSyncStatus> strToEnumMap = {
        { _XPLATSTR("PENDING"), eSyncStatus::PENDING },
        { _XPLATSTR("CONNECTED"), eSyncStatus::CONNECTED },
        { _XPLATSTR("SUCCESS"), eSyncStatus::SUCCESS },
        { _XPLATSTR("ERROR"), eSyncStatus::ERROR }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_SyncStatus_H_ */
