/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UpdateTenantSettings.h
 *
 * Request payload for updating tenant settings.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateTenantSettings_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateTenantSettings_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/CompanyType.h"
#include "CppRestOpenAPIClient/model/PartialFeatureSettings.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class PartialFeatureSettings;


/// <summary>
/// Request payload for updating tenant settings.
/// </summary>
class  UpdateTenantSettings
    : public ModelBase
{
public:
    UpdateTenantSettings();
    virtual ~UpdateTenantSettings();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// UpdateTenantSettings members


    std::shared_ptr<CompanyType> getCompanyType() const;
    bool companyTypeIsSet() const;
    void unsetCompanyType();
    void setCompanyType(const std::shared_ptr<CompanyType>& value);

    std::shared_ptr<PartialFeatureSettings> getFeatures() const;
    bool featuresIsSet() const;
    void unsetFeatures();
    void setFeatures(const std::shared_ptr<PartialFeatureSettings>& value);


protected:
    std::shared_ptr<CompanyType> m_CompanyType;
    bool m_CompanyTypeIsSet;

    boost::optional<std::shared_ptr<PartialFeatureSettings>> m_Features;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UpdateTenantSettings_H_ */
