/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/AllocatePaymentRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AllocatePaymentRequest::AllocatePaymentRequest()
{
    m_Amount = 0.0;
    m_AmountIsSet = false;
    m_Invoice_id = utility::conversions::to_string_t("");
    m_Invoice_idIsSet = false;
    m_Payment_id = utility::conversions::to_string_t("");
    m_Payment_idIsSet = false;
}

AllocatePaymentRequest::~AllocatePaymentRequest()
{
}

void AllocatePaymentRequest::validate()
{
    // TODO: implement validation
}

web::json::value AllocatePaymentRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AmountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("amount"))] = ModelBase::toJson(m_Amount);
    }
    if(m_Invoice_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("invoice_id"))] = ModelBase::toJson(m_Invoice_id);
    }
    if(m_Payment_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("payment_id"))] = ModelBase::toJson(m_Payment_id);
    }

    return val;
}

bool AllocatePaymentRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("amount")));
        if(!fieldValue.is_null())
        {
            double refVal_setAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmount);
            setAmount(refVal_setAmount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("invoice_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInvoiceId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInvoiceId);
            setInvoiceId(refVal_setInvoiceId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("payment_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("payment_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPaymentId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaymentId);
            setPaymentId(refVal_setPaymentId);
            
        }
    }
    return ok;
}

void AllocatePaymentRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("amount")), m_Amount));
    }
    if(m_Invoice_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("invoice_id")), m_Invoice_id));
    }
    if(m_Payment_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("payment_id")), m_Payment_id));
    }
}

bool AllocatePaymentRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("amount"))))
    {
        double refVal_setAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("amount"))), refVal_setAmount );
        setAmount(refVal_setAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))))
    {
        utility::string_t refVal_setInvoiceId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("invoice_id"))), refVal_setInvoiceId );
        setInvoiceId(refVal_setInvoiceId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("payment_id"))))
    {
        utility::string_t refVal_setPaymentId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("payment_id"))), refVal_setPaymentId );
        setPaymentId(refVal_setPaymentId);
    }
    return ok;
}


double AllocatePaymentRequest::getAmount() const
{
    return m_Amount;
}

void AllocatePaymentRequest::setAmount(double value)
{
    m_Amount = value;
    m_AmountIsSet = true;
}

bool AllocatePaymentRequest::amountIsSet() const
{
    return m_AmountIsSet;
}

void AllocatePaymentRequest::unsetAmount()
{
    m_AmountIsSet = false;
}
utility::string_t AllocatePaymentRequest::getInvoiceId() const
{
    return m_Invoice_id;
}


void AllocatePaymentRequest::setInvoiceId(const utility::string_t& value)
{
    m_Invoice_id = value;
    m_Invoice_idIsSet = true;
}

bool AllocatePaymentRequest::invoiceIdIsSet() const
{
    return m_Invoice_idIsSet;
}

void AllocatePaymentRequest::unsetInvoice_id()
{
    m_Invoice_idIsSet = false;
}
utility::string_t AllocatePaymentRequest::getPaymentId() const
{
    return m_Payment_id;
}


void AllocatePaymentRequest::setPaymentId(const utility::string_t& value)
{
    m_Payment_id = value;
    m_Payment_idIsSet = true;
}

bool AllocatePaymentRequest::paymentIdIsSet() const
{
    return m_Payment_idIsSet;
}

void AllocatePaymentRequest::unsetPayment_id()
{
    m_Payment_idIsSet = false;
}

}
}
}
}


