/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ApiResponse_GdprExport_data.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ApiResponse_GdprExport_data::ApiResponse_GdprExport_data()
{
    m_ActivityLogIsSet = false;
    m_ApiKeysIsSet = false;
    m_BillingIsSet = false;
    m_ExportedAt = utility::datetime();
    m_ExportedAtIsSet = false;
    m_GeneratedByAi = false;
    m_GeneratedByAiIsSet = false;
    m_NotificationsIsSet = false;
    m_RefreshTokensIsSet = false;
    m_TenantsIsSet = false;
    m_UsageEventsIsSet = false;
    m_UserIsSet = false;
}

ApiResponse_GdprExport_data::~ApiResponse_GdprExport_data()
{
}

void ApiResponse_GdprExport_data::validate()
{
    // TODO: implement validation
}

web::json::value ApiResponse_GdprExport_data::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ActivityLogIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("activityLog"))] = ModelBase::toJson(m_ActivityLog);
    }
    if(m_ApiKeysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("apiKeys"))] = ModelBase::toJson(m_ApiKeys);
    }
    if(m_BillingIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("billing"))] = ModelBase::toJson(m_Billing);
    }
    if(m_ExportedAtIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("exportedAt"))] = ModelBase::toJson(m_ExportedAt);
    }
    if(m_GeneratedByAiIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("generatedByAi"))] = ModelBase::toJson(m_GeneratedByAi);
    }
    if(m_NotificationsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("notifications"))] = ModelBase::toJson(m_Notifications);
    }
    if(m_RefreshTokensIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("refreshTokens"))] = ModelBase::toJson(m_RefreshTokens);
    }
    if(m_TenantsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenants"))] = ModelBase::toJson(m_Tenants);
    }
    if(m_UsageEventsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("usageEvents"))] = ModelBase::toJson(m_UsageEvents);
    }
    if(m_UserIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("user"))] = ModelBase::toJson(m_User);
    }

    return val;
}

bool ApiResponse_GdprExport_data::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("activityLog"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("activityLog")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprActivity>> refVal_setActivityLog;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActivityLog);
            setActivityLog(refVal_setActivityLog);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("apiKeys"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("apiKeys")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprApiKey>> refVal_setApiKeys;
            ok &= ModelBase::fromJson(fieldValue, refVal_setApiKeys);
            setApiKeys(refVal_setApiKeys);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("billing"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("billing")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprBillingInfo>> refVal_setBilling;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBilling);
            setBilling(refVal_setBilling);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("exportedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("exportedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setExportedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setExportedAt);
            setExportedAt(refVal_setExportedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("generatedByAi"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("generatedByAi")));
        if(!fieldValue.is_null())
        {
            bool refVal_setGeneratedByAi;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGeneratedByAi);
            setGeneratedByAi(refVal_setGeneratedByAi);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("notifications"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("notifications")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprNotification>> refVal_setNotifications;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotifications);
            setNotifications(refVal_setNotifications);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("refreshTokens"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("refreshTokens")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprRefreshToken>> refVal_setRefreshTokens;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRefreshTokens);
            setRefreshTokens(refVal_setRefreshTokens);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenants"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenants")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprTenant>> refVal_setTenants;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenants);
            setTenants(refVal_setTenants);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("usageEvents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("usageEvents")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<GdprUsageEvent>> refVal_setUsageEvents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsageEvents);
            setUsageEvents(refVal_setUsageEvents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("user")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<GdprUser> refVal_setUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUser);
            setUser(refVal_setUser);
            
        }
    }
    return ok;
}

void ApiResponse_GdprExport_data::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ActivityLogIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("activityLog")), m_ActivityLog));
    }
    if(m_ApiKeysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("apiKeys")), m_ApiKeys));
    }
    if(m_BillingIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("billing")), m_Billing));
    }
    if(m_ExportedAtIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("exportedAt")), m_ExportedAt));
    }
    if(m_GeneratedByAiIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("generatedByAi")), m_GeneratedByAi));
    }
    if(m_NotificationsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("notifications")), m_Notifications));
    }
    if(m_RefreshTokensIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("refreshTokens")), m_RefreshTokens));
    }
    if(m_TenantsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenants")), m_Tenants));
    }
    if(m_UsageEventsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("usageEvents")), m_UsageEvents));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("user")), m_User));
    }
}

bool ApiResponse_GdprExport_data::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("activityLog"))))
    {
        std::vector<std::shared_ptr<GdprActivity>> refVal_setActivityLog;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("activityLog"))), refVal_setActivityLog );
        setActivityLog(refVal_setActivityLog);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("apiKeys"))))
    {
        std::vector<std::shared_ptr<GdprApiKey>> refVal_setApiKeys;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("apiKeys"))), refVal_setApiKeys );
        setApiKeys(refVal_setApiKeys);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("billing"))))
    {
        std::vector<std::shared_ptr<GdprBillingInfo>> refVal_setBilling;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("billing"))), refVal_setBilling );
        setBilling(refVal_setBilling);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("exportedAt"))))
    {
        utility::datetime refVal_setExportedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("exportedAt"))), refVal_setExportedAt );
        setExportedAt(refVal_setExportedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("generatedByAi"))))
    {
        bool refVal_setGeneratedByAi;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("generatedByAi"))), refVal_setGeneratedByAi );
        setGeneratedByAi(refVal_setGeneratedByAi);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("notifications"))))
    {
        std::vector<std::shared_ptr<GdprNotification>> refVal_setNotifications;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("notifications"))), refVal_setNotifications );
        setNotifications(refVal_setNotifications);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("refreshTokens"))))
    {
        std::vector<std::shared_ptr<GdprRefreshToken>> refVal_setRefreshTokens;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("refreshTokens"))), refVal_setRefreshTokens );
        setRefreshTokens(refVal_setRefreshTokens);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenants"))))
    {
        std::vector<std::shared_ptr<GdprTenant>> refVal_setTenants;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenants"))), refVal_setTenants );
        setTenants(refVal_setTenants);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("usageEvents"))))
    {
        std::vector<std::shared_ptr<GdprUsageEvent>> refVal_setUsageEvents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("usageEvents"))), refVal_setUsageEvents );
        setUsageEvents(refVal_setUsageEvents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("user"))))
    {
        std::shared_ptr<GdprUser> refVal_setUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("user"))), refVal_setUser );
        setUser(refVal_setUser);
    }
    return ok;
}


std::vector<std::shared_ptr<GdprActivity>> ApiResponse_GdprExport_data::getActivityLog() const
{
    return m_ActivityLog;
}


void ApiResponse_GdprExport_data::setActivityLog(const std::vector<std::shared_ptr<GdprActivity>>& value)
{
    m_ActivityLog = value;
    m_ActivityLogIsSet = true;
}

bool ApiResponse_GdprExport_data::activityLogIsSet() const
{
    return m_ActivityLogIsSet;
}

void ApiResponse_GdprExport_data::unsetActivityLog()
{
    m_ActivityLogIsSet = false;
}
std::vector<std::shared_ptr<GdprApiKey>> ApiResponse_GdprExport_data::getApiKeys() const
{
    return m_ApiKeys;
}


void ApiResponse_GdprExport_data::setApiKeys(const std::vector<std::shared_ptr<GdprApiKey>>& value)
{
    m_ApiKeys = value;
    m_ApiKeysIsSet = true;
}

bool ApiResponse_GdprExport_data::apiKeysIsSet() const
{
    return m_ApiKeysIsSet;
}

void ApiResponse_GdprExport_data::unsetApiKeys()
{
    m_ApiKeysIsSet = false;
}
std::vector<std::shared_ptr<GdprBillingInfo>> ApiResponse_GdprExport_data::getBilling() const
{
    return m_Billing;
}


void ApiResponse_GdprExport_data::setBilling(const std::vector<std::shared_ptr<GdprBillingInfo>>& value)
{
    m_Billing = value;
    m_BillingIsSet = true;
}

bool ApiResponse_GdprExport_data::billingIsSet() const
{
    return m_BillingIsSet;
}

void ApiResponse_GdprExport_data::unsetBilling()
{
    m_BillingIsSet = false;
}
utility::datetime ApiResponse_GdprExport_data::getExportedAt() const
{
    return m_ExportedAt;
}


void ApiResponse_GdprExport_data::setExportedAt(const utility::datetime& value)
{
    m_ExportedAt = value;
    m_ExportedAtIsSet = true;
}

bool ApiResponse_GdprExport_data::exportedAtIsSet() const
{
    return m_ExportedAtIsSet;
}

void ApiResponse_GdprExport_data::unsetExportedAt()
{
    m_ExportedAtIsSet = false;
}
bool ApiResponse_GdprExport_data::isGeneratedByAi() const
{
    return m_GeneratedByAi;
}

void ApiResponse_GdprExport_data::setGeneratedByAi(bool value)
{
    m_GeneratedByAi = value;
    m_GeneratedByAiIsSet = true;
}

bool ApiResponse_GdprExport_data::generatedByAiIsSet() const
{
    return m_GeneratedByAiIsSet;
}

void ApiResponse_GdprExport_data::unsetGeneratedByAi()
{
    m_GeneratedByAiIsSet = false;
}
std::vector<std::shared_ptr<GdprNotification>> ApiResponse_GdprExport_data::getNotifications() const
{
    return m_Notifications;
}


void ApiResponse_GdprExport_data::setNotifications(const std::vector<std::shared_ptr<GdprNotification>>& value)
{
    m_Notifications = value;
    m_NotificationsIsSet = true;
}

bool ApiResponse_GdprExport_data::notificationsIsSet() const
{
    return m_NotificationsIsSet;
}

void ApiResponse_GdprExport_data::unsetNotifications()
{
    m_NotificationsIsSet = false;
}
std::vector<std::shared_ptr<GdprRefreshToken>> ApiResponse_GdprExport_data::getRefreshTokens() const
{
    return m_RefreshTokens;
}


void ApiResponse_GdprExport_data::setRefreshTokens(const std::vector<std::shared_ptr<GdprRefreshToken>>& value)
{
    m_RefreshTokens = value;
    m_RefreshTokensIsSet = true;
}

bool ApiResponse_GdprExport_data::refreshTokensIsSet() const
{
    return m_RefreshTokensIsSet;
}

void ApiResponse_GdprExport_data::unsetRefreshTokens()
{
    m_RefreshTokensIsSet = false;
}
std::vector<std::shared_ptr<GdprTenant>> ApiResponse_GdprExport_data::getTenants() const
{
    return m_Tenants;
}


void ApiResponse_GdprExport_data::setTenants(const std::vector<std::shared_ptr<GdprTenant>>& value)
{
    m_Tenants = value;
    m_TenantsIsSet = true;
}

bool ApiResponse_GdprExport_data::tenantsIsSet() const
{
    return m_TenantsIsSet;
}

void ApiResponse_GdprExport_data::unsetTenants()
{
    m_TenantsIsSet = false;
}
std::vector<std::shared_ptr<GdprUsageEvent>> ApiResponse_GdprExport_data::getUsageEvents() const
{
    return m_UsageEvents;
}


void ApiResponse_GdprExport_data::setUsageEvents(const std::vector<std::shared_ptr<GdprUsageEvent>>& value)
{
    m_UsageEvents = value;
    m_UsageEventsIsSet = true;
}

bool ApiResponse_GdprExport_data::usageEventsIsSet() const
{
    return m_UsageEventsIsSet;
}

void ApiResponse_GdprExport_data::unsetUsageEvents()
{
    m_UsageEventsIsSet = false;
}
std::shared_ptr<GdprUser> ApiResponse_GdprExport_data::getUser() const
{
    return m_User;
}


void ApiResponse_GdprExport_data::setUser(const std::shared_ptr<GdprUser>& value)
{
    m_User = value;
    m_UserIsSet = true;
}

bool ApiResponse_GdprExport_data::userIsSet() const
{
    return m_UserIsSet;
}

void ApiResponse_GdprExport_data::unsetUser()
{
    m_UserIsSet = false;
}

}
}
}
}


