/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ApiResponse_Vec_UserTenantInfo_data_inner.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ApiResponse_Vec_UserTenantInfo_data_inner::ApiResponse_Vec_UserTenantInfo_data_inner()
{
    m_Role = utility::conversions::to_string_t("");
    m_RoleIsSet = false;
    m_Tenant_id = utility::conversions::to_string_t("");
    m_Tenant_idIsSet = false;
    m_Tenant_name = utility::conversions::to_string_t("");
    m_Tenant_nameIsSet = false;
}

ApiResponse_Vec_UserTenantInfo_data_inner::~ApiResponse_Vec_UserTenantInfo_data_inner()
{
}

void ApiResponse_Vec_UserTenantInfo_data_inner::validate()
{
    // TODO: implement validation
}

web::json::value ApiResponse_Vec_UserTenantInfo_data_inner::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Custom_domain.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("custom_domain"))] = ModelBase::toJson(m_Custom_domain.get());
    }
    if(m_RoleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("role"))] = ModelBase::toJson(m_Role);
    }
    if(m_Subdomain.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subdomain"))] = ModelBase::toJson(m_Subdomain.get());
    }
    if(m_Tenant_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenant_id"))] = ModelBase::toJson(m_Tenant_id);
    }
    if(m_Tenant_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tenant_name"))] = ModelBase::toJson(m_Tenant_name);
    }

    return val;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("custom_domain"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("custom_domain")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCustomDomain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomDomain);
            setCustomDomain(refVal_setCustomDomain);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("role")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRole;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRole);
            setRole(refVal_setRole);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subdomain"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subdomain")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubdomain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubdomain);
            setSubdomain(refVal_setSubdomain);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenant_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenant_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantId);
            setTenantId(refVal_setTenantId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tenant_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tenant_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTenantName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTenantName);
            setTenantName(refVal_setTenantName);
            
        }
    }
    return ok;
}

void ApiResponse_Vec_UserTenantInfo_data_inner::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Custom_domain.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("custom_domain")), m_Custom_domain.get()));
    }
    if(m_RoleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("role")), m_Role));
    }
    if(m_Subdomain.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subdomain")), m_Subdomain.get()));
    }
    if(m_Tenant_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenant_id")), m_Tenant_id));
    }
    if(m_Tenant_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tenant_name")), m_Tenant_name));
    }
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("custom_domain"))))
    {
        utility::string_t refVal_setCustomDomain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("custom_domain"))), refVal_setCustomDomain );
        setCustomDomain(refVal_setCustomDomain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("role"))))
    {
        utility::string_t refVal_setRole;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("role"))), refVal_setRole );
        setRole(refVal_setRole);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subdomain"))))
    {
        utility::string_t refVal_setSubdomain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subdomain"))), refVal_setSubdomain );
        setSubdomain(refVal_setSubdomain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenant_id"))))
    {
        utility::string_t refVal_setTenantId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenant_id"))), refVal_setTenantId );
        setTenantId(refVal_setTenantId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tenant_name"))))
    {
        utility::string_t refVal_setTenantName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tenant_name"))), refVal_setTenantName );
        setTenantName(refVal_setTenantName);
    }
    return ok;
}


utility::string_t ApiResponse_Vec_UserTenantInfo_data_inner::getCustomDomain() const
{
    return m_Custom_domain.get();
}


void ApiResponse_Vec_UserTenantInfo_data_inner::setCustomDomain(const utility::string_t& value)
{
    m_Custom_domain = value;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::customDomainIsSet() const
{
    return m_Custom_domain.has_value();
}

void ApiResponse_Vec_UserTenantInfo_data_inner::unsetCustom_domain()
{
    m_Custom_domain.reset();
}
utility::string_t ApiResponse_Vec_UserTenantInfo_data_inner::getRole() const
{
    return m_Role;
}


void ApiResponse_Vec_UserTenantInfo_data_inner::setRole(const utility::string_t& value)
{
    m_Role = value;
    m_RoleIsSet = true;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::roleIsSet() const
{
    return m_RoleIsSet;
}

void ApiResponse_Vec_UserTenantInfo_data_inner::unsetRole()
{
    m_RoleIsSet = false;
}
utility::string_t ApiResponse_Vec_UserTenantInfo_data_inner::getSubdomain() const
{
    return m_Subdomain.get();
}


void ApiResponse_Vec_UserTenantInfo_data_inner::setSubdomain(const utility::string_t& value)
{
    m_Subdomain = value;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::subdomainIsSet() const
{
    return m_Subdomain.has_value();
}

void ApiResponse_Vec_UserTenantInfo_data_inner::unsetSubdomain()
{
    m_Subdomain.reset();
}
utility::string_t ApiResponse_Vec_UserTenantInfo_data_inner::getTenantId() const
{
    return m_Tenant_id;
}


void ApiResponse_Vec_UserTenantInfo_data_inner::setTenantId(const utility::string_t& value)
{
    m_Tenant_id = value;
    m_Tenant_idIsSet = true;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::tenantIdIsSet() const
{
    return m_Tenant_idIsSet;
}

void ApiResponse_Vec_UserTenantInfo_data_inner::unsetTenant_id()
{
    m_Tenant_idIsSet = false;
}
utility::string_t ApiResponse_Vec_UserTenantInfo_data_inner::getTenantName() const
{
    return m_Tenant_name;
}


void ApiResponse_Vec_UserTenantInfo_data_inner::setTenantName(const utility::string_t& value)
{
    m_Tenant_name = value;
    m_Tenant_nameIsSet = true;
}

bool ApiResponse_Vec_UserTenantInfo_data_inner::tenantNameIsSet() const
{
    return m_Tenant_nameIsSet;
}

void ApiResponse_Vec_UserTenantInfo_data_inner::unsetTenant_name()
{
    m_Tenant_nameIsSet = false;
}

}
}
}
}


