/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/BalanceSheet.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

BalanceSheet::BalanceSheet()
{
    m_AssetsIsSet = false;
    m_Balanced = false;
    m_BalancedIsSet = false;
    m_Equity_liabilitiesIsSet = false;
    m_Total_assets = utility::conversions::to_string_t("");
    m_Total_assetsIsSet = false;
    m_Total_equity_liabilities = utility::conversions::to_string_t("");
    m_Total_equity_liabilitiesIsSet = false;
}

BalanceSheet::~BalanceSheet()
{
}

void BalanceSheet::validate()
{
    // TODO: implement validation
}

web::json::value BalanceSheet::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AssetsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("assets"))] = ModelBase::toJson(m_Assets);
    }
    if(m_BalancedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("balanced"))] = ModelBase::toJson(m_Balanced);
    }
    if(m_Equity_liabilitiesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("equity_liabilities"))] = ModelBase::toJson(m_Equity_liabilities);
    }
    if(m_Total_assetsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total_assets"))] = ModelBase::toJson(m_Total_assets);
    }
    if(m_Total_equity_liabilitiesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities"))] = ModelBase::toJson(m_Total_equity_liabilities);
    }

    return val;
}

bool BalanceSheet::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("assets"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("assets")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<BalanceItem>> refVal_setAssets;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAssets);
            setAssets(refVal_setAssets);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("balanced"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("balanced")));
        if(!fieldValue.is_null())
        {
            bool refVal_setBalanced;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBalanced);
            setBalanced(refVal_setBalanced);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("equity_liabilities"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("equity_liabilities")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<BalanceItem>> refVal_setEquityLiabilities;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEquityLiabilities);
            setEquityLiabilities(refVal_setEquityLiabilities);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total_assets"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total_assets")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTotalAssets;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalAssets);
            setTotalAssets(refVal_setTotalAssets);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTotalEquityLiabilities;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalEquityLiabilities);
            setTotalEquityLiabilities(refVal_setTotalEquityLiabilities);
            
        }
    }
    return ok;
}

void BalanceSheet::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AssetsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("assets")), m_Assets));
    }
    if(m_BalancedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("balanced")), m_Balanced));
    }
    if(m_Equity_liabilitiesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("equity_liabilities")), m_Equity_liabilities));
    }
    if(m_Total_assetsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total_assets")), m_Total_assets));
    }
    if(m_Total_equity_liabilitiesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities")), m_Total_equity_liabilities));
    }
}

bool BalanceSheet::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("assets"))))
    {
        std::vector<std::shared_ptr<BalanceItem>> refVal_setAssets;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("assets"))), refVal_setAssets );
        setAssets(refVal_setAssets);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("balanced"))))
    {
        bool refVal_setBalanced;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("balanced"))), refVal_setBalanced );
        setBalanced(refVal_setBalanced);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("equity_liabilities"))))
    {
        std::vector<std::shared_ptr<BalanceItem>> refVal_setEquityLiabilities;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("equity_liabilities"))), refVal_setEquityLiabilities );
        setEquityLiabilities(refVal_setEquityLiabilities);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total_assets"))))
    {
        utility::string_t refVal_setTotalAssets;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total_assets"))), refVal_setTotalAssets );
        setTotalAssets(refVal_setTotalAssets);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities"))))
    {
        utility::string_t refVal_setTotalEquityLiabilities;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("total_equity_liabilities"))), refVal_setTotalEquityLiabilities );
        setTotalEquityLiabilities(refVal_setTotalEquityLiabilities);
    }
    return ok;
}


std::vector<std::shared_ptr<BalanceItem>> BalanceSheet::getAssets() const
{
    return m_Assets;
}


void BalanceSheet::setAssets(const std::vector<std::shared_ptr<BalanceItem>>& value)
{
    m_Assets = value;
    m_AssetsIsSet = true;
}

bool BalanceSheet::assetsIsSet() const
{
    return m_AssetsIsSet;
}

void BalanceSheet::unsetAssets()
{
    m_AssetsIsSet = false;
}
bool BalanceSheet::isBalanced() const
{
    return m_Balanced;
}

void BalanceSheet::setBalanced(bool value)
{
    m_Balanced = value;
    m_BalancedIsSet = true;
}

bool BalanceSheet::balancedIsSet() const
{
    return m_BalancedIsSet;
}

void BalanceSheet::unsetBalanced()
{
    m_BalancedIsSet = false;
}
std::vector<std::shared_ptr<BalanceItem>> BalanceSheet::getEquityLiabilities() const
{
    return m_Equity_liabilities;
}


void BalanceSheet::setEquityLiabilities(const std::vector<std::shared_ptr<BalanceItem>>& value)
{
    m_Equity_liabilities = value;
    m_Equity_liabilitiesIsSet = true;
}

bool BalanceSheet::equityLiabilitiesIsSet() const
{
    return m_Equity_liabilitiesIsSet;
}

void BalanceSheet::unsetEquity_liabilities()
{
    m_Equity_liabilitiesIsSet = false;
}
utility::string_t BalanceSheet::getTotalAssets() const
{
    return m_Total_assets;
}


void BalanceSheet::setTotalAssets(const utility::string_t& value)
{
    m_Total_assets = value;
    m_Total_assetsIsSet = true;
}

bool BalanceSheet::totalAssetsIsSet() const
{
    return m_Total_assetsIsSet;
}

void BalanceSheet::unsetTotal_assets()
{
    m_Total_assetsIsSet = false;
}
utility::string_t BalanceSheet::getTotalEquityLiabilities() const
{
    return m_Total_equity_liabilities;
}


void BalanceSheet::setTotalEquityLiabilities(const utility::string_t& value)
{
    m_Total_equity_liabilities = value;
    m_Total_equity_liabilitiesIsSet = true;
}

bool BalanceSheet::totalEquityLiabilitiesIsSet() const
{
    return m_Total_equity_liabilitiesIsSet;
}

void BalanceSheet::unsetTotal_equity_liabilities()
{
    m_Total_equity_liabilitiesIsSet = false;
}

}
}
}
}


