/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/BankLookup.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

BankLookup::BankLookup()
{
    m_Iban = utility::conversions::to_string_t("");
    m_IbanIsSet = false;
    m_Psd2_supported = false;
    m_Psd2_supportedIsSet = false;
}

BankLookup::~BankLookup()
{
}

void BankLookup::validate()
{
    // TODO: implement validation
}

web::json::value BankLookup::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Bank_name.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("bank_name"))] = ModelBase::toJson(m_Bank_name.get());
    }
    if(m_Bic.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("bic"))] = ModelBase::toJson(m_Bic.get());
    }
    if(m_IbanIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("iban"))] = ModelBase::toJson(m_Iban);
    }
    if(m_Nextgenpsd2_url.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url"))] = ModelBase::toJson(m_Nextgenpsd2_url.get());
    }
    if(m_Psd2_supportedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("psd2_supported"))] = ModelBase::toJson(m_Psd2_supported);
    }

    return val;
}

bool BankLookup::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("bank_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("bank_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBankName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBankName);
            setBankName(refVal_setBankName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("bic"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("bic")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBic;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBic);
            setBic(refVal_setBic);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("iban"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("iban")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIban;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIban);
            setIban(refVal_setIban);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNextgenpsd2Url;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNextgenpsd2Url);
            setNextgenpsd2Url(refVal_setNextgenpsd2Url);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("psd2_supported"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("psd2_supported")));
        if(!fieldValue.is_null())
        {
            bool refVal_setPsd2Supported;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPsd2Supported);
            setPsd2Supported(refVal_setPsd2Supported);
            
        }
    }
    return ok;
}

void BankLookup::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Bank_name.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("bank_name")), m_Bank_name.get()));
    }
    if(m_Bic.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("bic")), m_Bic.get()));
    }
    if(m_IbanIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("iban")), m_Iban));
    }
    if(m_Nextgenpsd2_url.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url")), m_Nextgenpsd2_url.get()));
    }
    if(m_Psd2_supportedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("psd2_supported")), m_Psd2_supported));
    }
}

bool BankLookup::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("bank_name"))))
    {
        utility::string_t refVal_setBankName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("bank_name"))), refVal_setBankName );
        setBankName(refVal_setBankName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("bic"))))
    {
        utility::string_t refVal_setBic;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("bic"))), refVal_setBic );
        setBic(refVal_setBic);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("iban"))))
    {
        utility::string_t refVal_setIban;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("iban"))), refVal_setIban );
        setIban(refVal_setIban);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url"))))
    {
        utility::string_t refVal_setNextgenpsd2Url;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("nextgenpsd2_url"))), refVal_setNextgenpsd2Url );
        setNextgenpsd2Url(refVal_setNextgenpsd2Url);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("psd2_supported"))))
    {
        bool refVal_setPsd2Supported;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("psd2_supported"))), refVal_setPsd2Supported );
        setPsd2Supported(refVal_setPsd2Supported);
    }
    return ok;
}


utility::string_t BankLookup::getBankName() const
{
    return m_Bank_name.get();
}


void BankLookup::setBankName(const utility::string_t& value)
{
    m_Bank_name = value;
}

bool BankLookup::bankNameIsSet() const
{
    return m_Bank_name.has_value();
}

void BankLookup::unsetBank_name()
{
    m_Bank_name.reset();
}
utility::string_t BankLookup::getBic() const
{
    return m_Bic.get();
}


void BankLookup::setBic(const utility::string_t& value)
{
    m_Bic = value;
}

bool BankLookup::bicIsSet() const
{
    return m_Bic.has_value();
}

void BankLookup::unsetBic()
{
    m_Bic.reset();
}
utility::string_t BankLookup::getIban() const
{
    return m_Iban;
}


void BankLookup::setIban(const utility::string_t& value)
{
    m_Iban = value;
    m_IbanIsSet = true;
}

bool BankLookup::ibanIsSet() const
{
    return m_IbanIsSet;
}

void BankLookup::unsetIban()
{
    m_IbanIsSet = false;
}
utility::string_t BankLookup::getNextgenpsd2Url() const
{
    return m_Nextgenpsd2_url.get();
}


void BankLookup::setNextgenpsd2Url(const utility::string_t& value)
{
    m_Nextgenpsd2_url = value;
}

bool BankLookup::nextgenpsd2UrlIsSet() const
{
    return m_Nextgenpsd2_url.has_value();
}

void BankLookup::unsetNextgenpsd2_url()
{
    m_Nextgenpsd2_url.reset();
}
bool BankLookup::isPsd2Supported() const
{
    return m_Psd2_supported;
}

void BankLookup::setPsd2Supported(bool value)
{
    m_Psd2_supported = value;
    m_Psd2_supportedIsSet = true;
}

bool BankLookup::psd2SupportedIsSet() const
{
    return m_Psd2_supportedIsSet;
}

void BankLookup::unsetPsd2_supported()
{
    m_Psd2_supportedIsSet = false;
}

}
}
}
}


