/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Budget.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Budget::Budget()
{
    m_Category = utility::conversions::to_string_t("");
    m_CategoryIsSet = false;
    m_MonthlyGoal = utility::conversions::to_string_t("");
    m_MonthlyGoalIsSet = false;
    m_Year = 0;
    m_YearIsSet = false;
}

Budget::~Budget()
{
}

void Budget::validate()
{
    // TODO: implement validation
}

web::json::value Budget::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CategoryIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("category"))] = ModelBase::toJson(m_Category);
    }
    if(m_MonthlyGoalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("monthlyGoal"))] = ModelBase::toJson(m_MonthlyGoal);
    }
    if(m_UpdatedAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt.get());
    }
    if(m_YearIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("year"))] = ModelBase::toJson(m_Year);
    }

    return val;
}

bool Budget::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("category"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("category")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCategory;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategory);
            setCategory(refVal_setCategory);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("monthlyGoal"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("monthlyGoal")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMonthlyGoal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMonthlyGoal);
            setMonthlyGoal(refVal_setMonthlyGoal);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("year")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setYear;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYear);
            setYear(refVal_setYear);
            
        }
    }
    return ok;
}

void Budget::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CategoryIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("category")), m_Category));
    }
    if(m_MonthlyGoalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("monthlyGoal")), m_MonthlyGoal));
    }
    if(m_UpdatedAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt.get()));
    }
    if(m_YearIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("year")), m_Year));
    }
}

bool Budget::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("category"))))
    {
        utility::string_t refVal_setCategory;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("category"))), refVal_setCategory );
        setCategory(refVal_setCategory);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("monthlyGoal"))))
    {
        utility::string_t refVal_setMonthlyGoal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("monthlyGoal"))), refVal_setMonthlyGoal );
        setMonthlyGoal(refVal_setMonthlyGoal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        int32_t refVal_setYear;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("year"))), refVal_setYear );
        setYear(refVal_setYear);
    }
    return ok;
}


utility::string_t Budget::getCategory() const
{
    return m_Category;
}


void Budget::setCategory(const utility::string_t& value)
{
    m_Category = value;
    m_CategoryIsSet = true;
}

bool Budget::categoryIsSet() const
{
    return m_CategoryIsSet;
}

void Budget::unsetCategory()
{
    m_CategoryIsSet = false;
}
utility::string_t Budget::getMonthlyGoal() const
{
    return m_MonthlyGoal;
}


void Budget::setMonthlyGoal(const utility::string_t& value)
{
    m_MonthlyGoal = value;
    m_MonthlyGoalIsSet = true;
}

bool Budget::monthlyGoalIsSet() const
{
    return m_MonthlyGoalIsSet;
}

void Budget::unsetMonthlyGoal()
{
    m_MonthlyGoalIsSet = false;
}
utility::datetime Budget::getUpdatedAt() const
{
    return m_UpdatedAt.get();
}


void Budget::setUpdatedAt(const utility::datetime& value)
{
    m_UpdatedAt = value;
}

bool Budget::updatedAtIsSet() const
{
    return m_UpdatedAt.has_value();
}

void Budget::unsetUpdatedAt()
{
    m_UpdatedAt.reset();
}
int32_t Budget::getYear() const
{
    return m_Year;
}

void Budget::setYear(int32_t value)
{
    m_Year = value;
    m_YearIsSet = true;
}

bool Budget::yearIsSet() const
{
    return m_YearIsSet;
}

void Budget::unsetYear()
{
    m_YearIsSet = false;
}

}
}
}
}


