/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/CustomerCommunicationUpdate.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CustomerCommunicationUpdate::CustomerCommunicationUpdate()
{
}

CustomerCommunicationUpdate::~CustomerCommunicationUpdate()
{
}

void CustomerCommunicationUpdate::validate()
{
    // TODO: implement validation
}

web::json::value CustomerCommunicationUpdate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Body.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body.get());
    }
    if(m_Channel.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("channel"))] = ModelBase::toJson(m_Channel.get());
    }
    if(m_ContactId.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("contactId"))] = ModelBase::toJson(m_ContactId.get());
    }
    if(m_Counterparty.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("counterparty"))] = ModelBase::toJson(m_Counterparty.get());
    }
    if(m_Direction.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("direction"))] = ModelBase::toJson(m_Direction.get());
    }
    if(m_OccurredAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("occurredAt"))] = ModelBase::toJson(m_OccurredAt.get());
    }
    if(m_Subject.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subject"))] = ModelBase::toJson(m_Subject.get());
    }
    if(m_Tags.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags.get());
    }

    return val;
}

bool CustomerCommunicationUpdate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("channel"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("channel")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CommunicationChannel> refVal_setChannel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setChannel);
            setChannel(refVal_setChannel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("contactId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("contactId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContactId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContactId);
            setContactId(refVal_setContactId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("counterparty"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("counterparty")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCounterparty;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCounterparty);
            setCounterparty(refVal_setCounterparty);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("direction"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("direction")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CommunicationDirection> refVal_setDirection;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDirection);
            setDirection(refVal_setDirection);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("occurredAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("occurredAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setOccurredAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOccurredAt);
            setOccurredAt(refVal_setOccurredAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subject")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubject);
            setSubject(refVal_setSubject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    return ok;
}

void CustomerCommunicationUpdate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Body.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body.get()));
    }
    if(m_Channel.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("channel")), m_Channel.get()));
    }
    if(m_ContactId.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("contactId")), m_ContactId.get()));
    }
    if(m_Counterparty.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("counterparty")), m_Counterparty.get()));
    }
    if(m_Direction.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("direction")), m_Direction.get()));
    }
    if(m_OccurredAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("occurredAt")), m_OccurredAt.get()));
    }
    if(m_Subject.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subject")), m_Subject.get()));
    }
    if(m_Tags.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags.get()));
    }
}

bool CustomerCommunicationUpdate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("channel"))))
    {
        std::shared_ptr<CommunicationChannel> refVal_setChannel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("channel"))), refVal_setChannel );
        setChannel(refVal_setChannel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("contactId"))))
    {
        utility::string_t refVal_setContactId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("contactId"))), refVal_setContactId );
        setContactId(refVal_setContactId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("counterparty"))))
    {
        utility::string_t refVal_setCounterparty;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("counterparty"))), refVal_setCounterparty );
        setCounterparty(refVal_setCounterparty);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("direction"))))
    {
        std::shared_ptr<CommunicationDirection> refVal_setDirection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("direction"))), refVal_setDirection );
        setDirection(refVal_setDirection);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("occurredAt"))))
    {
        utility::datetime refVal_setOccurredAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("occurredAt"))), refVal_setOccurredAt );
        setOccurredAt(refVal_setOccurredAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        utility::string_t refVal_setSubject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subject"))), refVal_setSubject );
        setSubject(refVal_setSubject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::shared_ptr<AnyType> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    return ok;
}


utility::string_t CustomerCommunicationUpdate::getBody() const
{
    return m_Body.get();
}


void CustomerCommunicationUpdate::setBody(const utility::string_t& value)
{
    m_Body = value;
}

bool CustomerCommunicationUpdate::bodyIsSet() const
{
    return m_Body.has_value();
}

void CustomerCommunicationUpdate::unsetBody()
{
    m_Body.reset();
}
std::shared_ptr<CommunicationChannel> CustomerCommunicationUpdate::getChannel() const
{
    return m_Channel.get();
}


void CustomerCommunicationUpdate::setChannel(const std::shared_ptr<CommunicationChannel>& value)
{
    m_Channel = value;
}

bool CustomerCommunicationUpdate::channelIsSet() const
{
    return m_Channel.has_value();
}

void CustomerCommunicationUpdate::unsetChannel()
{
    m_Channel.reset();
}
utility::string_t CustomerCommunicationUpdate::getContactId() const
{
    return m_ContactId.get();
}


void CustomerCommunicationUpdate::setContactId(const utility::string_t& value)
{
    m_ContactId = value;
}

bool CustomerCommunicationUpdate::contactIdIsSet() const
{
    return m_ContactId.has_value();
}

void CustomerCommunicationUpdate::unsetContactId()
{
    m_ContactId.reset();
}
utility::string_t CustomerCommunicationUpdate::getCounterparty() const
{
    return m_Counterparty.get();
}


void CustomerCommunicationUpdate::setCounterparty(const utility::string_t& value)
{
    m_Counterparty = value;
}

bool CustomerCommunicationUpdate::counterpartyIsSet() const
{
    return m_Counterparty.has_value();
}

void CustomerCommunicationUpdate::unsetCounterparty()
{
    m_Counterparty.reset();
}
std::shared_ptr<CommunicationDirection> CustomerCommunicationUpdate::getDirection() const
{
    return m_Direction.get();
}


void CustomerCommunicationUpdate::setDirection(const std::shared_ptr<CommunicationDirection>& value)
{
    m_Direction = value;
}

bool CustomerCommunicationUpdate::directionIsSet() const
{
    return m_Direction.has_value();
}

void CustomerCommunicationUpdate::unsetDirection()
{
    m_Direction.reset();
}
utility::datetime CustomerCommunicationUpdate::getOccurredAt() const
{
    return m_OccurredAt.get();
}


void CustomerCommunicationUpdate::setOccurredAt(const utility::datetime& value)
{
    m_OccurredAt = value;
}

bool CustomerCommunicationUpdate::occurredAtIsSet() const
{
    return m_OccurredAt.has_value();
}

void CustomerCommunicationUpdate::unsetOccurredAt()
{
    m_OccurredAt.reset();
}
utility::string_t CustomerCommunicationUpdate::getSubject() const
{
    return m_Subject.get();
}


void CustomerCommunicationUpdate::setSubject(const utility::string_t& value)
{
    m_Subject = value;
}

bool CustomerCommunicationUpdate::subjectIsSet() const
{
    return m_Subject.has_value();
}

void CustomerCommunicationUpdate::unsetSubject()
{
    m_Subject.reset();
}
std::shared_ptr<AnyType> CustomerCommunicationUpdate::getTags() const
{
    return m_Tags.get();
}


void CustomerCommunicationUpdate::setTags(const std::shared_ptr<AnyType>& value)
{
    m_Tags = value;
}

bool CustomerCommunicationUpdate::tagsIsSet() const
{
    return m_Tags.has_value();
}

void CustomerCommunicationUpdate::unsetTags()
{
    m_Tags.reset();
}

}
}
}
}


