/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/EmailTemplateCreate.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EmailTemplateCreate::EmailTemplateCreate()
{
    m_Body = utility::conversions::to_string_t("");
    m_BodyIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_StatusIsSet = false;
    m_Subject = utility::conversions::to_string_t("");
    m_SubjectIsSet = false;
}

EmailTemplateCreate::~EmailTemplateCreate()
{
}

void EmailTemplateCreate::validate()
{
    // TODO: implement validation
}

web::json::value EmailTemplateCreate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BodyIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("body"))] = ModelBase::toJson(m_Body);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_StatusIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("status"))] = ModelBase::toJson(m_Status);
    }
    if(m_SubjectIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subject"))] = ModelBase::toJson(m_Subject);
    }
    if(m_Variables.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("variables"))] = ModelBase::toJson(m_Variables.get());
    }

    return val;
}

bool EmailTemplateCreate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("body")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBody;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBody);
            setBody(refVal_setBody);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("status")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<EmailTemplateStatus> refVal_setStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatus);
            setStatus(refVal_setStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subject")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSubject;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubject);
            setSubject(refVal_setSubject);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("variables"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("variables")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setVariables;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVariables);
            setVariables(refVal_setVariables);
            
        }
    }
    return ok;
}

void EmailTemplateCreate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BodyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("body")), m_Body));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_StatusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("status")), m_Status));
    }
    if(m_SubjectIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subject")), m_Subject));
    }
    if(m_Variables.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("variables")), m_Variables.get()));
    }
}

bool EmailTemplateCreate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("body"))))
    {
        utility::string_t refVal_setBody;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("body"))), refVal_setBody );
        setBody(refVal_setBody);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("status"))))
    {
        std::shared_ptr<EmailTemplateStatus> refVal_setStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("status"))), refVal_setStatus );
        setStatus(refVal_setStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subject"))))
    {
        utility::string_t refVal_setSubject;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subject"))), refVal_setSubject );
        setSubject(refVal_setSubject);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("variables"))))
    {
        std::shared_ptr<AnyType> refVal_setVariables;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("variables"))), refVal_setVariables );
        setVariables(refVal_setVariables);
    }
    return ok;
}


utility::string_t EmailTemplateCreate::getBody() const
{
    return m_Body;
}


void EmailTemplateCreate::setBody(const utility::string_t& value)
{
    m_Body = value;
    m_BodyIsSet = true;
}

bool EmailTemplateCreate::bodyIsSet() const
{
    return m_BodyIsSet;
}

void EmailTemplateCreate::unsetBody()
{
    m_BodyIsSet = false;
}
utility::string_t EmailTemplateCreate::getName() const
{
    return m_Name;
}


void EmailTemplateCreate::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool EmailTemplateCreate::nameIsSet() const
{
    return m_NameIsSet;
}

void EmailTemplateCreate::unsetName()
{
    m_NameIsSet = false;
}
std::shared_ptr<EmailTemplateStatus> EmailTemplateCreate::getStatus() const
{
    return m_Status;
}


void EmailTemplateCreate::setStatus(const std::shared_ptr<EmailTemplateStatus>& value)
{
    m_Status = value;
    m_StatusIsSet = true;
}

bool EmailTemplateCreate::statusIsSet() const
{
    return m_StatusIsSet;
}

void EmailTemplateCreate::unsetStatus()
{
    m_StatusIsSet = false;
}
utility::string_t EmailTemplateCreate::getSubject() const
{
    return m_Subject;
}


void EmailTemplateCreate::setSubject(const utility::string_t& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}

bool EmailTemplateCreate::subjectIsSet() const
{
    return m_SubjectIsSet;
}

void EmailTemplateCreate::unsetSubject()
{
    m_SubjectIsSet = false;
}
std::shared_ptr<AnyType> EmailTemplateCreate::getVariables() const
{
    return m_Variables.get();
}


void EmailTemplateCreate::setVariables(const std::shared_ptr<AnyType>& value)
{
    m_Variables = value;
}

bool EmailTemplateCreate::variablesIsSet() const
{
    return m_Variables.has_value();
}

void EmailTemplateCreate::unsetVariables()
{
    m_Variables.reset();
}

}
}
}
}


