/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/EmissionEntry.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EmissionEntry::EmissionEntry()
{
    m_ActivityValue = utility::conversions::to_string_t("");
    m_ActivityValueIsSet = false;
    m_CategoryId = utility::conversions::to_string_t("");
    m_CategoryIdIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_EfSource = utility::conversions::to_string_t("");
    m_EfSourceIsSet = false;
    m_EfVersion = utility::conversions::to_string_t("");
    m_EfVersionIsSet = false;
    m_MethodIsSet = false;
    m_ScopeIsSet = false;
    m_Tco2e = utility::conversions::to_string_t("");
    m_Tco2eIsSet = false;
    m_Unit = utility::conversions::to_string_t("");
    m_UnitIsSet = false;
    m_Year = 0;
    m_YearIsSet = false;
}

EmissionEntry::~EmissionEntry()
{
}

void EmissionEntry::validate()
{
    // TODO: implement validation
}

web::json::value EmissionEntry::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ActivityValueIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("activityValue"))] = ModelBase::toJson(m_ActivityValue);
    }
    if(m_CategoryIdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("categoryId"))] = ModelBase::toJson(m_CategoryId);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_EfSourceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("efSource"))] = ModelBase::toJson(m_EfSource);
    }
    if(m_EfVersionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("efVersion"))] = ModelBase::toJson(m_EfVersion);
    }
    if(m_MethodIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("method"))] = ModelBase::toJson(m_Method);
    }
    if(m_ScopeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("scope"))] = ModelBase::toJson(m_Scope);
    }
    if(m_Tco2eIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tco2e"))] = ModelBase::toJson(m_Tco2e);
    }
    if(m_UnitIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("unit"))] = ModelBase::toJson(m_Unit);
    }
    if(m_UpdatedAt.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updatedAt"))] = ModelBase::toJson(m_UpdatedAt.get());
    }
    if(m_YearIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("year"))] = ModelBase::toJson(m_Year);
    }

    return val;
}

bool EmissionEntry::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("activityValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("activityValue")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setActivityValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setActivityValue);
            setActivityValue(refVal_setActivityValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("categoryId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("categoryId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCategoryId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategoryId);
            setCategoryId(refVal_setCategoryId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("efSource"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("efSource")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEfSource;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEfSource);
            setEfSource(refVal_setEfSource);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("efVersion"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("efVersion")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEfVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEfVersion);
            setEfVersion(refVal_setEfVersion);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("method"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("method")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<EmissionMethod> refVal_setMethod;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMethod);
            setMethod(refVal_setMethod);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("scope")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<GhgScope> refVal_setScope;
            ok &= ModelBase::fromJson(fieldValue, refVal_setScope);
            setScope(refVal_setScope);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tco2e"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tco2e")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTco2e;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTco2e);
            setTco2e(refVal_setTco2e);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("unit")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUnit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnit);
            setUnit(refVal_setUnit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updatedAt")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("year")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setYear;
            ok &= ModelBase::fromJson(fieldValue, refVal_setYear);
            setYear(refVal_setYear);
            
        }
    }
    return ok;
}

void EmissionEntry::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ActivityValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("activityValue")), m_ActivityValue));
    }
    if(m_CategoryIdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("categoryId")), m_CategoryId));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_EfSourceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("efSource")), m_EfSource));
    }
    if(m_EfVersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("efVersion")), m_EfVersion));
    }
    if(m_MethodIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("method")), m_Method));
    }
    if(m_ScopeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("scope")), m_Scope));
    }
    if(m_Tco2eIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tco2e")), m_Tco2e));
    }
    if(m_UnitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("unit")), m_Unit));
    }
    if(m_UpdatedAt.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updatedAt")), m_UpdatedAt.get()));
    }
    if(m_YearIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("year")), m_Year));
    }
}

bool EmissionEntry::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("activityValue"))))
    {
        utility::string_t refVal_setActivityValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("activityValue"))), refVal_setActivityValue );
        setActivityValue(refVal_setActivityValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("categoryId"))))
    {
        utility::string_t refVal_setCategoryId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("categoryId"))), refVal_setCategoryId );
        setCategoryId(refVal_setCategoryId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("efSource"))))
    {
        utility::string_t refVal_setEfSource;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("efSource"))), refVal_setEfSource );
        setEfSource(refVal_setEfSource);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("efVersion"))))
    {
        utility::string_t refVal_setEfVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("efVersion"))), refVal_setEfVersion );
        setEfVersion(refVal_setEfVersion);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("method"))))
    {
        std::shared_ptr<EmissionMethod> refVal_setMethod;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("method"))), refVal_setMethod );
        setMethod(refVal_setMethod);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        std::shared_ptr<GhgScope> refVal_setScope;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("scope"))), refVal_setScope );
        setScope(refVal_setScope);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tco2e"))))
    {
        utility::string_t refVal_setTco2e;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tco2e"))), refVal_setTco2e );
        setTco2e(refVal_setTco2e);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        utility::string_t refVal_setUnit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("unit"))), refVal_setUnit );
        setUnit(refVal_setUnit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updatedAt"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("year"))))
    {
        int32_t refVal_setYear;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("year"))), refVal_setYear );
        setYear(refVal_setYear);
    }
    return ok;
}


utility::string_t EmissionEntry::getActivityValue() const
{
    return m_ActivityValue;
}


void EmissionEntry::setActivityValue(const utility::string_t& value)
{
    m_ActivityValue = value;
    m_ActivityValueIsSet = true;
}

bool EmissionEntry::activityValueIsSet() const
{
    return m_ActivityValueIsSet;
}

void EmissionEntry::unsetActivityValue()
{
    m_ActivityValueIsSet = false;
}
utility::string_t EmissionEntry::getCategoryId() const
{
    return m_CategoryId;
}


void EmissionEntry::setCategoryId(const utility::string_t& value)
{
    m_CategoryId = value;
    m_CategoryIdIsSet = true;
}

bool EmissionEntry::categoryIdIsSet() const
{
    return m_CategoryIdIsSet;
}

void EmissionEntry::unsetCategoryId()
{
    m_CategoryIdIsSet = false;
}
utility::string_t EmissionEntry::getDescription() const
{
    return m_Description;
}


void EmissionEntry::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool EmissionEntry::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void EmissionEntry::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t EmissionEntry::getEfSource() const
{
    return m_EfSource;
}


void EmissionEntry::setEfSource(const utility::string_t& value)
{
    m_EfSource = value;
    m_EfSourceIsSet = true;
}

bool EmissionEntry::efSourceIsSet() const
{
    return m_EfSourceIsSet;
}

void EmissionEntry::unsetEfSource()
{
    m_EfSourceIsSet = false;
}
utility::string_t EmissionEntry::getEfVersion() const
{
    return m_EfVersion;
}


void EmissionEntry::setEfVersion(const utility::string_t& value)
{
    m_EfVersion = value;
    m_EfVersionIsSet = true;
}

bool EmissionEntry::efVersionIsSet() const
{
    return m_EfVersionIsSet;
}

void EmissionEntry::unsetEfVersion()
{
    m_EfVersionIsSet = false;
}
std::shared_ptr<EmissionMethod> EmissionEntry::getMethod() const
{
    return m_Method;
}


void EmissionEntry::setMethod(const std::shared_ptr<EmissionMethod>& value)
{
    m_Method = value;
    m_MethodIsSet = true;
}

bool EmissionEntry::methodIsSet() const
{
    return m_MethodIsSet;
}

void EmissionEntry::unsetMethod()
{
    m_MethodIsSet = false;
}
std::shared_ptr<GhgScope> EmissionEntry::getScope() const
{
    return m_Scope;
}


void EmissionEntry::setScope(const std::shared_ptr<GhgScope>& value)
{
    m_Scope = value;
    m_ScopeIsSet = true;
}

bool EmissionEntry::scopeIsSet() const
{
    return m_ScopeIsSet;
}

void EmissionEntry::unsetScope()
{
    m_ScopeIsSet = false;
}
utility::string_t EmissionEntry::getTco2e() const
{
    return m_Tco2e;
}


void EmissionEntry::setTco2e(const utility::string_t& value)
{
    m_Tco2e = value;
    m_Tco2eIsSet = true;
}

bool EmissionEntry::tco2eIsSet() const
{
    return m_Tco2eIsSet;
}

void EmissionEntry::unsetTco2e()
{
    m_Tco2eIsSet = false;
}
utility::string_t EmissionEntry::getUnit() const
{
    return m_Unit;
}


void EmissionEntry::setUnit(const utility::string_t& value)
{
    m_Unit = value;
    m_UnitIsSet = true;
}

bool EmissionEntry::unitIsSet() const
{
    return m_UnitIsSet;
}

void EmissionEntry::unsetUnit()
{
    m_UnitIsSet = false;
}
utility::datetime EmissionEntry::getUpdatedAt() const
{
    return m_UpdatedAt.get();
}


void EmissionEntry::setUpdatedAt(const utility::datetime& value)
{
    m_UpdatedAt = value;
}

bool EmissionEntry::updatedAtIsSet() const
{
    return m_UpdatedAt.has_value();
}

void EmissionEntry::unsetUpdatedAt()
{
    m_UpdatedAt.reset();
}
int32_t EmissionEntry::getYear() const
{
    return m_Year;
}

void EmissionEntry::setYear(int32_t value)
{
    m_Year = value;
    m_YearIsSet = true;
}

bool EmissionEntry::yearIsSet() const
{
    return m_YearIsSet;
}

void EmissionEntry::unsetYear()
{
    m_YearIsSet = false;
}

}
}
}
}


