/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/EuerKatSumme.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

EuerKatSumme::EuerKatSumme()
{
    m_Betrag = utility::conversions::to_string_t("");
    m_BetragIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
}

EuerKatSumme::~EuerKatSumme()
{
}

void EuerKatSumme::validate()
{
    // TODO: implement validation
}

web::json::value EuerKatSumme::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_BetragIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("betrag"))] = ModelBase::toJson(m_Betrag);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }

    return val;
}

bool EuerKatSumme::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("betrag"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("betrag")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBetrag;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBetrag);
            setBetrag(refVal_setBetrag);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    return ok;
}

void EuerKatSumme::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_BetragIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("betrag")), m_Betrag));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
}

bool EuerKatSumme::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("betrag"))))
    {
        utility::string_t refVal_setBetrag;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("betrag"))), refVal_setBetrag );
        setBetrag(refVal_setBetrag);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    return ok;
}


utility::string_t EuerKatSumme::getBetrag() const
{
    return m_Betrag;
}


void EuerKatSumme::setBetrag(const utility::string_t& value)
{
    m_Betrag = value;
    m_BetragIsSet = true;
}

bool EuerKatSumme::betragIsSet() const
{
    return m_BetragIsSet;
}

void EuerKatSumme::unsetBetrag()
{
    m_BetragIsSet = false;
}
utility::string_t EuerKatSumme::getName() const
{
    return m_Name;
}


void EuerKatSumme::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool EuerKatSumme::nameIsSet() const
{
    return m_NameIsSet;
}

void EuerKatSumme::unsetName()
{
    m_NameIsSet = false;
}

}
}
}
}


