/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/GatewayOAuthAuthorizeRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

GatewayOAuthAuthorizeRequest::GatewayOAuthAuthorizeRequest()
{
    m_Gateway_type = utility::conversions::to_string_t("");
    m_Gateway_typeIsSet = false;
    m_Redirect_uri = utility::conversions::to_string_t("");
    m_Redirect_uriIsSet = false;
}

GatewayOAuthAuthorizeRequest::~GatewayOAuthAuthorizeRequest()
{
}

void GatewayOAuthAuthorizeRequest::validate()
{
    // TODO: implement validation
}

web::json::value GatewayOAuthAuthorizeRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Gateway_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gateway_type"))] = ModelBase::toJson(m_Gateway_type);
    }
    if(m_Redirect_uriIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("redirect_uri"))] = ModelBase::toJson(m_Redirect_uri);
    }

    return val;
}

bool GatewayOAuthAuthorizeRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gateway_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gateway_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGatewayType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGatewayType);
            setGatewayType(refVal_setGatewayType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("redirect_uri"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("redirect_uri")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRedirectUri;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRedirectUri);
            setRedirectUri(refVal_setRedirectUri);
            
        }
    }
    return ok;
}

void GatewayOAuthAuthorizeRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Gateway_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gateway_type")), m_Gateway_type));
    }
    if(m_Redirect_uriIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("redirect_uri")), m_Redirect_uri));
    }
}

bool GatewayOAuthAuthorizeRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gateway_type"))))
    {
        utility::string_t refVal_setGatewayType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gateway_type"))), refVal_setGatewayType );
        setGatewayType(refVal_setGatewayType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("redirect_uri"))))
    {
        utility::string_t refVal_setRedirectUri;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("redirect_uri"))), refVal_setRedirectUri );
        setRedirectUri(refVal_setRedirectUri);
    }
    return ok;
}


utility::string_t GatewayOAuthAuthorizeRequest::getGatewayType() const
{
    return m_Gateway_type;
}


void GatewayOAuthAuthorizeRequest::setGatewayType(const utility::string_t& value)
{
    m_Gateway_type = value;
    m_Gateway_typeIsSet = true;
}

bool GatewayOAuthAuthorizeRequest::gatewayTypeIsSet() const
{
    return m_Gateway_typeIsSet;
}

void GatewayOAuthAuthorizeRequest::unsetGateway_type()
{
    m_Gateway_typeIsSet = false;
}
utility::string_t GatewayOAuthAuthorizeRequest::getRedirectUri() const
{
    return m_Redirect_uri;
}


void GatewayOAuthAuthorizeRequest::setRedirectUri(const utility::string_t& value)
{
    m_Redirect_uri = value;
    m_Redirect_uriIsSet = true;
}

bool GatewayOAuthAuthorizeRequest::redirectUriIsSet() const
{
    return m_Redirect_uriIsSet;
}

void GatewayOAuthAuthorizeRequest::unsetRedirect_uri()
{
    m_Redirect_uriIsSet = false;
}

}
}
}
}


