/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/InstituteProfile.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

InstituteProfile::InstituteProfile()
{
    m_InstituteTypeIsSet = false;
    m_Kapitalmarktorientiert = false;
    m_KapitalmarktorientiertIsSet = false;
}

InstituteProfile::~InstituteProfile()
{
}

void InstituteProfile::validate()
{
    // TODO: implement validation
}

web::json::value InstituteProfile::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_InstituteTypeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("instituteType"))] = ModelBase::toJson(m_InstituteType);
    }
    if(m_KapitalmarktorientiertIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert"))] = ModelBase::toJson(m_Kapitalmarktorientiert);
    }

    return val;
}

bool InstituteProfile::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("instituteType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("instituteType")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<InstituteType> refVal_setInstituteType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInstituteType);
            setInstituteType(refVal_setInstituteType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert")));
        if(!fieldValue.is_null())
        {
            bool refVal_setKapitalmarktorientiert;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKapitalmarktorientiert);
            setKapitalmarktorientiert(refVal_setKapitalmarktorientiert);
            
        }
    }
    return ok;
}

void InstituteProfile::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_InstituteTypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("instituteType")), m_InstituteType));
    }
    if(m_KapitalmarktorientiertIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert")), m_Kapitalmarktorientiert));
    }
}

bool InstituteProfile::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("instituteType"))))
    {
        std::shared_ptr<InstituteType> refVal_setInstituteType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("instituteType"))), refVal_setInstituteType );
        setInstituteType(refVal_setInstituteType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert"))))
    {
        bool refVal_setKapitalmarktorientiert;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kapitalmarktorientiert"))), refVal_setKapitalmarktorientiert );
        setKapitalmarktorientiert(refVal_setKapitalmarktorientiert);
    }
    return ok;
}


std::shared_ptr<InstituteType> InstituteProfile::getInstituteType() const
{
    return m_InstituteType;
}


void InstituteProfile::setInstituteType(const std::shared_ptr<InstituteType>& value)
{
    m_InstituteType = value;
    m_InstituteTypeIsSet = true;
}

bool InstituteProfile::instituteTypeIsSet() const
{
    return m_InstituteTypeIsSet;
}

void InstituteProfile::unsetInstituteType()
{
    m_InstituteTypeIsSet = false;
}
bool InstituteProfile::isKapitalmarktorientiert() const
{
    return m_Kapitalmarktorientiert;
}

void InstituteProfile::setKapitalmarktorientiert(bool value)
{
    m_Kapitalmarktorientiert = value;
    m_KapitalmarktorientiertIsSet = true;
}

bool InstituteProfile::kapitalmarktorientiertIsSet() const
{
    return m_KapitalmarktorientiertIsSet;
}

void InstituteProfile::unsetKapitalmarktorientiert()
{
    m_KapitalmarktorientiertIsSet = false;
}

}
}
}
}


