/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/LiquidityPosition.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

LiquidityPosition::LiquidityPosition()
{
    m_Accounts_payable = 0.0;
    m_Accounts_payableIsSet = false;
    m_Accounts_receivable = 0.0;
    m_Accounts_receivableIsSet = false;
    m_Cash_and_equivalents = 0.0;
    m_Cash_and_equivalentsIsSet = false;
    m_Current_ratio = 0.0;
    m_Current_ratioIsSet = false;
    m_Quick_ratio = 0.0;
    m_Quick_ratioIsSet = false;
    m_Working_capital = 0.0;
    m_Working_capitalIsSet = false;
}

LiquidityPosition::~LiquidityPosition()
{
}

void LiquidityPosition::validate()
{
    // TODO: implement validation
}

web::json::value LiquidityPosition::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Accounts_payableIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accounts_payable"))] = ModelBase::toJson(m_Accounts_payable);
    }
    if(m_Accounts_receivableIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("accounts_receivable"))] = ModelBase::toJson(m_Accounts_receivable);
    }
    if(m_Cash_and_equivalentsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents"))] = ModelBase::toJson(m_Cash_and_equivalents);
    }
    if(m_Current_ratioIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("current_ratio"))] = ModelBase::toJson(m_Current_ratio);
    }
    if(m_Quick_ratioIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("quick_ratio"))] = ModelBase::toJson(m_Quick_ratio);
    }
    if(m_Working_capitalIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("working_capital"))] = ModelBase::toJson(m_Working_capital);
    }

    return val;
}

bool LiquidityPosition::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accounts_payable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accounts_payable")));
        if(!fieldValue.is_null())
        {
            double refVal_setAccountsPayable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccountsPayable);
            setAccountsPayable(refVal_setAccountsPayable);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("accounts_receivable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("accounts_receivable")));
        if(!fieldValue.is_null())
        {
            double refVal_setAccountsReceivable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccountsReceivable);
            setAccountsReceivable(refVal_setAccountsReceivable);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents")));
        if(!fieldValue.is_null())
        {
            double refVal_setCashAndEquivalents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCashAndEquivalents);
            setCashAndEquivalents(refVal_setCashAndEquivalents);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("current_ratio"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("current_ratio")));
        if(!fieldValue.is_null())
        {
            double refVal_setCurrentRatio;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurrentRatio);
            setCurrentRatio(refVal_setCurrentRatio);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("quick_ratio"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("quick_ratio")));
        if(!fieldValue.is_null())
        {
            double refVal_setQuickRatio;
            ok &= ModelBase::fromJson(fieldValue, refVal_setQuickRatio);
            setQuickRatio(refVal_setQuickRatio);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("working_capital"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("working_capital")));
        if(!fieldValue.is_null())
        {
            double refVal_setWorkingCapital;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWorkingCapital);
            setWorkingCapital(refVal_setWorkingCapital);
            
        }
    }
    return ok;
}

void LiquidityPosition::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Accounts_payableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accounts_payable")), m_Accounts_payable));
    }
    if(m_Accounts_receivableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("accounts_receivable")), m_Accounts_receivable));
    }
    if(m_Cash_and_equivalentsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents")), m_Cash_and_equivalents));
    }
    if(m_Current_ratioIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("current_ratio")), m_Current_ratio));
    }
    if(m_Quick_ratioIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("quick_ratio")), m_Quick_ratio));
    }
    if(m_Working_capitalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("working_capital")), m_Working_capital));
    }
}

bool LiquidityPosition::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accounts_payable"))))
    {
        double refVal_setAccountsPayable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accounts_payable"))), refVal_setAccountsPayable );
        setAccountsPayable(refVal_setAccountsPayable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("accounts_receivable"))))
    {
        double refVal_setAccountsReceivable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("accounts_receivable"))), refVal_setAccountsReceivable );
        setAccountsReceivable(refVal_setAccountsReceivable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents"))))
    {
        double refVal_setCashAndEquivalents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("cash_and_equivalents"))), refVal_setCashAndEquivalents );
        setCashAndEquivalents(refVal_setCashAndEquivalents);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("current_ratio"))))
    {
        double refVal_setCurrentRatio;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("current_ratio"))), refVal_setCurrentRatio );
        setCurrentRatio(refVal_setCurrentRatio);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("quick_ratio"))))
    {
        double refVal_setQuickRatio;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("quick_ratio"))), refVal_setQuickRatio );
        setQuickRatio(refVal_setQuickRatio);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("working_capital"))))
    {
        double refVal_setWorkingCapital;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("working_capital"))), refVal_setWorkingCapital );
        setWorkingCapital(refVal_setWorkingCapital);
    }
    return ok;
}


double LiquidityPosition::getAccountsPayable() const
{
    return m_Accounts_payable;
}

void LiquidityPosition::setAccountsPayable(double value)
{
    m_Accounts_payable = value;
    m_Accounts_payableIsSet = true;
}

bool LiquidityPosition::accountsPayableIsSet() const
{
    return m_Accounts_payableIsSet;
}

void LiquidityPosition::unsetAccounts_payable()
{
    m_Accounts_payableIsSet = false;
}
double LiquidityPosition::getAccountsReceivable() const
{
    return m_Accounts_receivable;
}

void LiquidityPosition::setAccountsReceivable(double value)
{
    m_Accounts_receivable = value;
    m_Accounts_receivableIsSet = true;
}

bool LiquidityPosition::accountsReceivableIsSet() const
{
    return m_Accounts_receivableIsSet;
}

void LiquidityPosition::unsetAccounts_receivable()
{
    m_Accounts_receivableIsSet = false;
}
double LiquidityPosition::getCashAndEquivalents() const
{
    return m_Cash_and_equivalents;
}

void LiquidityPosition::setCashAndEquivalents(double value)
{
    m_Cash_and_equivalents = value;
    m_Cash_and_equivalentsIsSet = true;
}

bool LiquidityPosition::cashAndEquivalentsIsSet() const
{
    return m_Cash_and_equivalentsIsSet;
}

void LiquidityPosition::unsetCash_and_equivalents()
{
    m_Cash_and_equivalentsIsSet = false;
}
double LiquidityPosition::getCurrentRatio() const
{
    return m_Current_ratio;
}

void LiquidityPosition::setCurrentRatio(double value)
{
    m_Current_ratio = value;
    m_Current_ratioIsSet = true;
}

bool LiquidityPosition::currentRatioIsSet() const
{
    return m_Current_ratioIsSet;
}

void LiquidityPosition::unsetCurrent_ratio()
{
    m_Current_ratioIsSet = false;
}
double LiquidityPosition::getQuickRatio() const
{
    return m_Quick_ratio;
}

void LiquidityPosition::setQuickRatio(double value)
{
    m_Quick_ratio = value;
    m_Quick_ratioIsSet = true;
}

bool LiquidityPosition::quickRatioIsSet() const
{
    return m_Quick_ratioIsSet;
}

void LiquidityPosition::unsetQuick_ratio()
{
    m_Quick_ratioIsSet = false;
}
double LiquidityPosition::getWorkingCapital() const
{
    return m_Working_capital;
}

void LiquidityPosition::setWorkingCapital(double value)
{
    m_Working_capital = value;
    m_Working_capitalIsSet = true;
}

bool LiquidityPosition::workingCapitalIsSet() const
{
    return m_Working_capitalIsSet;
}

void LiquidityPosition::unsetWorking_capital()
{
    m_Working_capitalIsSet = false;
}

}
}
}
}


