/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Model.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Model::Model()
{
    m_Backup_codesIsSet = false;
    m_Created_at = utility::datetime();
    m_Created_atIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_Email_verified = false;
    m_Email_verifiedIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Is_active = false;
    m_Is_activeIsSet = false;
    m_Is_totp_enabled = false;
    m_Is_totp_enabledIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Password_hash = utility::conversions::to_string_t("");
    m_Password_hashIsSet = false;
    m_Updated_at = utility::datetime();
    m_Updated_atIsSet = false;
}

Model::~Model()
{
}

void Model::validate()
{
    // TODO: implement validation
}

web::json::value Model::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Backup_codesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("backup_codes"))] = ModelBase::toJson(m_Backup_codes);
    }
    if(m_Created_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("created_at"))] = ModelBase::toJson(m_Created_at);
    }
    if(m_Deleted_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deleted_at"))] = ModelBase::toJson(m_Deleted_at.get());
    }
    if(m_EmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_Email_verifiedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email_verified"))] = ModelBase::toJson(m_Email_verified);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Is_activeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_active"))] = ModelBase::toJson(m_Is_active);
    }
    if(m_Is_totp_enabledIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled"))] = ModelBase::toJson(m_Is_totp_enabled);
    }
    if(m_Last_login.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_login"))] = ModelBase::toJson(m_Last_login.get());
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Oauth_id.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("oauth_id"))] = ModelBase::toJson(m_Oauth_id.get());
    }
    if(m_Oauth_provider.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("oauth_provider"))] = ModelBase::toJson(m_Oauth_provider.get());
    }
    if(m_Password_changed_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("password_changed_at"))] = ModelBase::toJson(m_Password_changed_at.get());
    }
    if(m_Password_hashIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("password_hash"))] = ModelBase::toJson(m_Password_hash);
    }
    if(m_Picture.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("picture"))] = ModelBase::toJson(m_Picture.get());
    }
    if(m_Privacy_accepted_at.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at"))] = ModelBase::toJson(m_Privacy_accepted_at.get());
    }
    if(m_Totp_secret.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("totp_secret"))] = ModelBase::toJson(m_Totp_secret.get());
    }
    if(m_Updated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("updated_at"))] = ModelBase::toJson(m_Updated_at);
    }

    return val;
}

bool Model::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("backup_codes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("backup_codes")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setBackupCodes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBackupCodes);
            setBackupCodes(refVal_setBackupCodes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("created_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setCreatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCreatedAt);
            setCreatedAt(refVal_setCreatedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deleted_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDeletedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeletedAt);
            setDeletedAt(refVal_setDeletedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email_verified"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email_verified")));
        if(!fieldValue.is_null())
        {
            bool refVal_setEmailVerified;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmailVerified);
            setEmailVerified(refVal_setEmailVerified);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_active"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_active")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsActive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsActive);
            setIsActive(refVal_setIsActive);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsTotpEnabled;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsTotpEnabled);
            setIsTotpEnabled(refVal_setIsTotpEnabled);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_login"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_login")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setLastLogin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastLogin);
            setLastLogin(refVal_setLastLogin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("oauth_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("oauth_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOauthId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOauthId);
            setOauthId(refVal_setOauthId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("oauth_provider"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("oauth_provider")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOauthProvider;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOauthProvider);
            setOauthProvider(refVal_setOauthProvider);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("password_changed_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("password_changed_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setPasswordChangedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPasswordChangedAt);
            setPasswordChangedAt(refVal_setPasswordChangedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("password_hash"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("password_hash")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPasswordHash;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPasswordHash);
            setPasswordHash(refVal_setPasswordHash);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("picture"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("picture")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPicture;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPicture);
            setPicture(refVal_setPicture);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setPrivacyAcceptedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrivacyAcceptedAt);
            setPrivacyAcceptedAt(refVal_setPrivacyAcceptedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totp_secret"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totp_secret")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTotpSecret;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotpSecret);
            setTotpSecret(refVal_setTotpSecret);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("updated_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setUpdatedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUpdatedAt);
            setUpdatedAt(refVal_setUpdatedAt);
            
        }
    }
    return ok;
}

void Model::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Backup_codesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("backup_codes")), m_Backup_codes));
    }
    if(m_Created_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("created_at")), m_Created_at));
    }
    if(m_Deleted_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deleted_at")), m_Deleted_at.get()));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_Email_verifiedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email_verified")), m_Email_verified));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_Is_activeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_active")), m_Is_active));
    }
    if(m_Is_totp_enabledIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled")), m_Is_totp_enabled));
    }
    if(m_Last_login.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_login")), m_Last_login.get()));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Oauth_id.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("oauth_id")), m_Oauth_id.get()));
    }
    if(m_Oauth_provider.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("oauth_provider")), m_Oauth_provider.get()));
    }
    if(m_Password_changed_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("password_changed_at")), m_Password_changed_at.get()));
    }
    if(m_Password_hashIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("password_hash")), m_Password_hash));
    }
    if(m_Picture.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("picture")), m_Picture.get()));
    }
    if(m_Privacy_accepted_at.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at")), m_Privacy_accepted_at.get()));
    }
    if(m_Totp_secret.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totp_secret")), m_Totp_secret.get()));
    }
    if(m_Updated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("updated_at")), m_Updated_at));
    }
}

bool Model::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("backup_codes"))))
    {
        std::vector<utility::string_t> refVal_setBackupCodes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("backup_codes"))), refVal_setBackupCodes );
        setBackupCodes(refVal_setBackupCodes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))))
    {
        utility::datetime refVal_setCreatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("created_at"))), refVal_setCreatedAt );
        setCreatedAt(refVal_setCreatedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))))
    {
        utility::datetime refVal_setDeletedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deleted_at"))), refVal_setDeletedAt );
        setDeletedAt(refVal_setDeletedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email_verified"))))
    {
        bool refVal_setEmailVerified;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email_verified"))), refVal_setEmailVerified );
        setEmailVerified(refVal_setEmailVerified);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_active"))))
    {
        bool refVal_setIsActive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_active"))), refVal_setIsActive );
        setIsActive(refVal_setIsActive);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled"))))
    {
        bool refVal_setIsTotpEnabled;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("is_totp_enabled"))), refVal_setIsTotpEnabled );
        setIsTotpEnabled(refVal_setIsTotpEnabled);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_login"))))
    {
        utility::datetime refVal_setLastLogin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_login"))), refVal_setLastLogin );
        setLastLogin(refVal_setLastLogin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("oauth_id"))))
    {
        utility::string_t refVal_setOauthId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("oauth_id"))), refVal_setOauthId );
        setOauthId(refVal_setOauthId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("oauth_provider"))))
    {
        utility::string_t refVal_setOauthProvider;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("oauth_provider"))), refVal_setOauthProvider );
        setOauthProvider(refVal_setOauthProvider);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("password_changed_at"))))
    {
        utility::datetime refVal_setPasswordChangedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("password_changed_at"))), refVal_setPasswordChangedAt );
        setPasswordChangedAt(refVal_setPasswordChangedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("password_hash"))))
    {
        utility::string_t refVal_setPasswordHash;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("password_hash"))), refVal_setPasswordHash );
        setPasswordHash(refVal_setPasswordHash);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("picture"))))
    {
        utility::string_t refVal_setPicture;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("picture"))), refVal_setPicture );
        setPicture(refVal_setPicture);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at"))))
    {
        utility::datetime refVal_setPrivacyAcceptedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted_at"))), refVal_setPrivacyAcceptedAt );
        setPrivacyAcceptedAt(refVal_setPrivacyAcceptedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totp_secret"))))
    {
        utility::string_t refVal_setTotpSecret;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totp_secret"))), refVal_setTotpSecret );
        setTotpSecret(refVal_setTotpSecret);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))))
    {
        utility::datetime refVal_setUpdatedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("updated_at"))), refVal_setUpdatedAt );
        setUpdatedAt(refVal_setUpdatedAt);
    }
    return ok;
}


std::vector<utility::string_t> Model::getBackupCodes() const
{
    return m_Backup_codes;
}


void Model::setBackupCodes(const std::vector<utility::string_t>& value)
{
    m_Backup_codes = value;
    m_Backup_codesIsSet = true;
}

bool Model::backupCodesIsSet() const
{
    return m_Backup_codesIsSet;
}

void Model::unsetBackup_codes()
{
    m_Backup_codesIsSet = false;
}
utility::datetime Model::getCreatedAt() const
{
    return m_Created_at;
}


void Model::setCreatedAt(const utility::datetime& value)
{
    m_Created_at = value;
    m_Created_atIsSet = true;
}

bool Model::createdAtIsSet() const
{
    return m_Created_atIsSet;
}

void Model::unsetCreated_at()
{
    m_Created_atIsSet = false;
}
utility::datetime Model::getDeletedAt() const
{
    return m_Deleted_at.get();
}


void Model::setDeletedAt(const utility::datetime& value)
{
    m_Deleted_at = value;
}

bool Model::deletedAtIsSet() const
{
    return m_Deleted_at.has_value();
}

void Model::unsetDeleted_at()
{
    m_Deleted_at.reset();
}
utility::string_t Model::getEmail() const
{
    return m_Email;
}


void Model::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool Model::emailIsSet() const
{
    return m_EmailIsSet;
}

void Model::unsetEmail()
{
    m_EmailIsSet = false;
}
bool Model::isEmailVerified() const
{
    return m_Email_verified;
}

void Model::setEmailVerified(bool value)
{
    m_Email_verified = value;
    m_Email_verifiedIsSet = true;
}

bool Model::emailVerifiedIsSet() const
{
    return m_Email_verifiedIsSet;
}

void Model::unsetEmail_verified()
{
    m_Email_verifiedIsSet = false;
}
utility::string_t Model::getId() const
{
    return m_Id;
}


void Model::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Model::idIsSet() const
{
    return m_IdIsSet;
}

void Model::unsetId()
{
    m_IdIsSet = false;
}
bool Model::isIsActive() const
{
    return m_Is_active;
}

void Model::setIsActive(bool value)
{
    m_Is_active = value;
    m_Is_activeIsSet = true;
}

bool Model::isActiveIsSet() const
{
    return m_Is_activeIsSet;
}

void Model::unsetIs_active()
{
    m_Is_activeIsSet = false;
}
bool Model::isIsTotpEnabled() const
{
    return m_Is_totp_enabled;
}

void Model::setIsTotpEnabled(bool value)
{
    m_Is_totp_enabled = value;
    m_Is_totp_enabledIsSet = true;
}

bool Model::isTotpEnabledIsSet() const
{
    return m_Is_totp_enabledIsSet;
}

void Model::unsetIs_totp_enabled()
{
    m_Is_totp_enabledIsSet = false;
}
utility::datetime Model::getLastLogin() const
{
    return m_Last_login.get();
}


void Model::setLastLogin(const utility::datetime& value)
{
    m_Last_login = value;
}

bool Model::lastLoginIsSet() const
{
    return m_Last_login.has_value();
}

void Model::unsetLast_login()
{
    m_Last_login.reset();
}
utility::string_t Model::getName() const
{
    return m_Name;
}


void Model::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Model::nameIsSet() const
{
    return m_NameIsSet;
}

void Model::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t Model::getOauthId() const
{
    return m_Oauth_id.get();
}


void Model::setOauthId(const utility::string_t& value)
{
    m_Oauth_id = value;
}

bool Model::oauthIdIsSet() const
{
    return m_Oauth_id.has_value();
}

void Model::unsetOauth_id()
{
    m_Oauth_id.reset();
}
utility::string_t Model::getOauthProvider() const
{
    return m_Oauth_provider.get();
}


void Model::setOauthProvider(const utility::string_t& value)
{
    m_Oauth_provider = value;
}

bool Model::oauthProviderIsSet() const
{
    return m_Oauth_provider.has_value();
}

void Model::unsetOauth_provider()
{
    m_Oauth_provider.reset();
}
utility::datetime Model::getPasswordChangedAt() const
{
    return m_Password_changed_at.get();
}


void Model::setPasswordChangedAt(const utility::datetime& value)
{
    m_Password_changed_at = value;
}

bool Model::passwordChangedAtIsSet() const
{
    return m_Password_changed_at.has_value();
}

void Model::unsetPassword_changed_at()
{
    m_Password_changed_at.reset();
}
utility::string_t Model::getPasswordHash() const
{
    return m_Password_hash;
}


void Model::setPasswordHash(const utility::string_t& value)
{
    m_Password_hash = value;
    m_Password_hashIsSet = true;
}

bool Model::passwordHashIsSet() const
{
    return m_Password_hashIsSet;
}

void Model::unsetPassword_hash()
{
    m_Password_hashIsSet = false;
}
utility::string_t Model::getPicture() const
{
    return m_Picture.get();
}


void Model::setPicture(const utility::string_t& value)
{
    m_Picture = value;
}

bool Model::pictureIsSet() const
{
    return m_Picture.has_value();
}

void Model::unsetPicture()
{
    m_Picture.reset();
}
utility::datetime Model::getPrivacyAcceptedAt() const
{
    return m_Privacy_accepted_at.get();
}


void Model::setPrivacyAcceptedAt(const utility::datetime& value)
{
    m_Privacy_accepted_at = value;
}

bool Model::privacyAcceptedAtIsSet() const
{
    return m_Privacy_accepted_at.has_value();
}

void Model::unsetPrivacy_accepted_at()
{
    m_Privacy_accepted_at.reset();
}
utility::string_t Model::getTotpSecret() const
{
    return m_Totp_secret.get();
}


void Model::setTotpSecret(const utility::string_t& value)
{
    m_Totp_secret = value;
}

bool Model::totpSecretIsSet() const
{
    return m_Totp_secret.has_value();
}

void Model::unsetTotp_secret()
{
    m_Totp_secret.reset();
}
utility::datetime Model::getUpdatedAt() const
{
    return m_Updated_at;
}


void Model::setUpdatedAt(const utility::datetime& value)
{
    m_Updated_at = value;
    m_Updated_atIsSet = true;
}

bool Model::updatedAtIsSet() const
{
    return m_Updated_atIsSet;
}

void Model::unsetUpdated_at()
{
    m_Updated_atIsSet = false;
}

}
}
}
}


