/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/PackingCompleteResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PackingCompleteResponse::PackingCompleteResponse()
{
    m_Message = utility::conversions::to_string_t("");
    m_MessageIsSet = false;
    m_New_state = utility::conversions::to_string_t("");
    m_New_stateIsSet = false;
    m_Order_number = utility::conversions::to_string_t("");
    m_Order_numberIsSet = false;
    m_Success = false;
    m_SuccessIsSet = false;
}

PackingCompleteResponse::~PackingCompleteResponse()
{
}

void PackingCompleteResponse::validate()
{
    // TODO: implement validation
}

web::json::value PackingCompleteResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_MessageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("message"))] = ModelBase::toJson(m_Message);
    }
    if(m_New_stateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("new_state"))] = ModelBase::toJson(m_New_state);
    }
    if(m_Order_numberIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("order_number"))] = ModelBase::toJson(m_Order_number);
    }
    if(m_SuccessIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("success"))] = ModelBase::toJson(m_Success);
    }

    return val;
}

bool PackingCompleteResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessage);
            setMessage(refVal_setMessage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("new_state"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("new_state")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNewState;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNewState);
            setNewState(refVal_setNewState);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("order_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("order_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setOrderNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOrderNumber);
            setOrderNumber(refVal_setOrderNumber);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("success")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuccess);
            setSuccess(refVal_setSuccess);
            
        }
    }
    return ok;
}

void PackingCompleteResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_MessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("message")), m_Message));
    }
    if(m_New_stateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("new_state")), m_New_state));
    }
    if(m_Order_numberIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("order_number")), m_Order_number));
    }
    if(m_SuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("success")), m_Success));
    }
}

bool PackingCompleteResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        utility::string_t refVal_setMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("message"))), refVal_setMessage );
        setMessage(refVal_setMessage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("new_state"))))
    {
        utility::string_t refVal_setNewState;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("new_state"))), refVal_setNewState );
        setNewState(refVal_setNewState);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("order_number"))))
    {
        utility::string_t refVal_setOrderNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("order_number"))), refVal_setOrderNumber );
        setOrderNumber(refVal_setOrderNumber);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("success"))))
    {
        bool refVal_setSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("success"))), refVal_setSuccess );
        setSuccess(refVal_setSuccess);
    }
    return ok;
}


utility::string_t PackingCompleteResponse::getMessage() const
{
    return m_Message;
}


void PackingCompleteResponse::setMessage(const utility::string_t& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}

bool PackingCompleteResponse::messageIsSet() const
{
    return m_MessageIsSet;
}

void PackingCompleteResponse::unsetMessage()
{
    m_MessageIsSet = false;
}
utility::string_t PackingCompleteResponse::getNewState() const
{
    return m_New_state;
}


void PackingCompleteResponse::setNewState(const utility::string_t& value)
{
    m_New_state = value;
    m_New_stateIsSet = true;
}

bool PackingCompleteResponse::newStateIsSet() const
{
    return m_New_stateIsSet;
}

void PackingCompleteResponse::unsetNew_state()
{
    m_New_stateIsSet = false;
}
utility::string_t PackingCompleteResponse::getOrderNumber() const
{
    return m_Order_number;
}


void PackingCompleteResponse::setOrderNumber(const utility::string_t& value)
{
    m_Order_number = value;
    m_Order_numberIsSet = true;
}

bool PackingCompleteResponse::orderNumberIsSet() const
{
    return m_Order_numberIsSet;
}

void PackingCompleteResponse::unsetOrder_number()
{
    m_Order_numberIsSet = false;
}
bool PackingCompleteResponse::isSuccess() const
{
    return m_Success;
}

void PackingCompleteResponse::setSuccess(bool value)
{
    m_Success = value;
    m_SuccessIsSet = true;
}

bool PackingCompleteResponse::successIsSet() const
{
    return m_SuccessIsSet;
}

void PackingCompleteResponse::unsetSuccess()
{
    m_SuccessIsSet = false;
}

}
}
}
}


