/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/PaymentCondition.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PaymentCondition::PaymentCondition()
{
    m_Discount_days = 0;
    m_Discount_daysIsSet = false;
    m_Discount_percentage = 0.0;
    m_Discount_percentageIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Payment_term_days = 0;
    m_Payment_term_daysIsSet = false;
}

PaymentCondition::~PaymentCondition()
{
}

void PaymentCondition::validate()
{
    // TODO: implement validation
}

web::json::value PaymentCondition::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Discount_daysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("discount_days"))] = ModelBase::toJson(m_Discount_days);
    }
    if(m_Discount_percentageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("discount_percentage"))] = ModelBase::toJson(m_Discount_percentage);
    }
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Payment_term_daysIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("payment_term_days"))] = ModelBase::toJson(m_Payment_term_days);
    }

    return val;
}

bool PaymentCondition::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("discount_days"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("discount_days")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setDiscountDays;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDiscountDays);
            setDiscountDays(refVal_setDiscountDays);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("discount_percentage"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("discount_percentage")));
        if(!fieldValue.is_null())
        {
            double refVal_setDiscountPercentage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDiscountPercentage);
            setDiscountPercentage(refVal_setDiscountPercentage);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("payment_term_days"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("payment_term_days")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPaymentTermDays;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPaymentTermDays);
            setPaymentTermDays(refVal_setPaymentTermDays);
            
        }
    }
    return ok;
}

void PaymentCondition::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Discount_daysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("discount_days")), m_Discount_days));
    }
    if(m_Discount_percentageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("discount_percentage")), m_Discount_percentage));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Payment_term_daysIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("payment_term_days")), m_Payment_term_days));
    }
}

bool PaymentCondition::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("discount_days"))))
    {
        int32_t refVal_setDiscountDays;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("discount_days"))), refVal_setDiscountDays );
        setDiscountDays(refVal_setDiscountDays);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("discount_percentage"))))
    {
        double refVal_setDiscountPercentage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("discount_percentage"))), refVal_setDiscountPercentage );
        setDiscountPercentage(refVal_setDiscountPercentage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("payment_term_days"))))
    {
        int32_t refVal_setPaymentTermDays;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("payment_term_days"))), refVal_setPaymentTermDays );
        setPaymentTermDays(refVal_setPaymentTermDays);
    }
    return ok;
}


int32_t PaymentCondition::getDiscountDays() const
{
    return m_Discount_days;
}

void PaymentCondition::setDiscountDays(int32_t value)
{
    m_Discount_days = value;
    m_Discount_daysIsSet = true;
}

bool PaymentCondition::discountDaysIsSet() const
{
    return m_Discount_daysIsSet;
}

void PaymentCondition::unsetDiscount_days()
{
    m_Discount_daysIsSet = false;
}
double PaymentCondition::getDiscountPercentage() const
{
    return m_Discount_percentage;
}

void PaymentCondition::setDiscountPercentage(double value)
{
    m_Discount_percentage = value;
    m_Discount_percentageIsSet = true;
}

bool PaymentCondition::discountPercentageIsSet() const
{
    return m_Discount_percentageIsSet;
}

void PaymentCondition::unsetDiscount_percentage()
{
    m_Discount_percentageIsSet = false;
}
utility::string_t PaymentCondition::getId() const
{
    return m_Id;
}


void PaymentCondition::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool PaymentCondition::idIsSet() const
{
    return m_IdIsSet;
}

void PaymentCondition::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t PaymentCondition::getName() const
{
    return m_Name;
}


void PaymentCondition::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool PaymentCondition::nameIsSet() const
{
    return m_NameIsSet;
}

void PaymentCondition::unsetName()
{
    m_NameIsSet = false;
}
int32_t PaymentCondition::getPaymentTermDays() const
{
    return m_Payment_term_days;
}

void PaymentCondition::setPaymentTermDays(int32_t value)
{
    m_Payment_term_days = value;
    m_Payment_term_daysIsSet = true;
}

bool PaymentCondition::paymentTermDaysIsSet() const
{
    return m_Payment_term_daysIsSet;
}

void PaymentCondition::unsetPayment_term_days()
{
    m_Payment_term_daysIsSet = false;
}

}
}
}
}


