/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/PluginError_oneOf_2.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PluginError_oneOf_2::PluginError_oneOf_2()
{
    m_UnauthorizedIsSet = false;
}

PluginError_oneOf_2::~PluginError_oneOf_2()
{
}

void PluginError_oneOf_2::validate()
{
    // TODO: implement validation
}

web::json::value PluginError_oneOf_2::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_UnauthorizedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("Unauthorized"))] = ModelBase::toJson(m_Unauthorized);
    }

    return val;
}

bool PluginError_oneOf_2::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("Unauthorized"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("Unauthorized")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Object>> refVal_setUnauthorized;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnauthorized);
            setUnauthorized(refVal_setUnauthorized);
            
        }
    }
    return ok;
}

void PluginError_oneOf_2::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_UnauthorizedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("Unauthorized")), m_Unauthorized));
    }
}

bool PluginError_oneOf_2::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("Unauthorized"))))
    {
        std::vector<std::shared_ptr<Object>> refVal_setUnauthorized;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("Unauthorized"))), refVal_setUnauthorized );
        setUnauthorized(refVal_setUnauthorized);
    }
    return ok;
}


std::vector<std::shared_ptr<Object>> PluginError_oneOf_2::getUnauthorized() const
{
    return m_Unauthorized;
}


void PluginError_oneOf_2::setUnauthorized(const std::vector<std::shared_ptr<Object>>& value)
{
    m_Unauthorized = value;
    m_UnauthorizedIsSet = true;
}

bool PluginError_oneOf_2::unauthorizedIsSet() const
{
    return m_UnauthorizedIsSet;
}

void PluginError_oneOf_2::unsetUnauthorized()
{
    m_UnauthorizedIsSet = false;
}

}
}
}
}


