/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/PnLItem.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

PnLItem::PnLItem()
{
    m_Account = utility::conversions::to_string_t("");
    m_AccountIsSet = false;
    m_Account_name = utility::conversions::to_string_t("");
    m_Account_nameIsSet = false;
    m_Amount = utility::conversions::to_string_t("");
    m_AmountIsSet = false;
}

PnLItem::~PnLItem()
{
}

void PnLItem::validate()
{
    // TODO: implement validation
}

web::json::value PnLItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AccountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("account"))] = ModelBase::toJson(m_Account);
    }
    if(m_Account_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("account_name"))] = ModelBase::toJson(m_Account_name);
    }
    if(m_AmountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("amount"))] = ModelBase::toJson(m_Amount);
    }

    return val;
}

bool PnLItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("account"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("account")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAccount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccount);
            setAccount(refVal_setAccount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("account_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("account_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAccountName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAccountName);
            setAccountName(refVal_setAccountName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("amount")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAmount);
            setAmount(refVal_setAmount);
            
        }
    }
    return ok;
}

void PnLItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AccountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("account")), m_Account));
    }
    if(m_Account_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("account_name")), m_Account_name));
    }
    if(m_AmountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("amount")), m_Amount));
    }
}

bool PnLItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("account"))))
    {
        utility::string_t refVal_setAccount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("account"))), refVal_setAccount );
        setAccount(refVal_setAccount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("account_name"))))
    {
        utility::string_t refVal_setAccountName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("account_name"))), refVal_setAccountName );
        setAccountName(refVal_setAccountName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("amount"))))
    {
        utility::string_t refVal_setAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("amount"))), refVal_setAmount );
        setAmount(refVal_setAmount);
    }
    return ok;
}


utility::string_t PnLItem::getAccount() const
{
    return m_Account;
}


void PnLItem::setAccount(const utility::string_t& value)
{
    m_Account = value;
    m_AccountIsSet = true;
}

bool PnLItem::accountIsSet() const
{
    return m_AccountIsSet;
}

void PnLItem::unsetAccount()
{
    m_AccountIsSet = false;
}
utility::string_t PnLItem::getAccountName() const
{
    return m_Account_name;
}


void PnLItem::setAccountName(const utility::string_t& value)
{
    m_Account_name = value;
    m_Account_nameIsSet = true;
}

bool PnLItem::accountNameIsSet() const
{
    return m_Account_nameIsSet;
}

void PnLItem::unsetAccount_name()
{
    m_Account_nameIsSet = false;
}
utility::string_t PnLItem::getAmount() const
{
    return m_Amount;
}


void PnLItem::setAmount(const utility::string_t& value)
{
    m_Amount = value;
    m_AmountIsSet = true;
}

bool PnLItem::amountIsSet() const
{
    return m_AmountIsSet;
}

void PnLItem::unsetAmount()
{
    m_AmountIsSet = false;
}

}
}
}
}


