/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ProductCreate.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ProductCreate::ProductCreate()
{
    m_IsTaxable = false;
    m_IsTaxableIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_ProductCode = utility::conversions::to_string_t("");
    m_ProductCodeIsSet = false;
    m_Sku = utility::conversions::to_string_t("");
    m_SkuIsSet = false;
    m_TrackBatch = false;
    m_TrackBatchIsSet = false;
    m_TrackSerial = false;
    m_TrackSerialIsSet = false;
}

ProductCreate::~ProductCreate()
{
}

void ProductCreate::validate()
{
    // TODO: implement validation
}

web::json::value ProductCreate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Availability.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("availability"))] = ModelBase::toJson(m_Availability.get());
    }
    if(m_Barcode.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("barcode"))] = ModelBase::toJson(m_Barcode.get());
    }
    if(m_Brand.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("brand"))] = ModelBase::toJson(m_Brand.get());
    }
    if(m_CategoryId.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("categoryId"))] = ModelBase::toJson(m_CategoryId.get());
    }
    if(m_Condition.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("condition"))] = ModelBase::toJson(m_Condition.get());
    }
    if(m_DefaultLedgerAccount.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount"))] = ModelBase::toJson(m_DefaultLedgerAccount.get());
    }
    if(m_DefaultPrice.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultPrice"))] = ModelBase::toJson(m_DefaultPrice.get());
    }
    if(m_DefaultPriceFormulaId.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId"))] = ModelBase::toJson(m_DefaultPriceFormulaId.get());
    }
    if(m_DefaultTaxRate.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate"))] = ModelBase::toJson(m_DefaultTaxRate.get());
    }
    if(m_Description.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description.get());
    }
    if(m_Gtin.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gtin"))] = ModelBase::toJson(m_Gtin.get());
    }
    if(m_Height.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("height"))] = ModelBase::toJson(m_Height.get());
    }
    if(m_ImageLink.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("imageLink"))] = ModelBase::toJson(m_ImageLink.get());
    }
    if(m_Images.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("images"))] = ModelBase::toJson(m_Images.get());
    }
    if(m_IsTaxableIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isTaxable"))] = ModelBase::toJson(m_IsTaxable);
    }
    if(m_Length.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("length"))] = ModelBase::toJson(m_Length.get());
    }
    if(m_Link.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("link"))] = ModelBase::toJson(m_Link.get());
    }
    if(m_MaxStock.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("maxStock"))] = ModelBase::toJson(m_MaxStock.get());
    }
    if(m_MinStock.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("minStock"))] = ModelBase::toJson(m_MinStock.get());
    }
    if(m_Mpn.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("mpn"))] = ModelBase::toJson(m_Mpn.get());
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_PackageHeight.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageHeight"))] = ModelBase::toJson(m_PackageHeight.get());
    }
    if(m_PackageLength.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageLength"))] = ModelBase::toJson(m_PackageLength.get());
    }
    if(m_PackageWeightUnit.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit"))] = ModelBase::toJson(m_PackageWeightUnit.get());
    }
    if(m_PackageWeightValue.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageWeightValue"))] = ModelBase::toJson(m_PackageWeightValue.get());
    }
    if(m_PackageWidth.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("packageWidth"))] = ModelBase::toJson(m_PackageWidth.get());
    }
    if(m_ProductCodeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("productCode"))] = ModelBase::toJson(m_ProductCode);
    }
    if(m_ProductType.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("productType"))] = ModelBase::toJson(m_ProductType.get());
    }
    if(m_PurchasePrice.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("purchasePrice"))] = ModelBase::toJson(m_PurchasePrice.get());
    }
    if(m_ReorderQuantity.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("reorderQuantity"))] = ModelBase::toJson(m_ReorderQuantity.get());
    }
    if(m_SalePrice.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("salePrice"))] = ModelBase::toJson(m_SalePrice.get());
    }
    if(m_ShippingPrice.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shippingPrice"))] = ModelBase::toJson(m_ShippingPrice.get());
    }
    if(m_ShippingRequiresInsurance.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance"))] = ModelBase::toJson(m_ShippingRequiresInsurance.get());
    }
    if(m_SkuIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("sku"))] = ModelBase::toJson(m_Sku);
    }
    if(m_StockQuantity.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stockQuantity"))] = ModelBase::toJson(m_StockQuantity.get());
    }
    if(m_Tags.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tags"))] = ModelBase::toJson(m_Tags.get());
    }
    if(m_TaxPrice.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("taxPrice"))] = ModelBase::toJson(m_TaxPrice.get());
    }
    if(m_TrackBatchIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trackBatch"))] = ModelBase::toJson(m_TrackBatch);
    }
    if(m_TrackSerialIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("trackSerial"))] = ModelBase::toJson(m_TrackSerial);
    }
    if(m_Unit.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("unit"))] = ModelBase::toJson(m_Unit.get());
    }
    if(m_WeightUnit.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("weightUnit"))] = ModelBase::toJson(m_WeightUnit.get());
    }
    if(m_WeightValue.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("weightValue"))] = ModelBase::toJson(m_WeightValue.get());
    }
    if(m_Width.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("width"))] = ModelBase::toJson(m_Width.get());
    }

    return val;
}

bool ProductCreate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("availability"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("availability")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvailability;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvailability);
            setAvailability(refVal_setAvailability);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("barcode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("barcode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBarcode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBarcode);
            setBarcode(refVal_setBarcode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("brand"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("brand")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setBrand;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBrand);
            setBrand(refVal_setBrand);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("categoryId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("categoryId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCategoryId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCategoryId);
            setCategoryId(refVal_setCategoryId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("condition"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("condition")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCondition;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCondition);
            setCondition(refVal_setCondition);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDefaultLedgerAccount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultLedgerAccount);
            setDefaultLedgerAccount(refVal_setDefaultLedgerAccount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultPrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultPrice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDefaultPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultPrice);
            setDefaultPrice(refVal_setDefaultPrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDefaultPriceFormulaId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultPriceFormulaId);
            setDefaultPriceFormulaId(refVal_setDefaultPriceFormulaId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDefaultTaxRate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDefaultTaxRate);
            setDefaultTaxRate(refVal_setDefaultTaxRate);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gtin"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gtin")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGtin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGtin);
            setGtin(refVal_setGtin);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("height"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("height")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHeight;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHeight);
            setHeight(refVal_setHeight);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("imageLink"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("imageLink")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setImageLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImageLink);
            setImageLink(refVal_setImageLink);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("images"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("images")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setImages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setImages);
            setImages(refVal_setImages);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isTaxable"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isTaxable")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsTaxable;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsTaxable);
            setIsTaxable(refVal_setIsTaxable);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("length"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("length")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLength;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLength);
            setLength(refVal_setLength);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("link")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLink;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLink);
            setLink(refVal_setLink);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("maxStock"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("maxStock")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setMaxStock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxStock);
            setMaxStock(refVal_setMaxStock);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("minStock"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("minStock")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setMinStock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMinStock);
            setMinStock(refVal_setMinStock);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("mpn"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("mpn")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMpn;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMpn);
            setMpn(refVal_setMpn);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageHeight"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageHeight")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPackageHeight;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageHeight);
            setPackageHeight(refVal_setPackageHeight);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageLength"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageLength")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPackageLength;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageLength);
            setPackageLength(refVal_setPackageLength);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPackageWeightUnit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageWeightUnit);
            setPackageWeightUnit(refVal_setPackageWeightUnit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageWeightValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageWeightValue")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPackageWeightValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageWeightValue);
            setPackageWeightValue(refVal_setPackageWeightValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("packageWidth"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("packageWidth")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPackageWidth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPackageWidth);
            setPackageWidth(refVal_setPackageWidth);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("productCode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("productCode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProductCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProductCode);
            setProductCode(refVal_setProductCode);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("productType"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("productType")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProductType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProductType);
            setProductType(refVal_setProductType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("purchasePrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("purchasePrice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPurchasePrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPurchasePrice);
            setPurchasePrice(refVal_setPurchasePrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("reorderQuantity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("reorderQuantity")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setReorderQuantity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReorderQuantity);
            setReorderQuantity(refVal_setReorderQuantity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("salePrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("salePrice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSalePrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSalePrice);
            setSalePrice(refVal_setSalePrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shippingPrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shippingPrice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setShippingPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShippingPrice);
            setShippingPrice(refVal_setShippingPrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance")));
        if(!fieldValue.is_null())
        {
            bool refVal_setShippingRequiresInsurance;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShippingRequiresInsurance);
            setShippingRequiresInsurance(refVal_setShippingRequiresInsurance);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("sku"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("sku")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setSku;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSku);
            setSku(refVal_setSku);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stockQuantity"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stockQuantity")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setStockQuantity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStockQuantity);
            setStockQuantity(refVal_setStockQuantity);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tags")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setTags;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTags);
            setTags(refVal_setTags);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("taxPrice"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("taxPrice")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTaxPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaxPrice);
            setTaxPrice(refVal_setTaxPrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trackBatch"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trackBatch")));
        if(!fieldValue.is_null())
        {
            bool refVal_setTrackBatch;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTrackBatch);
            setTrackBatch(refVal_setTrackBatch);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("trackSerial"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("trackSerial")));
        if(!fieldValue.is_null())
        {
            bool refVal_setTrackSerial;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTrackSerial);
            setTrackSerial(refVal_setTrackSerial);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("unit")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setUnit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUnit);
            setUnit(refVal_setUnit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weightUnit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weightUnit")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWeightUnit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeightUnit);
            setWeightUnit(refVal_setWeightUnit);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("weightValue"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("weightValue")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWeightValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWeightValue);
            setWeightValue(refVal_setWeightValue);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("width"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("width")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWidth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWidth);
            setWidth(refVal_setWidth);
            
        }
    }
    return ok;
}

void ProductCreate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Availability.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("availability")), m_Availability.get()));
    }
    if(m_Barcode.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("barcode")), m_Barcode.get()));
    }
    if(m_Brand.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("brand")), m_Brand.get()));
    }
    if(m_CategoryId.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("categoryId")), m_CategoryId.get()));
    }
    if(m_Condition.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("condition")), m_Condition.get()));
    }
    if(m_DefaultLedgerAccount.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount")), m_DefaultLedgerAccount.get()));
    }
    if(m_DefaultPrice.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultPrice")), m_DefaultPrice.get()));
    }
    if(m_DefaultPriceFormulaId.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId")), m_DefaultPriceFormulaId.get()));
    }
    if(m_DefaultTaxRate.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate")), m_DefaultTaxRate.get()));
    }
    if(m_Description.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description.get()));
    }
    if(m_Gtin.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gtin")), m_Gtin.get()));
    }
    if(m_Height.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("height")), m_Height.get()));
    }
    if(m_ImageLink.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("imageLink")), m_ImageLink.get()));
    }
    if(m_Images.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("images")), m_Images.get()));
    }
    if(m_IsTaxableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isTaxable")), m_IsTaxable));
    }
    if(m_Length.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("length")), m_Length.get()));
    }
    if(m_Link.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("link")), m_Link.get()));
    }
    if(m_MaxStock.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("maxStock")), m_MaxStock.get()));
    }
    if(m_MinStock.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("minStock")), m_MinStock.get()));
    }
    if(m_Mpn.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("mpn")), m_Mpn.get()));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_PackageHeight.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageHeight")), m_PackageHeight.get()));
    }
    if(m_PackageLength.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageLength")), m_PackageLength.get()));
    }
    if(m_PackageWeightUnit.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit")), m_PackageWeightUnit.get()));
    }
    if(m_PackageWeightValue.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageWeightValue")), m_PackageWeightValue.get()));
    }
    if(m_PackageWidth.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("packageWidth")), m_PackageWidth.get()));
    }
    if(m_ProductCodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("productCode")), m_ProductCode));
    }
    if(m_ProductType.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("productType")), m_ProductType.get()));
    }
    if(m_PurchasePrice.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("purchasePrice")), m_PurchasePrice.get()));
    }
    if(m_ReorderQuantity.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("reorderQuantity")), m_ReorderQuantity.get()));
    }
    if(m_SalePrice.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("salePrice")), m_SalePrice.get()));
    }
    if(m_ShippingPrice.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shippingPrice")), m_ShippingPrice.get()));
    }
    if(m_ShippingRequiresInsurance.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance")), m_ShippingRequiresInsurance.get()));
    }
    if(m_SkuIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("sku")), m_Sku));
    }
    if(m_StockQuantity.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stockQuantity")), m_StockQuantity.get()));
    }
    if(m_Tags.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tags")), m_Tags.get()));
    }
    if(m_TaxPrice.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("taxPrice")), m_TaxPrice.get()));
    }
    if(m_TrackBatchIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trackBatch")), m_TrackBatch));
    }
    if(m_TrackSerialIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("trackSerial")), m_TrackSerial));
    }
    if(m_Unit.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("unit")), m_Unit.get()));
    }
    if(m_WeightUnit.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weightUnit")), m_WeightUnit.get()));
    }
    if(m_WeightValue.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("weightValue")), m_WeightValue.get()));
    }
    if(m_Width.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("width")), m_Width.get()));
    }
}

bool ProductCreate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("availability"))))
    {
        utility::string_t refVal_setAvailability;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("availability"))), refVal_setAvailability );
        setAvailability(refVal_setAvailability);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("barcode"))))
    {
        utility::string_t refVal_setBarcode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("barcode"))), refVal_setBarcode );
        setBarcode(refVal_setBarcode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("brand"))))
    {
        utility::string_t refVal_setBrand;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("brand"))), refVal_setBrand );
        setBrand(refVal_setBrand);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("categoryId"))))
    {
        utility::string_t refVal_setCategoryId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("categoryId"))), refVal_setCategoryId );
        setCategoryId(refVal_setCategoryId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("condition"))))
    {
        utility::string_t refVal_setCondition;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("condition"))), refVal_setCondition );
        setCondition(refVal_setCondition);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount"))))
    {
        utility::string_t refVal_setDefaultLedgerAccount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultLedgerAccount"))), refVal_setDefaultLedgerAccount );
        setDefaultLedgerAccount(refVal_setDefaultLedgerAccount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultPrice"))))
    {
        utility::string_t refVal_setDefaultPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultPrice"))), refVal_setDefaultPrice );
        setDefaultPrice(refVal_setDefaultPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId"))))
    {
        utility::string_t refVal_setDefaultPriceFormulaId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultPriceFormulaId"))), refVal_setDefaultPriceFormulaId );
        setDefaultPriceFormulaId(refVal_setDefaultPriceFormulaId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate"))))
    {
        utility::string_t refVal_setDefaultTaxRate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("defaultTaxRate"))), refVal_setDefaultTaxRate );
        setDefaultTaxRate(refVal_setDefaultTaxRate);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gtin"))))
    {
        utility::string_t refVal_setGtin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gtin"))), refVal_setGtin );
        setGtin(refVal_setGtin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("height"))))
    {
        utility::string_t refVal_setHeight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("height"))), refVal_setHeight );
        setHeight(refVal_setHeight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("imageLink"))))
    {
        utility::string_t refVal_setImageLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("imageLink"))), refVal_setImageLink );
        setImageLink(refVal_setImageLink);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("images"))))
    {
        std::shared_ptr<AnyType> refVal_setImages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("images"))), refVal_setImages );
        setImages(refVal_setImages);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isTaxable"))))
    {
        bool refVal_setIsTaxable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isTaxable"))), refVal_setIsTaxable );
        setIsTaxable(refVal_setIsTaxable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("length"))))
    {
        utility::string_t refVal_setLength;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("length"))), refVal_setLength );
        setLength(refVal_setLength);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("link"))))
    {
        utility::string_t refVal_setLink;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("link"))), refVal_setLink );
        setLink(refVal_setLink);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("maxStock"))))
    {
        int64_t refVal_setMaxStock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("maxStock"))), refVal_setMaxStock );
        setMaxStock(refVal_setMaxStock);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("minStock"))))
    {
        int64_t refVal_setMinStock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("minStock"))), refVal_setMinStock );
        setMinStock(refVal_setMinStock);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("mpn"))))
    {
        utility::string_t refVal_setMpn;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("mpn"))), refVal_setMpn );
        setMpn(refVal_setMpn);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageHeight"))))
    {
        utility::string_t refVal_setPackageHeight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageHeight"))), refVal_setPackageHeight );
        setPackageHeight(refVal_setPackageHeight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageLength"))))
    {
        utility::string_t refVal_setPackageLength;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageLength"))), refVal_setPackageLength );
        setPackageLength(refVal_setPackageLength);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit"))))
    {
        utility::string_t refVal_setPackageWeightUnit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageWeightUnit"))), refVal_setPackageWeightUnit );
        setPackageWeightUnit(refVal_setPackageWeightUnit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageWeightValue"))))
    {
        utility::string_t refVal_setPackageWeightValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageWeightValue"))), refVal_setPackageWeightValue );
        setPackageWeightValue(refVal_setPackageWeightValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("packageWidth"))))
    {
        utility::string_t refVal_setPackageWidth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("packageWidth"))), refVal_setPackageWidth );
        setPackageWidth(refVal_setPackageWidth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("productCode"))))
    {
        utility::string_t refVal_setProductCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("productCode"))), refVal_setProductCode );
        setProductCode(refVal_setProductCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("productType"))))
    {
        utility::string_t refVal_setProductType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("productType"))), refVal_setProductType );
        setProductType(refVal_setProductType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("purchasePrice"))))
    {
        utility::string_t refVal_setPurchasePrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("purchasePrice"))), refVal_setPurchasePrice );
        setPurchasePrice(refVal_setPurchasePrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("reorderQuantity"))))
    {
        int64_t refVal_setReorderQuantity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("reorderQuantity"))), refVal_setReorderQuantity );
        setReorderQuantity(refVal_setReorderQuantity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("salePrice"))))
    {
        utility::string_t refVal_setSalePrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("salePrice"))), refVal_setSalePrice );
        setSalePrice(refVal_setSalePrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shippingPrice"))))
    {
        utility::string_t refVal_setShippingPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shippingPrice"))), refVal_setShippingPrice );
        setShippingPrice(refVal_setShippingPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance"))))
    {
        bool refVal_setShippingRequiresInsurance;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shippingRequiresInsurance"))), refVal_setShippingRequiresInsurance );
        setShippingRequiresInsurance(refVal_setShippingRequiresInsurance);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("sku"))))
    {
        utility::string_t refVal_setSku;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("sku"))), refVal_setSku );
        setSku(refVal_setSku);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stockQuantity"))))
    {
        int64_t refVal_setStockQuantity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stockQuantity"))), refVal_setStockQuantity );
        setStockQuantity(refVal_setStockQuantity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tags"))))
    {
        std::shared_ptr<AnyType> refVal_setTags;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tags"))), refVal_setTags );
        setTags(refVal_setTags);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("taxPrice"))))
    {
        utility::string_t refVal_setTaxPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("taxPrice"))), refVal_setTaxPrice );
        setTaxPrice(refVal_setTaxPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trackBatch"))))
    {
        bool refVal_setTrackBatch;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trackBatch"))), refVal_setTrackBatch );
        setTrackBatch(refVal_setTrackBatch);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("trackSerial"))))
    {
        bool refVal_setTrackSerial;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("trackSerial"))), refVal_setTrackSerial );
        setTrackSerial(refVal_setTrackSerial);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("unit"))))
    {
        std::shared_ptr<AnyType> refVal_setUnit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("unit"))), refVal_setUnit );
        setUnit(refVal_setUnit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weightUnit"))))
    {
        utility::string_t refVal_setWeightUnit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weightUnit"))), refVal_setWeightUnit );
        setWeightUnit(refVal_setWeightUnit);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("weightValue"))))
    {
        utility::string_t refVal_setWeightValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("weightValue"))), refVal_setWeightValue );
        setWeightValue(refVal_setWeightValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("width"))))
    {
        utility::string_t refVal_setWidth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("width"))), refVal_setWidth );
        setWidth(refVal_setWidth);
    }
    return ok;
}


utility::string_t ProductCreate::getAvailability() const
{
    return m_Availability.get();
}


void ProductCreate::setAvailability(const utility::string_t& value)
{
    m_Availability = value;
}

bool ProductCreate::availabilityIsSet() const
{
    return m_Availability.has_value();
}

void ProductCreate::unsetAvailability()
{
    m_Availability.reset();
}
utility::string_t ProductCreate::getBarcode() const
{
    return m_Barcode.get();
}


void ProductCreate::setBarcode(const utility::string_t& value)
{
    m_Barcode = value;
}

bool ProductCreate::barcodeIsSet() const
{
    return m_Barcode.has_value();
}

void ProductCreate::unsetBarcode()
{
    m_Barcode.reset();
}
utility::string_t ProductCreate::getBrand() const
{
    return m_Brand.get();
}


void ProductCreate::setBrand(const utility::string_t& value)
{
    m_Brand = value;
}

bool ProductCreate::brandIsSet() const
{
    return m_Brand.has_value();
}

void ProductCreate::unsetBrand()
{
    m_Brand.reset();
}
utility::string_t ProductCreate::getCategoryId() const
{
    return m_CategoryId.get();
}


void ProductCreate::setCategoryId(const utility::string_t& value)
{
    m_CategoryId = value;
}

bool ProductCreate::categoryIdIsSet() const
{
    return m_CategoryId.has_value();
}

void ProductCreate::unsetCategoryId()
{
    m_CategoryId.reset();
}
utility::string_t ProductCreate::getCondition() const
{
    return m_Condition.get();
}


void ProductCreate::setCondition(const utility::string_t& value)
{
    m_Condition = value;
}

bool ProductCreate::conditionIsSet() const
{
    return m_Condition.has_value();
}

void ProductCreate::unsetCondition()
{
    m_Condition.reset();
}
utility::string_t ProductCreate::getDefaultLedgerAccount() const
{
    return m_DefaultLedgerAccount.get();
}


void ProductCreate::setDefaultLedgerAccount(const utility::string_t& value)
{
    m_DefaultLedgerAccount = value;
}

bool ProductCreate::defaultLedgerAccountIsSet() const
{
    return m_DefaultLedgerAccount.has_value();
}

void ProductCreate::unsetDefaultLedgerAccount()
{
    m_DefaultLedgerAccount.reset();
}
utility::string_t ProductCreate::getDefaultPrice() const
{
    return m_DefaultPrice.get();
}


void ProductCreate::setDefaultPrice(const utility::string_t& value)
{
    m_DefaultPrice = value;
}

bool ProductCreate::defaultPriceIsSet() const
{
    return m_DefaultPrice.has_value();
}

void ProductCreate::unsetDefaultPrice()
{
    m_DefaultPrice.reset();
}
utility::string_t ProductCreate::getDefaultPriceFormulaId() const
{
    return m_DefaultPriceFormulaId.get();
}


void ProductCreate::setDefaultPriceFormulaId(const utility::string_t& value)
{
    m_DefaultPriceFormulaId = value;
}

bool ProductCreate::defaultPriceFormulaIdIsSet() const
{
    return m_DefaultPriceFormulaId.has_value();
}

void ProductCreate::unsetDefaultPriceFormulaId()
{
    m_DefaultPriceFormulaId.reset();
}
utility::string_t ProductCreate::getDefaultTaxRate() const
{
    return m_DefaultTaxRate.get();
}


void ProductCreate::setDefaultTaxRate(const utility::string_t& value)
{
    m_DefaultTaxRate = value;
}

bool ProductCreate::defaultTaxRateIsSet() const
{
    return m_DefaultTaxRate.has_value();
}

void ProductCreate::unsetDefaultTaxRate()
{
    m_DefaultTaxRate.reset();
}
utility::string_t ProductCreate::getDescription() const
{
    return m_Description.get();
}


void ProductCreate::setDescription(const utility::string_t& value)
{
    m_Description = value;
}

bool ProductCreate::descriptionIsSet() const
{
    return m_Description.has_value();
}

void ProductCreate::unsetDescription()
{
    m_Description.reset();
}
utility::string_t ProductCreate::getGtin() const
{
    return m_Gtin.get();
}


void ProductCreate::setGtin(const utility::string_t& value)
{
    m_Gtin = value;
}

bool ProductCreate::gtinIsSet() const
{
    return m_Gtin.has_value();
}

void ProductCreate::unsetGtin()
{
    m_Gtin.reset();
}
utility::string_t ProductCreate::getHeight() const
{
    return m_Height.get();
}


void ProductCreate::setHeight(const utility::string_t& value)
{
    m_Height = value;
}

bool ProductCreate::heightIsSet() const
{
    return m_Height.has_value();
}

void ProductCreate::unsetHeight()
{
    m_Height.reset();
}
utility::string_t ProductCreate::getImageLink() const
{
    return m_ImageLink.get();
}


void ProductCreate::setImageLink(const utility::string_t& value)
{
    m_ImageLink = value;
}

bool ProductCreate::imageLinkIsSet() const
{
    return m_ImageLink.has_value();
}

void ProductCreate::unsetImageLink()
{
    m_ImageLink.reset();
}
std::shared_ptr<AnyType> ProductCreate::getImages() const
{
    return m_Images.get();
}


void ProductCreate::setImages(const std::shared_ptr<AnyType>& value)
{
    m_Images = value;
}

bool ProductCreate::imagesIsSet() const
{
    return m_Images.has_value();
}

void ProductCreate::unsetImages()
{
    m_Images.reset();
}
bool ProductCreate::isIsTaxable() const
{
    return m_IsTaxable;
}

void ProductCreate::setIsTaxable(bool value)
{
    m_IsTaxable = value;
    m_IsTaxableIsSet = true;
}

bool ProductCreate::isTaxableIsSet() const
{
    return m_IsTaxableIsSet;
}

void ProductCreate::unsetIsTaxable()
{
    m_IsTaxableIsSet = false;
}
utility::string_t ProductCreate::getLength() const
{
    return m_Length.get();
}


void ProductCreate::setLength(const utility::string_t& value)
{
    m_Length = value;
}

bool ProductCreate::lengthIsSet() const
{
    return m_Length.has_value();
}

void ProductCreate::unsetLength()
{
    m_Length.reset();
}
utility::string_t ProductCreate::getLink() const
{
    return m_Link.get();
}


void ProductCreate::setLink(const utility::string_t& value)
{
    m_Link = value;
}

bool ProductCreate::linkIsSet() const
{
    return m_Link.has_value();
}

void ProductCreate::unsetLink()
{
    m_Link.reset();
}
int64_t ProductCreate::getMaxStock() const
{
    return m_MaxStock.get();
}

void ProductCreate::setMaxStock(int64_t value)
{
    m_MaxStock = value;
}

bool ProductCreate::maxStockIsSet() const
{
    return m_MaxStock.has_value();
}

void ProductCreate::unsetMaxStock()
{
    m_MaxStock.reset();
}
int64_t ProductCreate::getMinStock() const
{
    return m_MinStock.get();
}

void ProductCreate::setMinStock(int64_t value)
{
    m_MinStock = value;
}

bool ProductCreate::minStockIsSet() const
{
    return m_MinStock.has_value();
}

void ProductCreate::unsetMinStock()
{
    m_MinStock.reset();
}
utility::string_t ProductCreate::getMpn() const
{
    return m_Mpn.get();
}


void ProductCreate::setMpn(const utility::string_t& value)
{
    m_Mpn = value;
}

bool ProductCreate::mpnIsSet() const
{
    return m_Mpn.has_value();
}

void ProductCreate::unsetMpn()
{
    m_Mpn.reset();
}
utility::string_t ProductCreate::getName() const
{
    return m_Name;
}


void ProductCreate::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool ProductCreate::nameIsSet() const
{
    return m_NameIsSet;
}

void ProductCreate::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t ProductCreate::getPackageHeight() const
{
    return m_PackageHeight.get();
}


void ProductCreate::setPackageHeight(const utility::string_t& value)
{
    m_PackageHeight = value;
}

bool ProductCreate::packageHeightIsSet() const
{
    return m_PackageHeight.has_value();
}

void ProductCreate::unsetPackageHeight()
{
    m_PackageHeight.reset();
}
utility::string_t ProductCreate::getPackageLength() const
{
    return m_PackageLength.get();
}


void ProductCreate::setPackageLength(const utility::string_t& value)
{
    m_PackageLength = value;
}

bool ProductCreate::packageLengthIsSet() const
{
    return m_PackageLength.has_value();
}

void ProductCreate::unsetPackageLength()
{
    m_PackageLength.reset();
}
utility::string_t ProductCreate::getPackageWeightUnit() const
{
    return m_PackageWeightUnit.get();
}


void ProductCreate::setPackageWeightUnit(const utility::string_t& value)
{
    m_PackageWeightUnit = value;
}

bool ProductCreate::packageWeightUnitIsSet() const
{
    return m_PackageWeightUnit.has_value();
}

void ProductCreate::unsetPackageWeightUnit()
{
    m_PackageWeightUnit.reset();
}
utility::string_t ProductCreate::getPackageWeightValue() const
{
    return m_PackageWeightValue.get();
}


void ProductCreate::setPackageWeightValue(const utility::string_t& value)
{
    m_PackageWeightValue = value;
}

bool ProductCreate::packageWeightValueIsSet() const
{
    return m_PackageWeightValue.has_value();
}

void ProductCreate::unsetPackageWeightValue()
{
    m_PackageWeightValue.reset();
}
utility::string_t ProductCreate::getPackageWidth() const
{
    return m_PackageWidth.get();
}


void ProductCreate::setPackageWidth(const utility::string_t& value)
{
    m_PackageWidth = value;
}

bool ProductCreate::packageWidthIsSet() const
{
    return m_PackageWidth.has_value();
}

void ProductCreate::unsetPackageWidth()
{
    m_PackageWidth.reset();
}
utility::string_t ProductCreate::getProductCode() const
{
    return m_ProductCode;
}


void ProductCreate::setProductCode(const utility::string_t& value)
{
    m_ProductCode = value;
    m_ProductCodeIsSet = true;
}

bool ProductCreate::productCodeIsSet() const
{
    return m_ProductCodeIsSet;
}

void ProductCreate::unsetProductCode()
{
    m_ProductCodeIsSet = false;
}
utility::string_t ProductCreate::getProductType() const
{
    return m_ProductType.get();
}


void ProductCreate::setProductType(const utility::string_t& value)
{
    m_ProductType = value;
}

bool ProductCreate::productTypeIsSet() const
{
    return m_ProductType.has_value();
}

void ProductCreate::unsetProductType()
{
    m_ProductType.reset();
}
utility::string_t ProductCreate::getPurchasePrice() const
{
    return m_PurchasePrice.get();
}


void ProductCreate::setPurchasePrice(const utility::string_t& value)
{
    m_PurchasePrice = value;
}

bool ProductCreate::purchasePriceIsSet() const
{
    return m_PurchasePrice.has_value();
}

void ProductCreate::unsetPurchasePrice()
{
    m_PurchasePrice.reset();
}
int64_t ProductCreate::getReorderQuantity() const
{
    return m_ReorderQuantity.get();
}

void ProductCreate::setReorderQuantity(int64_t value)
{
    m_ReorderQuantity = value;
}

bool ProductCreate::reorderQuantityIsSet() const
{
    return m_ReorderQuantity.has_value();
}

void ProductCreate::unsetReorderQuantity()
{
    m_ReorderQuantity.reset();
}
utility::string_t ProductCreate::getSalePrice() const
{
    return m_SalePrice.get();
}


void ProductCreate::setSalePrice(const utility::string_t& value)
{
    m_SalePrice = value;
}

bool ProductCreate::salePriceIsSet() const
{
    return m_SalePrice.has_value();
}

void ProductCreate::unsetSalePrice()
{
    m_SalePrice.reset();
}
utility::string_t ProductCreate::getShippingPrice() const
{
    return m_ShippingPrice.get();
}


void ProductCreate::setShippingPrice(const utility::string_t& value)
{
    m_ShippingPrice = value;
}

bool ProductCreate::shippingPriceIsSet() const
{
    return m_ShippingPrice.has_value();
}

void ProductCreate::unsetShippingPrice()
{
    m_ShippingPrice.reset();
}
bool ProductCreate::isShippingRequiresInsurance() const
{
    return m_ShippingRequiresInsurance.get();
}

void ProductCreate::setShippingRequiresInsurance(bool value)
{
    m_ShippingRequiresInsurance = value;
}

bool ProductCreate::shippingRequiresInsuranceIsSet() const
{
    return m_ShippingRequiresInsurance.has_value();
}

void ProductCreate::unsetShippingRequiresInsurance()
{
    m_ShippingRequiresInsurance.reset();
}
utility::string_t ProductCreate::getSku() const
{
    return m_Sku;
}


void ProductCreate::setSku(const utility::string_t& value)
{
    m_Sku = value;
    m_SkuIsSet = true;
}

bool ProductCreate::skuIsSet() const
{
    return m_SkuIsSet;
}

void ProductCreate::unsetSku()
{
    m_SkuIsSet = false;
}
int64_t ProductCreate::getStockQuantity() const
{
    return m_StockQuantity.get();
}

void ProductCreate::setStockQuantity(int64_t value)
{
    m_StockQuantity = value;
}

bool ProductCreate::stockQuantityIsSet() const
{
    return m_StockQuantity.has_value();
}

void ProductCreate::unsetStockQuantity()
{
    m_StockQuantity.reset();
}
std::shared_ptr<AnyType> ProductCreate::getTags() const
{
    return m_Tags.get();
}


void ProductCreate::setTags(const std::shared_ptr<AnyType>& value)
{
    m_Tags = value;
}

bool ProductCreate::tagsIsSet() const
{
    return m_Tags.has_value();
}

void ProductCreate::unsetTags()
{
    m_Tags.reset();
}
utility::string_t ProductCreate::getTaxPrice() const
{
    return m_TaxPrice.get();
}


void ProductCreate::setTaxPrice(const utility::string_t& value)
{
    m_TaxPrice = value;
}

bool ProductCreate::taxPriceIsSet() const
{
    return m_TaxPrice.has_value();
}

void ProductCreate::unsetTaxPrice()
{
    m_TaxPrice.reset();
}
bool ProductCreate::isTrackBatch() const
{
    return m_TrackBatch;
}

void ProductCreate::setTrackBatch(bool value)
{
    m_TrackBatch = value;
    m_TrackBatchIsSet = true;
}

bool ProductCreate::trackBatchIsSet() const
{
    return m_TrackBatchIsSet;
}

void ProductCreate::unsetTrackBatch()
{
    m_TrackBatchIsSet = false;
}
bool ProductCreate::isTrackSerial() const
{
    return m_TrackSerial;
}

void ProductCreate::setTrackSerial(bool value)
{
    m_TrackSerial = value;
    m_TrackSerialIsSet = true;
}

bool ProductCreate::trackSerialIsSet() const
{
    return m_TrackSerialIsSet;
}

void ProductCreate::unsetTrackSerial()
{
    m_TrackSerialIsSet = false;
}
std::shared_ptr<AnyType> ProductCreate::getUnit() const
{
    return m_Unit.get();
}


void ProductCreate::setUnit(const std::shared_ptr<AnyType>& value)
{
    m_Unit = value;
}

bool ProductCreate::unitIsSet() const
{
    return m_Unit.has_value();
}

void ProductCreate::unsetUnit()
{
    m_Unit.reset();
}
utility::string_t ProductCreate::getWeightUnit() const
{
    return m_WeightUnit.get();
}


void ProductCreate::setWeightUnit(const utility::string_t& value)
{
    m_WeightUnit = value;
}

bool ProductCreate::weightUnitIsSet() const
{
    return m_WeightUnit.has_value();
}

void ProductCreate::unsetWeightUnit()
{
    m_WeightUnit.reset();
}
utility::string_t ProductCreate::getWeightValue() const
{
    return m_WeightValue.get();
}


void ProductCreate::setWeightValue(const utility::string_t& value)
{
    m_WeightValue = value;
}

bool ProductCreate::weightValueIsSet() const
{
    return m_WeightValue.has_value();
}

void ProductCreate::unsetWeightValue()
{
    m_WeightValue.reset();
}
utility::string_t ProductCreate::getWidth() const
{
    return m_Width.get();
}


void ProductCreate::setWidth(const utility::string_t& value)
{
    m_Width = value;
}

bool ProductCreate::widthIsSet() const
{
    return m_Width.has_value();
}

void ProductCreate::unsetWidth()
{
    m_Width.reset();
}

}
}
}
}


