/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/RegisterRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RegisterRequest::RegisterRequest()
{
    m_Company_name = utility::conversions::to_string_t("");
    m_Company_nameIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_First_name = utility::conversions::to_string_t("");
    m_First_nameIsSet = false;
    m_Last_name = utility::conversions::to_string_t("");
    m_Last_nameIsSet = false;
    m_Password = utility::conversions::to_string_t("");
    m_PasswordIsSet = false;
    m_Privacy_accepted = false;
    m_Privacy_acceptedIsSet = false;
}

RegisterRequest::~RegisterRequest()
{
}

void RegisterRequest::validate()
{
    // TODO: implement validation
}

web::json::value RegisterRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Company_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("company_name"))] = ModelBase::toJson(m_Company_name);
    }
    if(m_EmailIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_First_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("first_name"))] = ModelBase::toJson(m_First_name);
    }
    if(m_Last_nameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("last_name"))] = ModelBase::toJson(m_Last_name);
    }
    if(m_PasswordIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("password"))] = ModelBase::toJson(m_Password);
    }
    if(m_Privacy_acceptedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("privacy_accepted"))] = ModelBase::toJson(m_Privacy_accepted);
    }

    return val;
}

bool RegisterRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("company_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("company_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCompanyName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCompanyName);
            setCompanyName(refVal_setCompanyName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("first_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("first_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFirstName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFirstName);
            setFirstName(refVal_setFirstName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("last_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("last_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastName);
            setLastName(refVal_setLastName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("password"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("password")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPassword;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPassword);
            setPassword(refVal_setPassword);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted")));
        if(!fieldValue.is_null())
        {
            bool refVal_setPrivacyAccepted;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrivacyAccepted);
            setPrivacyAccepted(refVal_setPrivacyAccepted);
            
        }
    }
    return ok;
}

void RegisterRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Company_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("company_name")), m_Company_name));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("email")), m_Email));
    }
    if(m_First_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("first_name")), m_First_name));
    }
    if(m_Last_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("last_name")), m_Last_name));
    }
    if(m_PasswordIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("password")), m_Password));
    }
    if(m_Privacy_acceptedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("privacy_accepted")), m_Privacy_accepted));
    }
}

bool RegisterRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("company_name"))))
    {
        utility::string_t refVal_setCompanyName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("company_name"))), refVal_setCompanyName );
        setCompanyName(refVal_setCompanyName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("first_name"))))
    {
        utility::string_t refVal_setFirstName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("first_name"))), refVal_setFirstName );
        setFirstName(refVal_setFirstName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("last_name"))))
    {
        utility::string_t refVal_setLastName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("last_name"))), refVal_setLastName );
        setLastName(refVal_setLastName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("password"))))
    {
        utility::string_t refVal_setPassword;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("password"))), refVal_setPassword );
        setPassword(refVal_setPassword);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted"))))
    {
        bool refVal_setPrivacyAccepted;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("privacy_accepted"))), refVal_setPrivacyAccepted );
        setPrivacyAccepted(refVal_setPrivacyAccepted);
    }
    return ok;
}


utility::string_t RegisterRequest::getCompanyName() const
{
    return m_Company_name;
}


void RegisterRequest::setCompanyName(const utility::string_t& value)
{
    m_Company_name = value;
    m_Company_nameIsSet = true;
}

bool RegisterRequest::companyNameIsSet() const
{
    return m_Company_nameIsSet;
}

void RegisterRequest::unsetCompany_name()
{
    m_Company_nameIsSet = false;
}
utility::string_t RegisterRequest::getEmail() const
{
    return m_Email;
}


void RegisterRequest::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool RegisterRequest::emailIsSet() const
{
    return m_EmailIsSet;
}

void RegisterRequest::unsetEmail()
{
    m_EmailIsSet = false;
}
utility::string_t RegisterRequest::getFirstName() const
{
    return m_First_name;
}


void RegisterRequest::setFirstName(const utility::string_t& value)
{
    m_First_name = value;
    m_First_nameIsSet = true;
}

bool RegisterRequest::firstNameIsSet() const
{
    return m_First_nameIsSet;
}

void RegisterRequest::unsetFirst_name()
{
    m_First_nameIsSet = false;
}
utility::string_t RegisterRequest::getLastName() const
{
    return m_Last_name;
}


void RegisterRequest::setLastName(const utility::string_t& value)
{
    m_Last_name = value;
    m_Last_nameIsSet = true;
}

bool RegisterRequest::lastNameIsSet() const
{
    return m_Last_nameIsSet;
}

void RegisterRequest::unsetLast_name()
{
    m_Last_nameIsSet = false;
}
utility::string_t RegisterRequest::getPassword() const
{
    return m_Password;
}


void RegisterRequest::setPassword(const utility::string_t& value)
{
    m_Password = value;
    m_PasswordIsSet = true;
}

bool RegisterRequest::passwordIsSet() const
{
    return m_PasswordIsSet;
}

void RegisterRequest::unsetPassword()
{
    m_PasswordIsSet = false;
}
bool RegisterRequest::isPrivacyAccepted() const
{
    return m_Privacy_accepted;
}

void RegisterRequest::setPrivacyAccepted(bool value)
{
    m_Privacy_accepted = value;
    m_Privacy_acceptedIsSet = true;
}

bool RegisterRequest::privacyAcceptedIsSet() const
{
    return m_Privacy_acceptedIsSet;
}

void RegisterRequest::unsetPrivacy_accepted()
{
    m_Privacy_acceptedIsSet = false;
}

}
}
}
}


