/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ReturnLogisticsSummary.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ReturnLogisticsSummary::ReturnLogisticsSummary()
{
    m_ByWarehouseIsSet = false;
    m_ItemsRestocked = 0L;
    m_ItemsRestockedIsSet = false;
    m_ItemsScrapped = 0L;
    m_ItemsScrappedIsSet = false;
    m_TotalItems = 0L;
    m_TotalItemsIsSet = false;
    m_TotalReturns = 0L;
    m_TotalReturnsIsSet = false;
}

ReturnLogisticsSummary::~ReturnLogisticsSummary()
{
}

void ReturnLogisticsSummary::validate()
{
    // TODO: implement validation
}

web::json::value ReturnLogisticsSummary::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ByStatus.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("byStatus"))] = ModelBase::toJson(m_ByStatus.get());
    }
    if(m_ByWarehouseIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("byWarehouse"))] = ModelBase::toJson(m_ByWarehouse);
    }
    if(m_ItemsRestockedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))] = ModelBase::toJson(m_ItemsRestocked);
    }
    if(m_ItemsScrappedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))] = ModelBase::toJson(m_ItemsScrapped);
    }
    if(m_TotalItemsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("totalItems"))] = ModelBase::toJson(m_TotalItems);
    }
    if(m_TotalReturnsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("totalReturns"))] = ModelBase::toJson(m_TotalReturns);
    }

    return val;
}

bool ReturnLogisticsSummary::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("byStatus"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("byStatus")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setByStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setByStatus);
            setByStatus(refVal_setByStatus);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("byWarehouse"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("byWarehouse")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ReturnWarehouseSummary>> refVal_setByWarehouse;
            ok &= ModelBase::fromJson(fieldValue, refVal_setByWarehouse);
            setByWarehouse(refVal_setByWarehouse);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setItemsRestocked;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItemsRestocked);
            setItemsRestocked(refVal_setItemsRestocked);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setItemsScrapped;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItemsScrapped);
            setItemsScrapped(refVal_setItemsScrapped);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totalItems"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totalItems")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTotalItems;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalItems);
            setTotalItems(refVal_setTotalItems);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("totalReturns"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("totalReturns")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTotalReturns;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalReturns);
            setTotalReturns(refVal_setTotalReturns);
            
        }
    }
    return ok;
}

void ReturnLogisticsSummary::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ByStatus.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("byStatus")), m_ByStatus.get()));
    }
    if(m_ByWarehouseIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("byWarehouse")), m_ByWarehouse));
    }
    if(m_ItemsRestockedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("itemsRestocked")), m_ItemsRestocked));
    }
    if(m_ItemsScrappedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("itemsScrapped")), m_ItemsScrapped));
    }
    if(m_TotalItemsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totalItems")), m_TotalItems));
    }
    if(m_TotalReturnsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("totalReturns")), m_TotalReturns));
    }
}

bool ReturnLogisticsSummary::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("byStatus"))))
    {
        std::shared_ptr<AnyType> refVal_setByStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("byStatus"))), refVal_setByStatus );
        setByStatus(refVal_setByStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("byWarehouse"))))
    {
        std::vector<std::shared_ptr<ReturnWarehouseSummary>> refVal_setByWarehouse;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("byWarehouse"))), refVal_setByWarehouse );
        setByWarehouse(refVal_setByWarehouse);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))))
    {
        int64_t refVal_setItemsRestocked;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))), refVal_setItemsRestocked );
        setItemsRestocked(refVal_setItemsRestocked);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))))
    {
        int64_t refVal_setItemsScrapped;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))), refVal_setItemsScrapped );
        setItemsScrapped(refVal_setItemsScrapped);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totalItems"))))
    {
        int64_t refVal_setTotalItems;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totalItems"))), refVal_setTotalItems );
        setTotalItems(refVal_setTotalItems);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("totalReturns"))))
    {
        int64_t refVal_setTotalReturns;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("totalReturns"))), refVal_setTotalReturns );
        setTotalReturns(refVal_setTotalReturns);
    }
    return ok;
}


std::shared_ptr<AnyType> ReturnLogisticsSummary::getByStatus() const
{
    return m_ByStatus.get();
}


void ReturnLogisticsSummary::setByStatus(const std::shared_ptr<AnyType>& value)
{
    m_ByStatus = value;
}

bool ReturnLogisticsSummary::byStatusIsSet() const
{
    return m_ByStatus.has_value();
}

void ReturnLogisticsSummary::unsetByStatus()
{
    m_ByStatus.reset();
}
std::vector<std::shared_ptr<ReturnWarehouseSummary>> ReturnLogisticsSummary::getByWarehouse() const
{
    return m_ByWarehouse;
}


void ReturnLogisticsSummary::setByWarehouse(const std::vector<std::shared_ptr<ReturnWarehouseSummary>>& value)
{
    m_ByWarehouse = value;
    m_ByWarehouseIsSet = true;
}

bool ReturnLogisticsSummary::byWarehouseIsSet() const
{
    return m_ByWarehouseIsSet;
}

void ReturnLogisticsSummary::unsetByWarehouse()
{
    m_ByWarehouseIsSet = false;
}
int64_t ReturnLogisticsSummary::getItemsRestocked() const
{
    return m_ItemsRestocked;
}

void ReturnLogisticsSummary::setItemsRestocked(int64_t value)
{
    m_ItemsRestocked = value;
    m_ItemsRestockedIsSet = true;
}

bool ReturnLogisticsSummary::itemsRestockedIsSet() const
{
    return m_ItemsRestockedIsSet;
}

void ReturnLogisticsSummary::unsetItemsRestocked()
{
    m_ItemsRestockedIsSet = false;
}
int64_t ReturnLogisticsSummary::getItemsScrapped() const
{
    return m_ItemsScrapped;
}

void ReturnLogisticsSummary::setItemsScrapped(int64_t value)
{
    m_ItemsScrapped = value;
    m_ItemsScrappedIsSet = true;
}

bool ReturnLogisticsSummary::itemsScrappedIsSet() const
{
    return m_ItemsScrappedIsSet;
}

void ReturnLogisticsSummary::unsetItemsScrapped()
{
    m_ItemsScrappedIsSet = false;
}
int64_t ReturnLogisticsSummary::getTotalItems() const
{
    return m_TotalItems;
}

void ReturnLogisticsSummary::setTotalItems(int64_t value)
{
    m_TotalItems = value;
    m_TotalItemsIsSet = true;
}

bool ReturnLogisticsSummary::totalItemsIsSet() const
{
    return m_TotalItemsIsSet;
}

void ReturnLogisticsSummary::unsetTotalItems()
{
    m_TotalItemsIsSet = false;
}
int64_t ReturnLogisticsSummary::getTotalReturns() const
{
    return m_TotalReturns;
}

void ReturnLogisticsSummary::setTotalReturns(int64_t value)
{
    m_TotalReturns = value;
    m_TotalReturnsIsSet = true;
}

bool ReturnLogisticsSummary::totalReturnsIsSet() const
{
    return m_TotalReturnsIsSet;
}

void ReturnLogisticsSummary::unsetTotalReturns()
{
    m_TotalReturnsIsSet = false;
}

}
}
}
}


