/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ReturnWarehouseSummary.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ReturnWarehouseSummary::ReturnWarehouseSummary()
{
    m_ItemsRestocked = 0L;
    m_ItemsRestockedIsSet = false;
    m_ItemsScrapped = 0L;
    m_ItemsScrappedIsSet = false;
    m_Returns = 0L;
    m_ReturnsIsSet = false;
}

ReturnWarehouseSummary::~ReturnWarehouseSummary()
{
}

void ReturnWarehouseSummary::validate()
{
    // TODO: implement validation
}

web::json::value ReturnWarehouseSummary::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ItemsRestockedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))] = ModelBase::toJson(m_ItemsRestocked);
    }
    if(m_ItemsScrappedIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))] = ModelBase::toJson(m_ItemsScrapped);
    }
    if(m_ReturnsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("returns"))] = ModelBase::toJson(m_Returns);
    }
    if(m_WarehouseId.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("warehouseId"))] = ModelBase::toJson(m_WarehouseId.get());
    }

    return val;
}

bool ReturnWarehouseSummary::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setItemsRestocked;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItemsRestocked);
            setItemsRestocked(refVal_setItemsRestocked);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setItemsScrapped;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItemsScrapped);
            setItemsScrapped(refVal_setItemsScrapped);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("returns"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("returns")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setReturns;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReturns);
            setReturns(refVal_setReturns);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("warehouseId"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("warehouseId")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setWarehouseId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWarehouseId);
            setWarehouseId(refVal_setWarehouseId);
            
        }
    }
    return ok;
}

void ReturnWarehouseSummary::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ItemsRestockedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("itemsRestocked")), m_ItemsRestocked));
    }
    if(m_ItemsScrappedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("itemsScrapped")), m_ItemsScrapped));
    }
    if(m_ReturnsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("returns")), m_Returns));
    }
    if(m_WarehouseId.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("warehouseId")), m_WarehouseId.get()));
    }
}

bool ReturnWarehouseSummary::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))))
    {
        int64_t refVal_setItemsRestocked;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("itemsRestocked"))), refVal_setItemsRestocked );
        setItemsRestocked(refVal_setItemsRestocked);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))))
    {
        int64_t refVal_setItemsScrapped;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("itemsScrapped"))), refVal_setItemsScrapped );
        setItemsScrapped(refVal_setItemsScrapped);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("returns"))))
    {
        int64_t refVal_setReturns;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("returns"))), refVal_setReturns );
        setReturns(refVal_setReturns);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("warehouseId"))))
    {
        utility::string_t refVal_setWarehouseId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("warehouseId"))), refVal_setWarehouseId );
        setWarehouseId(refVal_setWarehouseId);
    }
    return ok;
}


int64_t ReturnWarehouseSummary::getItemsRestocked() const
{
    return m_ItemsRestocked;
}

void ReturnWarehouseSummary::setItemsRestocked(int64_t value)
{
    m_ItemsRestocked = value;
    m_ItemsRestockedIsSet = true;
}

bool ReturnWarehouseSummary::itemsRestockedIsSet() const
{
    return m_ItemsRestockedIsSet;
}

void ReturnWarehouseSummary::unsetItemsRestocked()
{
    m_ItemsRestockedIsSet = false;
}
int64_t ReturnWarehouseSummary::getItemsScrapped() const
{
    return m_ItemsScrapped;
}

void ReturnWarehouseSummary::setItemsScrapped(int64_t value)
{
    m_ItemsScrapped = value;
    m_ItemsScrappedIsSet = true;
}

bool ReturnWarehouseSummary::itemsScrappedIsSet() const
{
    return m_ItemsScrappedIsSet;
}

void ReturnWarehouseSummary::unsetItemsScrapped()
{
    m_ItemsScrappedIsSet = false;
}
int64_t ReturnWarehouseSummary::getReturns() const
{
    return m_Returns;
}

void ReturnWarehouseSummary::setReturns(int64_t value)
{
    m_Returns = value;
    m_ReturnsIsSet = true;
}

bool ReturnWarehouseSummary::returnsIsSet() const
{
    return m_ReturnsIsSet;
}

void ReturnWarehouseSummary::unsetReturns()
{
    m_ReturnsIsSet = false;
}
utility::string_t ReturnWarehouseSummary::getWarehouseId() const
{
    return m_WarehouseId.get();
}


void ReturnWarehouseSummary::setWarehouseId(const utility::string_t& value)
{
    m_WarehouseId = value;
}

bool ReturnWarehouseSummary::warehouseIdIsSet() const
{
    return m_WarehouseId.has_value();
}

void ReturnWarehouseSummary::unsetWarehouseId()
{
    m_WarehouseId.reset();
}

}
}
}
}


