/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ScopeTotal.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ScopeTotal::ScopeTotal()
{
    m_Scope = utility::conversions::to_string_t("");
    m_ScopeIsSet = false;
    m_Tco2e = utility::conversions::to_string_t("");
    m_Tco2eIsSet = false;
}

ScopeTotal::~ScopeTotal()
{
}

void ScopeTotal::validate()
{
    // TODO: implement validation
}

web::json::value ScopeTotal::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_ScopeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("scope"))] = ModelBase::toJson(m_Scope);
    }
    if(m_Tco2eIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tco2e"))] = ModelBase::toJson(m_Tco2e);
    }

    return val;
}

bool ScopeTotal::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("scope")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setScope;
            ok &= ModelBase::fromJson(fieldValue, refVal_setScope);
            setScope(refVal_setScope);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tco2e"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tco2e")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTco2e;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTco2e);
            setTco2e(refVal_setTco2e);
            
        }
    }
    return ok;
}

void ScopeTotal::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_ScopeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("scope")), m_Scope));
    }
    if(m_Tco2eIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tco2e")), m_Tco2e));
    }
}

bool ScopeTotal::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("scope"))))
    {
        utility::string_t refVal_setScope;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("scope"))), refVal_setScope );
        setScope(refVal_setScope);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tco2e"))))
    {
        utility::string_t refVal_setTco2e;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tco2e"))), refVal_setTco2e );
        setTco2e(refVal_setTco2e);
    }
    return ok;
}


utility::string_t ScopeTotal::getScope() const
{
    return m_Scope;
}


void ScopeTotal::setScope(const utility::string_t& value)
{
    m_Scope = value;
    m_ScopeIsSet = true;
}

bool ScopeTotal::scopeIsSet() const
{
    return m_ScopeIsSet;
}

void ScopeTotal::unsetScope()
{
    m_ScopeIsSet = false;
}
utility::string_t ScopeTotal::getTco2e() const
{
    return m_Tco2e;
}


void ScopeTotal::setTco2e(const utility::string_t& value)
{
    m_Tco2e = value;
    m_Tco2eIsSet = true;
}

bool ScopeTotal::tco2eIsSet() const
{
    return m_Tco2eIsSet;
}

void ScopeTotal::unsetTco2e()
{
    m_Tco2eIsSet = false;
}

}
}
}
}


