/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/ShippingRuleCreate.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

ShippingRuleCreate::ShippingRuleCreate()
{
    m_IsActive = false;
    m_IsActiveIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Price = utility::conversions::to_string_t("");
    m_PriceIsSet = false;
    m_Priority = 0;
    m_PriorityIsSet = false;
}

ShippingRuleCreate::~ShippingRuleCreate()
{
}

void ShippingRuleCreate::validate()
{
    // TODO: implement validation
}

web::json::value ShippingRuleCreate::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Carrier.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("carrier"))] = ModelBase::toJson(m_Carrier.get());
    }
    if(m_Country.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("country"))] = ModelBase::toJson(m_Country.get());
    }
    if(m_DeliveryTime.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("deliveryTime"))] = ModelBase::toJson(m_DeliveryTime.get());
    }
    if(m_IsActiveIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("isActive"))] = ModelBase::toJson(m_IsActive);
    }
    if(m_MaxWeightKg.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("maxWeightKg"))] = ModelBase::toJson(m_MaxWeightKg.get());
    }
    if(m_MinWeightKg.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("minWeightKg"))] = ModelBase::toJson(m_MinWeightKg.get());
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Notes.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("notes"))] = ModelBase::toJson(m_Notes.get());
    }
    if(m_PriceIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("price"))] = ModelBase::toJson(m_Price);
    }
    if(m_PriorityIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("priority"))] = ModelBase::toJson(m_Priority);
    }

    return val;
}

bool ShippingRuleCreate::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("carrier"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("carrier")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCarrier;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCarrier);
            setCarrier(refVal_setCarrier);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("country")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<CountryCode> refVal_setCountry;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountry);
            setCountry(refVal_setCountry);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("deliveryTime"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("deliveryTime")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeliveryTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeliveryTime);
            setDeliveryTime(refVal_setDeliveryTime);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("isActive"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("isActive")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsActive;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsActive);
            setIsActive(refVal_setIsActive);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("maxWeightKg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("maxWeightKg")));
        if(!fieldValue.is_null())
        {
            double refVal_setMaxWeightKg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxWeightKg);
            setMaxWeightKg(refVal_setMaxWeightKg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("minWeightKg"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("minWeightKg")));
        if(!fieldValue.is_null())
        {
            double refVal_setMinWeightKg;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMinWeightKg);
            setMinWeightKg(refVal_setMinWeightKg);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("notes"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("notes")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNotes;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotes);
            setNotes(refVal_setNotes);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("price"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("price")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPrice;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrice);
            setPrice(refVal_setPrice);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("priority"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("priority")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPriority;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPriority);
            setPriority(refVal_setPriority);
            
        }
    }
    return ok;
}

void ShippingRuleCreate::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Carrier.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("carrier")), m_Carrier.get()));
    }
    if(m_Country.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("country")), m_Country.get()));
    }
    if(m_DeliveryTime.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("deliveryTime")), m_DeliveryTime.get()));
    }
    if(m_IsActiveIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("isActive")), m_IsActive));
    }
    if(m_MaxWeightKg.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("maxWeightKg")), m_MaxWeightKg.get()));
    }
    if(m_MinWeightKg.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("minWeightKg")), m_MinWeightKg.get()));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Notes.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("notes")), m_Notes.get()));
    }
    if(m_PriceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("price")), m_Price));
    }
    if(m_PriorityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("priority")), m_Priority));
    }
}

bool ShippingRuleCreate::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("carrier"))))
    {
        utility::string_t refVal_setCarrier;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("carrier"))), refVal_setCarrier );
        setCarrier(refVal_setCarrier);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("country"))))
    {
        std::shared_ptr<CountryCode> refVal_setCountry;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("country"))), refVal_setCountry );
        setCountry(refVal_setCountry);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("deliveryTime"))))
    {
        utility::string_t refVal_setDeliveryTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("deliveryTime"))), refVal_setDeliveryTime );
        setDeliveryTime(refVal_setDeliveryTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("isActive"))))
    {
        bool refVal_setIsActive;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("isActive"))), refVal_setIsActive );
        setIsActive(refVal_setIsActive);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("maxWeightKg"))))
    {
        double refVal_setMaxWeightKg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("maxWeightKg"))), refVal_setMaxWeightKg );
        setMaxWeightKg(refVal_setMaxWeightKg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("minWeightKg"))))
    {
        double refVal_setMinWeightKg;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("minWeightKg"))), refVal_setMinWeightKg );
        setMinWeightKg(refVal_setMinWeightKg);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("notes"))))
    {
        utility::string_t refVal_setNotes;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("notes"))), refVal_setNotes );
        setNotes(refVal_setNotes);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("price"))))
    {
        utility::string_t refVal_setPrice;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("price"))), refVal_setPrice );
        setPrice(refVal_setPrice);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("priority"))))
    {
        int32_t refVal_setPriority;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("priority"))), refVal_setPriority );
        setPriority(refVal_setPriority);
    }
    return ok;
}


utility::string_t ShippingRuleCreate::getCarrier() const
{
    return m_Carrier.get();
}


void ShippingRuleCreate::setCarrier(const utility::string_t& value)
{
    m_Carrier = value;
}

bool ShippingRuleCreate::carrierIsSet() const
{
    return m_Carrier.has_value();
}

void ShippingRuleCreate::unsetCarrier()
{
    m_Carrier.reset();
}
std::shared_ptr<CountryCode> ShippingRuleCreate::getCountry() const
{
    return m_Country.get();
}


void ShippingRuleCreate::setCountry(const std::shared_ptr<CountryCode>& value)
{
    m_Country = value;
}

bool ShippingRuleCreate::countryIsSet() const
{
    return m_Country.has_value();
}

void ShippingRuleCreate::unsetCountry()
{
    m_Country.reset();
}
utility::string_t ShippingRuleCreate::getDeliveryTime() const
{
    return m_DeliveryTime.get();
}


void ShippingRuleCreate::setDeliveryTime(const utility::string_t& value)
{
    m_DeliveryTime = value;
}

bool ShippingRuleCreate::deliveryTimeIsSet() const
{
    return m_DeliveryTime.has_value();
}

void ShippingRuleCreate::unsetDeliveryTime()
{
    m_DeliveryTime.reset();
}
bool ShippingRuleCreate::isIsActive() const
{
    return m_IsActive;
}

void ShippingRuleCreate::setIsActive(bool value)
{
    m_IsActive = value;
    m_IsActiveIsSet = true;
}

bool ShippingRuleCreate::isActiveIsSet() const
{
    return m_IsActiveIsSet;
}

void ShippingRuleCreate::unsetIsActive()
{
    m_IsActiveIsSet = false;
}
double ShippingRuleCreate::getMaxWeightKg() const
{
    return m_MaxWeightKg.get();
}

void ShippingRuleCreate::setMaxWeightKg(double value)
{
    m_MaxWeightKg = value;
}

bool ShippingRuleCreate::maxWeightKgIsSet() const
{
    return m_MaxWeightKg.has_value();
}

void ShippingRuleCreate::unsetMaxWeightKg()
{
    m_MaxWeightKg.reset();
}
double ShippingRuleCreate::getMinWeightKg() const
{
    return m_MinWeightKg.get();
}

void ShippingRuleCreate::setMinWeightKg(double value)
{
    m_MinWeightKg = value;
}

bool ShippingRuleCreate::minWeightKgIsSet() const
{
    return m_MinWeightKg.has_value();
}

void ShippingRuleCreate::unsetMinWeightKg()
{
    m_MinWeightKg.reset();
}
utility::string_t ShippingRuleCreate::getName() const
{
    return m_Name;
}


void ShippingRuleCreate::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool ShippingRuleCreate::nameIsSet() const
{
    return m_NameIsSet;
}

void ShippingRuleCreate::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t ShippingRuleCreate::getNotes() const
{
    return m_Notes.get();
}


void ShippingRuleCreate::setNotes(const utility::string_t& value)
{
    m_Notes = value;
}

bool ShippingRuleCreate::notesIsSet() const
{
    return m_Notes.has_value();
}

void ShippingRuleCreate::unsetNotes()
{
    m_Notes.reset();
}
utility::string_t ShippingRuleCreate::getPrice() const
{
    return m_Price;
}


void ShippingRuleCreate::setPrice(const utility::string_t& value)
{
    m_Price = value;
    m_PriceIsSet = true;
}

bool ShippingRuleCreate::priceIsSet() const
{
    return m_PriceIsSet;
}

void ShippingRuleCreate::unsetPrice()
{
    m_PriceIsSet = false;
}
int32_t ShippingRuleCreate::getPriority() const
{
    return m_Priority;
}

void ShippingRuleCreate::setPriority(int32_t value)
{
    m_Priority = value;
    m_PriorityIsSet = true;
}

bool ShippingRuleCreate::priorityIsSet() const
{
    return m_PriorityIsSet;
}

void ShippingRuleCreate::unsetPriority()
{
    m_PriorityIsSet = false;
}

}
}
}
}


