/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/StillePartnerZeile.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

StillePartnerZeile::StillePartnerZeile()
{
    m_Auseinandersetzungsguthaben = utility::conversions::to_string_t("");
    m_AuseinandersetzungsguthabenIsSet = false;
    m_Gewinnanteil = utility::conversions::to_string_t("");
    m_GewinnanteilIsSet = false;
    m_Gewinnvortrag = utility::conversions::to_string_t("");
    m_GewinnvortragIsSet = false;
    m_Instrument_type = utility::conversions::to_string_t("");
    m_Instrument_typeIsSet = false;
    m_Kest = utility::conversions::to_string_t("");
    m_KestIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Verlust_verrechnungskonto = utility::conversions::to_string_t("");
    m_Verlust_verrechnungskontoIsSet = false;
    m_Verlustanteil = utility::conversions::to_string_t("");
    m_VerlustanteilIsSet = false;
}

StillePartnerZeile::~StillePartnerZeile()
{
}

void StillePartnerZeile::validate()
{
    // TODO: implement validation
}

web::json::value StillePartnerZeile::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_AuseinandersetzungsguthabenIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben"))] = ModelBase::toJson(m_Auseinandersetzungsguthaben);
    }
    if(m_GewinnanteilIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gewinnanteil"))] = ModelBase::toJson(m_Gewinnanteil);
    }
    if(m_GewinnvortragIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag"))] = ModelBase::toJson(m_Gewinnvortrag);
    }
    if(m_Hinweis.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("hinweis"))] = ModelBase::toJson(m_Hinweis.get());
    }
    if(m_Instrument_typeIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("instrument_type"))] = ModelBase::toJson(m_Instrument_type);
    }
    if(m_KestIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("kest"))] = ModelBase::toJson(m_Kest);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Verlust_verrechnungskontoIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto"))] = ModelBase::toJson(m_Verlust_verrechnungskonto);
    }
    if(m_VerlustanteilIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("verlustanteil"))] = ModelBase::toJson(m_Verlustanteil);
    }

    return val;
}

bool StillePartnerZeile::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAuseinandersetzungsguthaben;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuseinandersetzungsguthaben);
            setAuseinandersetzungsguthaben(refVal_setAuseinandersetzungsguthaben);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gewinnanteil"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gewinnanteil")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGewinnanteil;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGewinnanteil);
            setGewinnanteil(refVal_setGewinnanteil);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGewinnvortrag;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGewinnvortrag);
            setGewinnvortrag(refVal_setGewinnvortrag);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("hinweis"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("hinweis")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHinweis;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHinweis);
            setHinweis(refVal_setHinweis);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("instrument_type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("instrument_type")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInstrumentType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInstrumentType);
            setInstrumentType(refVal_setInstrumentType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("kest"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("kest")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKest;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKest);
            setKest(refVal_setKest);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVerlustVerrechnungskonto;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerlustVerrechnungskonto);
            setVerlustVerrechnungskonto(refVal_setVerlustVerrechnungskonto);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("verlustanteil"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("verlustanteil")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVerlustanteil;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVerlustanteil);
            setVerlustanteil(refVal_setVerlustanteil);
            
        }
    }
    return ok;
}

void StillePartnerZeile::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_AuseinandersetzungsguthabenIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben")), m_Auseinandersetzungsguthaben));
    }
    if(m_GewinnanteilIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gewinnanteil")), m_Gewinnanteil));
    }
    if(m_GewinnvortragIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag")), m_Gewinnvortrag));
    }
    if(m_Hinweis.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("hinweis")), m_Hinweis.get()));
    }
    if(m_Instrument_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("instrument_type")), m_Instrument_type));
    }
    if(m_KestIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("kest")), m_Kest));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_Verlust_verrechnungskontoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto")), m_Verlust_verrechnungskonto));
    }
    if(m_VerlustanteilIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("verlustanteil")), m_Verlustanteil));
    }
}

bool StillePartnerZeile::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben"))))
    {
        utility::string_t refVal_setAuseinandersetzungsguthaben;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("auseinandersetzungsguthaben"))), refVal_setAuseinandersetzungsguthaben );
        setAuseinandersetzungsguthaben(refVal_setAuseinandersetzungsguthaben);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gewinnanteil"))))
    {
        utility::string_t refVal_setGewinnanteil;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gewinnanteil"))), refVal_setGewinnanteil );
        setGewinnanteil(refVal_setGewinnanteil);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag"))))
    {
        utility::string_t refVal_setGewinnvortrag;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("gewinnvortrag"))), refVal_setGewinnvortrag );
        setGewinnvortrag(refVal_setGewinnvortrag);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("hinweis"))))
    {
        utility::string_t refVal_setHinweis;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("hinweis"))), refVal_setHinweis );
        setHinweis(refVal_setHinweis);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("instrument_type"))))
    {
        utility::string_t refVal_setInstrumentType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("instrument_type"))), refVal_setInstrumentType );
        setInstrumentType(refVal_setInstrumentType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("kest"))))
    {
        utility::string_t refVal_setKest;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("kest"))), refVal_setKest );
        setKest(refVal_setKest);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto"))))
    {
        utility::string_t refVal_setVerlustVerrechnungskonto;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verlust_verrechnungskonto"))), refVal_setVerlustVerrechnungskonto );
        setVerlustVerrechnungskonto(refVal_setVerlustVerrechnungskonto);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("verlustanteil"))))
    {
        utility::string_t refVal_setVerlustanteil;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("verlustanteil"))), refVal_setVerlustanteil );
        setVerlustanteil(refVal_setVerlustanteil);
    }
    return ok;
}


utility::string_t StillePartnerZeile::getAuseinandersetzungsguthaben() const
{
    return m_Auseinandersetzungsguthaben;
}


void StillePartnerZeile::setAuseinandersetzungsguthaben(const utility::string_t& value)
{
    m_Auseinandersetzungsguthaben = value;
    m_AuseinandersetzungsguthabenIsSet = true;
}

bool StillePartnerZeile::auseinandersetzungsguthabenIsSet() const
{
    return m_AuseinandersetzungsguthabenIsSet;
}

void StillePartnerZeile::unsetAuseinandersetzungsguthaben()
{
    m_AuseinandersetzungsguthabenIsSet = false;
}
utility::string_t StillePartnerZeile::getGewinnanteil() const
{
    return m_Gewinnanteil;
}


void StillePartnerZeile::setGewinnanteil(const utility::string_t& value)
{
    m_Gewinnanteil = value;
    m_GewinnanteilIsSet = true;
}

bool StillePartnerZeile::gewinnanteilIsSet() const
{
    return m_GewinnanteilIsSet;
}

void StillePartnerZeile::unsetGewinnanteil()
{
    m_GewinnanteilIsSet = false;
}
utility::string_t StillePartnerZeile::getGewinnvortrag() const
{
    return m_Gewinnvortrag;
}


void StillePartnerZeile::setGewinnvortrag(const utility::string_t& value)
{
    m_Gewinnvortrag = value;
    m_GewinnvortragIsSet = true;
}

bool StillePartnerZeile::gewinnvortragIsSet() const
{
    return m_GewinnvortragIsSet;
}

void StillePartnerZeile::unsetGewinnvortrag()
{
    m_GewinnvortragIsSet = false;
}
utility::string_t StillePartnerZeile::getHinweis() const
{
    return m_Hinweis.get();
}


void StillePartnerZeile::setHinweis(const utility::string_t& value)
{
    m_Hinweis = value;
}

bool StillePartnerZeile::hinweisIsSet() const
{
    return m_Hinweis.has_value();
}

void StillePartnerZeile::unsetHinweis()
{
    m_Hinweis.reset();
}
utility::string_t StillePartnerZeile::getInstrumentType() const
{
    return m_Instrument_type;
}


void StillePartnerZeile::setInstrumentType(const utility::string_t& value)
{
    m_Instrument_type = value;
    m_Instrument_typeIsSet = true;
}

bool StillePartnerZeile::instrumentTypeIsSet() const
{
    return m_Instrument_typeIsSet;
}

void StillePartnerZeile::unsetInstrument_type()
{
    m_Instrument_typeIsSet = false;
}
utility::string_t StillePartnerZeile::getKest() const
{
    return m_Kest;
}


void StillePartnerZeile::setKest(const utility::string_t& value)
{
    m_Kest = value;
    m_KestIsSet = true;
}

bool StillePartnerZeile::kestIsSet() const
{
    return m_KestIsSet;
}

void StillePartnerZeile::unsetKest()
{
    m_KestIsSet = false;
}
utility::string_t StillePartnerZeile::getName() const
{
    return m_Name;
}


void StillePartnerZeile::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool StillePartnerZeile::nameIsSet() const
{
    return m_NameIsSet;
}

void StillePartnerZeile::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t StillePartnerZeile::getVerlustVerrechnungskonto() const
{
    return m_Verlust_verrechnungskonto;
}


void StillePartnerZeile::setVerlustVerrechnungskonto(const utility::string_t& value)
{
    m_Verlust_verrechnungskonto = value;
    m_Verlust_verrechnungskontoIsSet = true;
}

bool StillePartnerZeile::verlustVerrechnungskontoIsSet() const
{
    return m_Verlust_verrechnungskontoIsSet;
}

void StillePartnerZeile::unsetVerlust_verrechnungskonto()
{
    m_Verlust_verrechnungskontoIsSet = false;
}
utility::string_t StillePartnerZeile::getVerlustanteil() const
{
    return m_Verlustanteil;
}


void StillePartnerZeile::setVerlustanteil(const utility::string_t& value)
{
    m_Verlustanteil = value;
    m_VerlustanteilIsSet = true;
}

bool StillePartnerZeile::verlustanteilIsSet() const
{
    return m_VerlustanteilIsSet;
}

void StillePartnerZeile::unsetVerlustanteil()
{
    m_VerlustanteilIsSet = false;
}

}
}
}
}


