/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/UpsCredentials.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

UpsCredentials::UpsCredentials()
{
    m_Client_id = utility::conversions::to_string_t("");
    m_Client_idIsSet = false;
    m_Client_secret = utility::conversions::to_string_t("");
    m_Client_secretIsSet = false;
}

UpsCredentials::~UpsCredentials()
{
}

void UpsCredentials::validate()
{
    // TODO: implement validation
}

web::json::value UpsCredentials::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Client_idIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_id"))] = ModelBase::toJson(m_Client_id);
    }
    if(m_Client_secretIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("client_secret"))] = ModelBase::toJson(m_Client_secret);
    }
    if(m_Shipper_number.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("shipper_number"))] = ModelBase::toJson(m_Shipper_number.get());
    }

    return val;
}

bool UpsCredentials::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientId);
            setClientId(refVal_setClientId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("client_secret"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("client_secret")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setClientSecret;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClientSecret);
            setClientSecret(refVal_setClientSecret);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("shipper_number"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("shipper_number")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setShipperNumber;
            ok &= ModelBase::fromJson(fieldValue, refVal_setShipperNumber);
            setShipperNumber(refVal_setShipperNumber);
            
        }
    }
    return ok;
}

void UpsCredentials::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Client_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_id")), m_Client_id));
    }
    if(m_Client_secretIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("client_secret")), m_Client_secret));
    }
    if(m_Shipper_number.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("shipper_number")), m_Shipper_number.get()));
    }
}

bool UpsCredentials::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_id"))))
    {
        utility::string_t refVal_setClientId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_id"))), refVal_setClientId );
        setClientId(refVal_setClientId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("client_secret"))))
    {
        utility::string_t refVal_setClientSecret;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("client_secret"))), refVal_setClientSecret );
        setClientSecret(refVal_setClientSecret);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("shipper_number"))))
    {
        utility::string_t refVal_setShipperNumber;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("shipper_number"))), refVal_setShipperNumber );
        setShipperNumber(refVal_setShipperNumber);
    }
    return ok;
}


utility::string_t UpsCredentials::getClientId() const
{
    return m_Client_id;
}


void UpsCredentials::setClientId(const utility::string_t& value)
{
    m_Client_id = value;
    m_Client_idIsSet = true;
}

bool UpsCredentials::clientIdIsSet() const
{
    return m_Client_idIsSet;
}

void UpsCredentials::unsetClient_id()
{
    m_Client_idIsSet = false;
}
utility::string_t UpsCredentials::getClientSecret() const
{
    return m_Client_secret;
}


void UpsCredentials::setClientSecret(const utility::string_t& value)
{
    m_Client_secret = value;
    m_Client_secretIsSet = true;
}

bool UpsCredentials::clientSecretIsSet() const
{
    return m_Client_secretIsSet;
}

void UpsCredentials::unsetClient_secret()
{
    m_Client_secretIsSet = false;
}
utility::string_t UpsCredentials::getShipperNumber() const
{
    return m_Shipper_number.get();
}


void UpsCredentials::setShipperNumber(const utility::string_t& value)
{
    m_Shipper_number = value;
}

bool UpsCredentials::shipperNumberIsSet() const
{
    return m_Shipper_number.has_value();
}

void UpsCredentials::unsetShipper_number()
{
    m_Shipper_number.reset();
}

}
}
}
}


