/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/VatItem.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

VatItem::VatItem()
{
    m_Net_amount = utility::conversions::to_string_t("");
    m_Net_amountIsSet = false;
    m_Tax_amount = utility::conversions::to_string_t("");
    m_Tax_amountIsSet = false;
    m_Tax_rate = utility::conversions::to_string_t("");
    m_Tax_rateIsSet = false;
}

VatItem::~VatItem()
{
}

void VatItem::validate()
{
    // TODO: implement validation
}

web::json::value VatItem::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Net_amountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("net_amount"))] = ModelBase::toJson(m_Net_amount);
    }
    if(m_Tax_amountIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tax_amount"))] = ModelBase::toJson(m_Tax_amount);
    }
    if(m_Tax_rateIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("tax_rate"))] = ModelBase::toJson(m_Tax_rate);
    }

    return val;
}

bool VatItem::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("net_amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("net_amount")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNetAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNetAmount);
            setNetAmount(refVal_setNetAmount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tax_amount"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tax_amount")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTaxAmount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaxAmount);
            setTaxAmount(refVal_setTaxAmount);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tax_rate"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tax_rate")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTaxRate;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTaxRate);
            setTaxRate(refVal_setTaxRate);
            
        }
    }
    return ok;
}

void VatItem::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Net_amountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("net_amount")), m_Net_amount));
    }
    if(m_Tax_amountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tax_amount")), m_Tax_amount));
    }
    if(m_Tax_rateIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tax_rate")), m_Tax_rate));
    }
}

bool VatItem::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("net_amount"))))
    {
        utility::string_t refVal_setNetAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("net_amount"))), refVal_setNetAmount );
        setNetAmount(refVal_setNetAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tax_amount"))))
    {
        utility::string_t refVal_setTaxAmount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tax_amount"))), refVal_setTaxAmount );
        setTaxAmount(refVal_setTaxAmount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tax_rate"))))
    {
        utility::string_t refVal_setTaxRate;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tax_rate"))), refVal_setTaxRate );
        setTaxRate(refVal_setTaxRate);
    }
    return ok;
}


utility::string_t VatItem::getNetAmount() const
{
    return m_Net_amount;
}


void VatItem::setNetAmount(const utility::string_t& value)
{
    m_Net_amount = value;
    m_Net_amountIsSet = true;
}

bool VatItem::netAmountIsSet() const
{
    return m_Net_amountIsSet;
}

void VatItem::unsetNet_amount()
{
    m_Net_amountIsSet = false;
}
utility::string_t VatItem::getTaxAmount() const
{
    return m_Tax_amount;
}


void VatItem::setTaxAmount(const utility::string_t& value)
{
    m_Tax_amount = value;
    m_Tax_amountIsSet = true;
}

bool VatItem::taxAmountIsSet() const
{
    return m_Tax_amountIsSet;
}

void VatItem::unsetTax_amount()
{
    m_Tax_amountIsSet = false;
}
utility::string_t VatItem::getTaxRate() const
{
    return m_Tax_rate;
}


void VatItem::setTaxRate(const utility::string_t& value)
{
    m_Tax_rate = value;
    m_Tax_rateIsSet = true;
}

bool VatItem::taxRateIsSet() const
{
    return m_Tax_rateIsSet;
}

void VatItem::unsetTax_rate()
{
    m_Tax_rateIsSet = false;
}

}
}
}
}


