/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.25.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/Verfahrensdokumentation.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

Verfahrensdokumentation::Verfahrensdokumentation()
{
    m_EntriesIsSet = false;
    m_Generated_at = utility::conversions::to_string_t("");
    m_Generated_atIsSet = false;
    m_Title = utility::conversions::to_string_t("");
    m_TitleIsSet = false;
    m_Version = utility::conversions::to_string_t("");
    m_VersionIsSet = false;
}

Verfahrensdokumentation::~Verfahrensdokumentation()
{
}

void Verfahrensdokumentation::validate()
{
    // TODO: implement validation
}

web::json::value Verfahrensdokumentation::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_EntriesIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("entries"))] = ModelBase::toJson(m_Entries);
    }
    if(m_Generated_atIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("generated_at"))] = ModelBase::toJson(m_Generated_at);
    }
    if(m_TitleIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("title"))] = ModelBase::toJson(m_Title);
    }
    if(m_VersionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("version"))] = ModelBase::toJson(m_Version);
    }

    return val;
}

bool Verfahrensdokumentation::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("entries"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("entries")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ComplianceEntry>> refVal_setEntries;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEntries);
            setEntries(refVal_setEntries);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("generated_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("generated_at")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setGeneratedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setGeneratedAt);
            setGeneratedAt(refVal_setGeneratedAt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("title")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTitle;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTitle);
            setTitle(refVal_setTitle);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("version")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setVersion;
            ok &= ModelBase::fromJson(fieldValue, refVal_setVersion);
            setVersion(refVal_setVersion);
            
        }
    }
    return ok;
}

void Verfahrensdokumentation::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_EntriesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("entries")), m_Entries));
    }
    if(m_Generated_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("generated_at")), m_Generated_at));
    }
    if(m_TitleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("title")), m_Title));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("version")), m_Version));
    }
}

bool Verfahrensdokumentation::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("entries"))))
    {
        std::vector<std::shared_ptr<ComplianceEntry>> refVal_setEntries;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("entries"))), refVal_setEntries );
        setEntries(refVal_setEntries);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("generated_at"))))
    {
        utility::string_t refVal_setGeneratedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("generated_at"))), refVal_setGeneratedAt );
        setGeneratedAt(refVal_setGeneratedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("title"))))
    {
        utility::string_t refVal_setTitle;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("title"))), refVal_setTitle );
        setTitle(refVal_setTitle);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("version"))))
    {
        utility::string_t refVal_setVersion;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("version"))), refVal_setVersion );
        setVersion(refVal_setVersion);
    }
    return ok;
}


std::vector<std::shared_ptr<ComplianceEntry>> Verfahrensdokumentation::getEntries() const
{
    return m_Entries;
}


void Verfahrensdokumentation::setEntries(const std::vector<std::shared_ptr<ComplianceEntry>>& value)
{
    m_Entries = value;
    m_EntriesIsSet = true;
}

bool Verfahrensdokumentation::entriesIsSet() const
{
    return m_EntriesIsSet;
}

void Verfahrensdokumentation::unsetEntries()
{
    m_EntriesIsSet = false;
}
utility::string_t Verfahrensdokumentation::getGeneratedAt() const
{
    return m_Generated_at;
}


void Verfahrensdokumentation::setGeneratedAt(const utility::string_t& value)
{
    m_Generated_at = value;
    m_Generated_atIsSet = true;
}

bool Verfahrensdokumentation::generatedAtIsSet() const
{
    return m_Generated_atIsSet;
}

void Verfahrensdokumentation::unsetGenerated_at()
{
    m_Generated_atIsSet = false;
}
utility::string_t Verfahrensdokumentation::getTitle() const
{
    return m_Title;
}


void Verfahrensdokumentation::setTitle(const utility::string_t& value)
{
    m_Title = value;
    m_TitleIsSet = true;
}

bool Verfahrensdokumentation::titleIsSet() const
{
    return m_TitleIsSet;
}

void Verfahrensdokumentation::unsetTitle()
{
    m_TitleIsSet = false;
}
utility::string_t Verfahrensdokumentation::getVersion() const
{
    return m_Version;
}


void Verfahrensdokumentation::setVersion(const utility::string_t& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool Verfahrensdokumentation::versionIsSet() const
{
    return m_VersionIsSet;
}

void Verfahrensdokumentation::unsetVersion()
{
    m_VersionIsSet = false;
}

}
}
}
}


